.Id $Id: idc.1,v 1.2 2000-10-21 15:02:02 jon Exp $
.Im mantools converters
.TH idc 1
.XI idc - "Information Database Compiler (Bug list converter)"
.SH NAME
idc \- Information Database Compiler (Bug list converter).
.SH SYNOPSIS
.sp 1
.na
\fBidc\fR
\fC[\fB\-?\fC]\fR
\fC[\fB\-d\fR\ \fI<debugLevel>\fC]\fR
\fC[\fB\-E\fR\ \fI<file>\fC]\fR
\fC[\fB\-e\fR\ \fI<file>\fC]\fR
\fC[\fB\-h\fC|\fB\-r\fC]\fR
\fC[\fB\-H\fR\ \fI<home>\fC]\fR
\fC[\fB\-I\fC]\fR
\fC[\fB\-i\fC]\fR
\fC[\fB\-o\fR\ \fI<file>\fC]\fR
\fC[\fB\-p\fR\ \fI<file>\fC]\fR
\fC[\fB\-q\fC]\fR
\fC[\fB\-t\fR\ \fI<title>\fC]\fR
\fC[\fB\-v\fR\ \fI<verboseLevel>\fC]\fR
\fC[\fBSF=0\fC]\fR
\fIfiles \.\.\.\fR
.ad
.SH DESCRIPTION
The  \fIInformation  Database  Compiler\fR  \-  \fBidc\fR  provides  an  error
cataloging  mechanism for tracking  development bugs \fI[bugs]\fR,  frequently
asked  questions   \fI[faq]\fR,  news  items   \fI[new]\fR,   technical  notes
\fI[tek]\fR,  release notes \fI[rel]\fR etc. The compiler takes as input a set
of ASCII text files (as defined by
.Ht idc 4 ),
with fixed field  formats,  generating  a set of hypertext  linked pages (with
indexes) in either  HyperText Markup Language (HTML) or Rich Text Format (RTF)
files.
.BS 1 1
The HTML files are produced with un-resolved references in the
.Ht htp 4
file format for use with the HTML compiler
.Ht htmlc 1 .
.BU
The RTF files are produced with the Windows Help Compiler  overloading for use
with the Microsoft Help Compiler
.Ht hc 1 .
.BE
The options to \fBidc\fR are defined as follows:
.IP "\fB\-?\fR"
Display a help message concerning the tool.
.IP "\fB\-d\fR\ \fI<debugLevel>\fR"
Enable  debugging  messages,  \fI<debugLevel>\fR  is a single digit  \fC0-9\fR
which enables the debugging  messages to be displayed.  The higher the number,
the more debugging is enabled. The default is disabled.
.\" -e <file> -E <file> : Error reporting.
.so opt_e.tni
.IP "[\fB\-h\fR|\fB\-r\fR]"
Determine  the output to be generated by the  Compiler.  The default when both
options are absent, or \fB\-h\fR is specified, is HTML format. RTF file format
is selected with the \fB\-r\fR option.
.\" -H <home> : Home page
.so opt_hh.tni
.IP \fB\-i\fR
Enable  interactive  (on-screen)  progress  information.  The  progress of the
compilation is displayed at the console, this is the default when omited.
.\" -I : Version information
.so opt_i.tni
.\" -o <file> : output file name.
.so opt_o.tni
.\" -p : Picture (image) mode.
.so opt_p.tni
The  default,  when  omitted,  is  \fBlogo.gif\fR   for  HTML  generation  and
\fBlogo.bmp\fR for RTF generation.
.\" -q : Quiet mode.
.so opt_q.tni
.IP "\fB\-t\fR\ \fI<title>\fR"
Specifies the name to use as the title. The default when omitted is 
.IR "Information Development Database" .
.IP "\fB\-v\fR\ \fI<verboseLevel>\fR"
Verbose  reporting  on the progress of the tool. The usual  setting is level 1
(the  default). The higher the number, the more verbose  reporting is enabled.
The default is enabled to level 1.
.IP "\fBSF=0\fR"
Disable the sorting  function on the  arguments, by default the  arguments are
sorted  into  alphabetical  order, this is not  desirable  when  dealing  with
multiple files on the input line. The order of some of the input is important.
.SH NOTES
It is recommended  that entries are retained in manageable  files. The typical
technique for reports is segmentation into files of 100 reports each. The file
names  typically  reflect the contents e.g.  \fCbug0700.bug\fR  would  contain
fault reports numbered 700-799 inclusive.
.SH "EXAMPLE"
The \fBidc\fR  converter is typically executed twice, once for the generate of
Windows  Help  Files and again for the HTML  files.  Each build is  considered
below:
.SS "Windows Help Production"
Windows help file generation is slightly different from the HTML conversion in
that a single  \fC.rtf\fR  is  generated  for each  source  file.  For a large
database the Window Help Compiler
.Ht hc 1
cannot cope with large files. The core of the Makefile is shown below:
.CS
buglist.hlp: $(BUGS) $(IDC) buglist.rsp buglist.hpj
        cp $(ROOTDIR)/etc/logo.bmp .
        $(IDC) -H jasspa -r -e idcrtf.err SF=0 @buglist.rsp
        $(HC31) buglist
        $(RM) *.rtf logo.bmp
.CE
Where  buglist.rsp  is a list of source  files  (the  global  definitions  are
defined in \fCdinf0000.bug\fR in this case e.g.
.CS
dinf0000.bug
dfaq0000.bug
dfaq0100.bug
dnew0000.bug
dtek0000.bug
dbug0000.bug
dbug0100.bug
dbug0200.bug
dbug0300.bug
dbug0400.bug
dbug0500.bug
dbug0600.bug
dbug0700.bug
dbug0800.bug
dbug0900.bug
dbug1000.bug
dbug1100.bug
dbug1200.bug
dbug1300.bug
dbug1400.bug
dbug1500.bug
dpat0000.bug
.CE
The Help file for the bug list is defined as:
.CS
; This help project requires hc 3.1
[OPTIONS]
errorlog = hc31.err
title = Development Information Database
contents = buglist
compress = 0
warning = 3
report = 1

[FILES]
dbug0000.rtf
dbug0100.rtf
dbug0200.rtf
dbug0300.rtf
dbug0400.rtf
dbug0500.rtf
dbug0600.rtf
dbug0700.rtf
dbug0800.rtf
dbug0900.rtf
dbug1000.rtf
dbug1100.rtf
dbug1200.rtf
dbug1300.rtf
dbug1400.rtf
dbug1500.rtf
dfaq0000.rtf
dfaq0100.rtf
dinf0000.rtf
dnew0000.rtf
dpat0000.rtf
dtek0000.rtf

[BITMAPS]
logo.bmp

[WINDOWS]
main = "Development Information Database",,,, (192,192,192 )

[CONFIG]
BrowseButtons()
.CE 0
.SS "HTML Production"
The HTML built is slightly easier as \fBidc\fR generates a single
.Ht htp 4
file which is compiled using
.Ht htmlc 1
generating a single
.Ht hts 4
file which may be expanded using
.Ht hts2html 1 .
The Makefile fragment is defined as follows:
.CS
buglist.hts: $(BUGS) $(IDC) buglist.rsp
        $(IDC) -H jasspa -h -o $@ -e idchtml.err SF=0 @buglist.rsp
        $(HTMLC) -v 1 -s buglist -o $@ buglist.htp
        $(RM) buglist.htp
.CE 0
.SH NOTES
Release 2.2.0 of the \fBidc\fR compiler introduced the in-line text formatting
constructs as defined by 
.Hl idc(4) idcFormat 4 .
The \fBBase Address:\fR  construct was removed and the  \fBftp:\fR/\fBeftp:\fR
group construct was removed and replaced with the in-line \fBftp:\fR function,
the \fBeftp:\fR construct is obsolete.
.SH "SEE ALSO"
.na
.Ht hc 1 ,
.Ht htmlc 1 ,
.Ht htp 4 ,
.Ht hts 4 ,
.Ht idc 4 .
.ad
.FH
