##-*- makefile -*-############################################################
#
#  Copyright (c) 2024 Detlef Groth.
# 
#
##############################################################################

## just for testing of a local install
pkg=microemacs-mec
## or reinstall
action=install
default:
	brew $(action) --build-from-source  $(pkg).rb

