##-*- makefile -*-############################################################
#
#  Copyright (c) 2024 Detlef Groth.
# 
#
##############################################################################

## just for testing of a local install
default:
	brew install --build-from-source  microemacs-mec.rb

