.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2006 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd059.2,v 2.6 2006-08-21 20:40:45 jon Exp $
.Im MicroEmacs command|region
.ds C0 "(\fB\*(cXa\fR)\ \&
.so me.tni
.TH goto-alpha-mark 2
.XI goto-alpha-mark \- "\*(C0Move the cursor to a alpha marked location"
.SH NAME
goto-alpha-mark \- Move the cursor to a alpha marked location
.Me $a
.SH SYNOPSIS
.na
.B goto-alpha-mark
"\fI?\fR" \*(C0
.br
.I 0
.B goto-alpha-mark
.ad
.SH DESCRIPTION
.B goto-alpha-mark
prompts user for an alpha character and sets the cursor position to the preset
location.  Alpha marks are  specified on a per buffer  basis, thus the current
buffer is not  changed,  merely the current  location in the buffer. The alpha
mark must already be defined using
.Ht set-alpha-mark 2 .
This  functionality is useful for rapidly returning back to locations in large
files.
.PP
.B goto-alpha-mark
with a numeric  argument  of zero (0) returns a string  containing  all of the
alpha  marks  that  exist in the  current  buffer.  The alpha  mark  string is
returned in 
.Ht $result 5 ,
this is an empty  string if there are no alpha marks in the buffer.  
.SH "SEE ALSO"
.na
.Ht set-alpha-mark 2 .
.ad
.rm C0
.FH
