.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd046.2,v 2.6 2009-08-29 17:13:09 jon Exp $
.Im MicroEmacs command|macro
.ds C0 "(\fB\*(cXe\fR)\ \&
.so me.tni
.TH execute-kbd-macro 2
.XI execute-kbd-macro \- "\*(C0Execute a keyboard macro"
.SH NAME
execute-kbd-macro \- Execute a keyboard macro
.Me $a
.SH SYNOPSIS
.na
.I n
\fBexecute-kbd-macro\fR \*(C0
.ad
.SH DESCRIPTION
.B execute-kbd-macro
executes a keyboard  macro. The entire  sequence  of recorded  key-strokes  is
repeated  starting at the current  point. The result is exactly as if you were
retyping the sequence all over again. A numeric argument \fIn\fR prefixing the
.B execute-kbd-macro
command repeats the stored key-strokes \fIn\fR times.
.PP
Keyboard macros are recored with
.Ht start-kbd-macro 2 ;
recording is terminated with
.Ht end-kbd-macro 2 .
.SH "SEE ALSO"
.na
.Ht end-kbd-macro 2 ,
.Ht kbd-macro-query 2 ,
.Ht name-kbd-macro 2 ,
.Ht start-kbd-macro 2 .
.ad
.rm C0
.FH
