.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd162.2,v 1.4 2009/08/29 17:13:25 jon Exp $
.Im MicroEmacs command|window|macrodevelop
.ds C0 "(\fB\*(cX5\ 0\fR)\ \&
.so me.tni
.TH delete-frame 2
.XI delete-frame - "\*(C0Delete the current frame"
.SH NAME
delete-frame \- Delete the current frame
.Me $a
.SH SYNOPSIS
.na
.I n
.B delete-frame
\*(C0
.ad
.SH DESCRIPTION
\fBdelete-frame\fR  deletes the current  frame and the next is  displayed.  If
there is no next frame then the command fails.
.SH "SEE ALSO"
.na
.Ht create-frame 2 ,
.Ht next-frame 2 .
.Ht $frame-id 5 .
.ad
.rm C0
.FH
