.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd104.2,v 2.7 2009/08/29 17:13:25 jon Exp $
.Im MicroEmacs command|insert
.ds C0 "(\fB\*cq\fR)\ \&
.so me.tni
.TH quote-char 2
.XI quote-char - "\*(C0Insert literal character"
.SH NAME
quote-char \- Insert literal character
.Me $a
.SH SYNOPSIS
.na
.I n
.B quote-char
"\fIkey\fR" \*(C0
.ad
.SH DESCRIPTION
.B quote-char
inserts the next typed  character  \fIn\fR  times,  default is 1, ignoring the
fact that it may be a command  character.  \fBquote-char\fR  obeys the current
buffer setting of
.Ht over 2m
mode.
.SH "SEE ALSO"
.na
.Ht insert-string 2 ,
.Ht insert-symbol 3 .
.ad
.rm C0
.FH
