.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Thu Jul 16 23:13:14 1998
.\"
.Id $Id: m2cmd129.2,v 2.6 2002-01-11 21:58:42 jon Exp $
.Im MicroEmacs command|print|hilight
.so me.tni
.TH print-color 2
.XI print-color - "Create a new printer color"
.XI print-scheme - "Create a new printer color and font scheme"
.SH NAME
.br
.Me "|print-color"
print-color \- Create a new printer color
.br
.Me "|print-scheme"
print-scheme \- Create a new printer color and font scheme
.Me $a
.SH SYNOPSIS
.na
.I n
.B print-color
"\fIcol-no\fR"
"\fIred\fR"
"\fIgreen\fR"
"\fIblue\fR"
.br
.I n
.B print-scheme
"\fIschemeNum\fR"
"\fIfore\fR"
"\fIback\fR"
"\fIfont-mask\fR"
.ad
.SH DESCRIPTION
.B print-color
and
.B print-scheme
are similar to
.Ht add-color 2
and
.Ht add-color-scheme 2
except they configure \*(mS's printer scheme.
.PP
\fBprint-color\fR  creates a new printer color and inserts it into the printer
color  table,  where  \fIred\fR,  \fIgreen\fR  and  \fIblue\fR  are the  color
components  and  \fIcol-no\fR  is the printer  color index. The printer  color
table  contains  256  entries  indexed  by  \fIcol-no\fR  in the range  0-255.
\fBprint-color\fR may also be used to modify an existing \fIcol-no\fR index by
re-assignment,  the existing  color  definition is  over-written  with the new
color definition.
.PP
An argument \fIn\fR of 0 to \fBprint-color\fR  resets the printer color table,
removing all currently defined colors.
.PP
\fBprint-scheme\fR creates a new printer scheme. A printer scheme maps the
.Ht hilight 2
buffer's  text into a print  scheme. For example key words could be printed in
\fIbold\fR  or in \fIblue\fR  etc.  \fBprint-scheme\fR  arguments  comprise an
identifying index number "\fIschemeNum\fR", two color values, "\fIfore\fR" and
"\fIback\fR"    (defined   by   \fBprint-color\fR)    and   a   font   setting
"\fIfont-mask\fR". The \fIfont-mask\fR is a bit mask where each bit is defined
as follows:
.sp
.RS
\fC0x01\fR Enable bold font.
.br
\fC0x02\fR Enable italic font.
.br
\fC0x04\fR Enable light font.
.br
\fC0x08\fR Enable reverse font.
.br
\fC0x10\fR Enable underlining.
.RE
.PP
An  argument  \fIn\fR of 0 to  \fBprint-scheme\fR  resets the  printer  scheme
table, removing all currently defined printer schemes.
.SH NOTES
Printer schemes may be created and altered using the
.Ht scheme-editor 3
dialog, the created printer scheme may then be used directly in the
.Ht print-setup 3
dialog. Therefore direct use of these commands is largely redundant.
.SH "SEE ALSO"
.na
.Ht scheme-editor 3 ,
.Ht print-setup 3 ,
.Ht print-buffer 2 ,
.Ht hilight 2 ,
.Ht $buffer-hilight 5 .
.ad
.FH
