.\" -*- nroff -*-
.Id $Id: m2cmd126.2,v 2.4 2001-12-18 16:52:52 jon Exp $
.Im MicroEmacs command|window
.ds C0 "(\fB\*(cX3\fR)\ \&
.so me.tni
.TH next-window-find-buffer 2
.XI next-window-find-buffer - "[\\fB\\fR] Split the current window and show new buffer"
.SH NAME
next-window-find-buffer \- Split the current window and show new buffer
.Me $a
.SH SYNOPSIS
.na
.B next-window-find-buffer
"\fIbuffer\fR" \*(C0
.ad
.SH DESCRIPTION
.B next-window-find-buffer
splits the current  window into two near equal  windows, and swaps the current
windows buffer to the given \fIbuffer\fR. It is effectively a
.Ht split-window-vertically 2
command followed by a
.Ht find-buffer 2 .
When there is  insufficient  space in the current window to perform the split,
then the current  window is replaced.  The  requested  \fIbuffer\fR  is always
displayed, if the buffer does not already exist it is created.
.SH "SEE ALSO"
.na
.Ht find-buffer 2 ,
.Ht split-window-vertically 2 ,
.Ht next-window-find-file 2 .
.ad
.rm C0
.FH
