.\" -*- nroff -*-
.Id $Id: m2cmd090.2,v 1.2 2000-10-21 17:09:47 jon Exp $
.Im MicroEmacs command|macrodevelop
.ds C0 "(\fB\*(rE\fR)\ \&
.so me.tni
.TH newline 2
.XI newline - "\*(C0Insert a new line"
.SH NAME
newline \- Insert a new line
.Me $a
.SH SYNOPSIS
.na
\fIn\fR \fBnewline\fR \*(C0
.ad
.SH DESCRIPTION
.B newline
inserts \fIn\fR new lines into the text, move the cursor down to the beginning
of the next  physical  line,  carrying any text that was after it with it. The
next line may automatically be indented  depending on the current buffer mode,
see
.Ht cmode 2m ,
.Ht indent 2m ,
and
.Ht wrap 2m .
.SH "SEE ALSO"
.na
.Ht cmode 2m ,
.Ht indent 2m ,
.Ht wrap 2m ,
.Ht buffer-mode 2 .
.ad
.rm C0
.FH
