.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2005 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Thu Jul 16 23:13:14 1998
.\"
.Id $Id: m2cmd114.2,v 2.6 2005-01-23 15:28:55 jon Exp $
.Im MicroEmacs command|registry
.so me.tni
.TH delete-registry 2
.XI delete-registry - "Delete a registry tree"
.SH NAME
delete-registry \- Delete a registry tree
.SH SYNOPSIS
.na
.B delete-registry
"\fIroot\fR"
.ad
.SH DESCRIPTION
.B delete-registry
deletes a registry node \fIroot\fR from the registry, any children belonging to
the node are also deleted.
.SH DIAGNOSTICS
.B delete-registry
fails if \fIroot\fR does not exist.
.SH "SEE ALSO"
.na
.Ht copy-registry 3 ,
.Ht delete-registry 2 ,
.Ht find-registry 2 ,
.Ht list-registry 2 ,
.Ht mark-registry 2 ,
.Ht read-registry 2 ,
.Ht set-registry 2 ,
.Ht &reg 4 ,
.Ht erf 8 .
.ad
.FH
