.\" -*- nroff -*-
.Id $Id: m2cmd059.2,v 1.2 2000-10-21 17:09:41 jon Exp $
.Im MicroEmacs command|region
.ds C0 "(\fB\*(cXa\fR)\ \&
.so me.tni
.TH goto-alpha-mark 2
.XI goto-alpha-mark \- "\*(C0Move the cursor to a alpha marked location"
.SH NAME
goto-alpha-mark \- Move the cursor to a alpha marked location
.Me $a
.SH SYNOPSIS
.na
.B goto-alpha-mark
"\fI?\fR" \*(C0
.ad
.SH DESCRIPTION
.B goto-alpha-mark
prompts user for an alpha character and sets the cursor position to the preset
location.  Alpha marks are  specified on a per buffer  basis, thus the current
buffer is not  changed,  merely the current  location in the buffer. The alpha
mark must already be defined using
.Ht set-alpha-mark 2 .
This  functionality is useful for rapidly returning back to locations in large
files.
.SH "SEE ALSO"
.na
.Ht set-alpha-mark 2 .
.ad
.rm C0
.FH
