.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd159.2,v 2.8 2009-08-29 17:13:25 jon Exp $
.Im MicroEmacs command|delete|region|insert
.ds C0 "(\fB\*e\*cw\fR)\ \&
.ds C1 "(\fB\*e\*cy\fR)\ \&
.so me.tni
.TH kill-rectangle 2
.XI kill-rectangle - "\*(C0Delete a column of text"
.XI yank-rectangle - "\*(C1Insert a column of text"
.SH NAME
.Me "|kill-rectangle"
kill-rectangle \- Delete a column of text
.br
.Me "|yank-rectangle"
yank-rectangle \- Insert a column of text
.Me $a
.SH SYNOPSIS
.na
\fBkill-rectangle\fR \*(C0
.br
.I n
\fByank-rectangle\fR \*(C1
.ad
.SH DESCRIPTION
.B kill-rectangle
deletes a rectangle (or column) of text defined between the cursor and the
.Hl set-mark set-mark 2
position.  The text  between the mark column and the cursor  column is removed
from every line between the mark line and the cursor line inclusive and copied
to the kill buffer. The delete text may then be extracted from the kill buffer
using
.Ht yank 2 ,
\fByank-rectangle\fR or
.Ht yank-rectangle-overwrite 3 .
.PP
The mark position may be ahead or behind the current  cursor  position. If the
rectangle column boundary divides a tab character which spans multiple columns,
the tab character is replaced with the equivalent  number of spaces. Similarly
if the boundary  divides an  unprintable  character  which is displayed  using
multiple  characters  (e.g.  '\fC^A\fR'  for  character  0x01) then spaces are
inserted before the character to move it to the right of the boundary.
.PP
.B yank-rectangle
inserts  the  current  kill buffer  (which may or may not have been  generated
using  \fBkill-rectangle\fR) into the current buffer in a column fashion. That
is to say that the first line of text in the kill buffer is inserted  into the
current line of text in the current buffer from the current cursor column, the
cursor  is then  moved the the next line and  placed at the same  column.  The
process is then repeated for the second line of text in the kill buffer etc.
.SH "SEE ALSO"
.na
.Ht copy-rectangle 3 ,
.Ht copy-region 2 ,
.Ht kill-region 2 ,
.Ht reyank 2 ,
.Ht set-mark 2 ,
.Ht string-rectangle 3 ,
.Ht undo 2 ,
.Ht yank 2 ,
.Ht yank-rectangle-overwrite 3 .
.ad
.rm C0
.rm C1
.FH
