.\" -*- nroff -*-
.Id $Id: m2cmd076.2,v 1.1.1.1 2000-07-25 22:03:55 jon Exp $
.Im MicroEmacs command|macrodevelop
.so me.tni
.TH insert-string 2
.XI insert-string \- "Insert character string into current buffer"
.SH NAME
insert-string \- Insert character string into current buffer
.Me $a
.SH SYNOPSIS
.na
.I n
.B insert-string
"\fIstring\fR"
.ad
.SH DESCRIPTION
.B insert-string
inserts a string  \fIn\fR  times into the  current  buffer,  moving the cursor
position.
.PP
.B insert-string
allows  text to be  built in a buffer  without  reading  it from a file.  Some
special escape characters are interpreted in the \fIstring\fR, as follows:
.IP
.nf
.na
\fC\\n\fR \- Enters a new line
\fC\\t\fR \- A tab character
\fC\\b\fR \- Backspace
\fC\\f\fR \- Form-feed
\fC\\\\\fR \- Literal backslash character '\fC\\\fR'
\fC\\xXX\fR \- Hexadecimal value of character \s-1ASCII\s0 value
.ad
.fi
.SH "SEE ALSO"
.na
.Ht insert-file 2 ,
.Ht insert-newline 2 ,
.Ht insert-space 2 ,
.Ht insert-tab 2 ,
.Ht newline 2 .
.ad
.FH
