.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd043.2,v 2.7 2009/08/29 17:13:09 jon Exp $
.Im MicroEmacs command|region
.ds C0 "(\fB\*(cX\*cx\fR)\ \&
.so me.tni
.TH exchange-point-and-mark 2
.XI exchange-point-and-mark - "\*(C0Exchange the cursor and marked position"
.SH NAME
exchange-point-and-mark \- Exchange the cursor and marked position
.Me $a
.SH SYNOPSIS
.na
.B exchange-point-and-mark
(\fB\*(cX\*cx\fR)
.ad
.SH DESCRIPTION
.B exchange-point-and-mark
moves  the cursor to  the current marked  position
(see
.Ht set-mark 2 )
in the current window and moves the mark to where the cursor was. This is very
useful in finding  where a mark was, or in returning to a position  previously
marked.
.PP
The current buffer mark line and column position may be obtained from within a
macro using the variables
.Ht $window-mark-line 5 
and 
.Ht $window-mark-col 5 . 
.SH "SEE ALSO"
.na
.Ht set-mark 2 ,
.Ht copy-region 2 ,
.Ht $window-mark-col 5 , 
.Ht $window-mark-line 5 .
.ad
.rm C0
.FH
