.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd053.2,v 2.5 2002-01-11 21:58:42 jon Exp $
.Im MicroEmacs command|shell
.ds C0 "(\fB\*(cX#\fR)\ \&
.so me.tni
.TH filter-buffer 2
.XI filter-buffer \- "\*(C0Filter the current buffer through an O/S command"
.SH NAME
filter-buffer \- Filter the current buffer through an O/S command
.Me $a
.SH SYNOPSIS
.na
\fBfilter-buffer\fR \*(C0
.ad
.SH DESCRIPTION
.B filter-buffer
executes  one  operating  system  command,  using the  contents of the current
buffer as input,  sending the results back to the same buffer,  replacing  the
original text.
.PP
This would typically be used in conjunction with
.Hr sort 1 ,
.Hr awk 1 
or
.Hr sed 1
to translate the contents of the buffer.
.SH "SEE ALSO"
.na
.Ht pipe-shell-command 2 .
.ad
.rm C0
.FH
