.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2mod015.2,v 2.8 2009/08/29 17:13:40 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH usr 2m
.XI usr - "User buffer modes"
.Me "!32musr1..usr8"
.SH NAME
usr1 \- usr8 \- User buffer modes
.SH SYNOPSIS
.B "usr1-usr8 Mode"
.sp
\fB1\fR\-\fB8\fR \- mode line letters.
.SH DESCRIPTION
.B usr1
through
.B usr8
modes have no  predefined  purpose,  they are present to provide the user with
the ability to store some buffer state. All of these modes are off by default.
For  example,  the user may wish to have two  commands  bound to the same key,
with another command to toggle which one is currently active.
.SH NOTES
The  toolbar  'Buffer File Info' tool uses \fBusr8\fR mode to track the status
of the buffer, when using this tool the mode should  not be used.
.SH "SEE ALSO"
.na
.Hl "Operating Modes" Modes - ,
.Ht buffer-mode 2 ,
.Ht global-mode 2 .
.ad
.FH
