.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2mod026.2,v 2.7 2009/08/29 17:13:40 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH del 2m
.XI del - "Flag buffer to be deleted"
.SH NAME
del \- Flag buffer to be deleted
.SH SYNOPSIS
.B "del Mode"
.sp
\fBd\fR \- mode line letter.
.SH DESCRIPTION
This mode cannot be set  globally and is used to flag that the buffer is to be
deleted. The state of the mode is displayed in the output of
.Ht list-buffers 2 ,
if the first  column is a 'D' the mode is set,  otherwise  it is not. Only the
execute command in
.Ht list-buffers 2
(bound to 'x') uses this flag to actually delete the buffer.
.SH "SEE ALSO"
.na
.Hl "Operating Modes" Modes - ,
.Ht list-buffers 2 ,
.Ht save 2m .
.ad
.FH
