.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2mod012.2,v 2.8 2009/08/29 17:13:40 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH tab 2m
.XI tab - "Tabulation mode"
.SH NAME
tab \- Tabulation mode
.SH SYNOPSIS
.B "tab Mode"
.sp
\fBT\fR \- mode line letter.
.SH DESCRIPTION
.B tab
mode,  when  enabled,  simulates  all  tab  stops  with  spaces.  This  allows
\'\fIvariable\fR'  tab sizes and fixes  indentation.  If \fBtab\fR mode is not
enabled  literal  tab  characters  are  inserted,  their  displayed  width  is
controlled on a buffer basis with the variable
.Ht $buffer-tab-width 5 .
.SH "SEE ALSO"
.na
.Hl "Operating Modes" Modes - ,
.Ht buffer-mode 2 ,
.Ht global-mode 2 .
.Ht $buffer-tab-width 5 ,
.Ht $tab-width 5 ,
.Ht tabs-to-spaces 3 .
.ad
.FH
