.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2004 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2mod028.2,v 2.6 2004-01-05 00:19:24 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH dir 2m
.XI dir - "Buffer is a directory listing"
.SH NAME
dir \- Buffer is a directory listing
.SH SYNOPSIS
.B "dir Mode"
.sp
\fBD\fR \- mode line letter.
.SH DESCRIPTION
This  mode  can  not be set  and is used to  indicate  that  the  buffer  is a
directory listing, created by the
.Ht find-file 2
command when the file name given is a directory.
.SH "SEE ALSO"
.na
.Hl "Operating Modes" Modes - ,
.Ht find-file 2 .
.ad
.FH
