.\" -*- nroff -*-
.Id $Id: m2mod028.2,v 1.2 2000-10-21 17:10:10 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH dir 2m
.XI dir - "Buffer is a directory listing"
.SH NAME
dir \- Buffer is a directory listing
.SH SYNOPSIS
.B "dir Mode"
.sp
\fBD\fR \- mode line letter.
.SH DESCRIPTION
This  mode  can  not be set  and is used to  indicate  that  the  buffer  is a
directory listing, created by the
.Ht find-file 2
command when the file name given is a directory.
.SH "SEE ALSO"
.na
.Ht find-file 2 .
.ad
.FH
