.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2mod025.2,v 2.9 2009-08-29 17:13:40 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH narrow 2m
.XI narrow - "Buffer contains a narrow"
.SH NAME
narrow \- Buffer contains a narrow
.SH SYNOPSIS
.B "narrow Mode"
.sp
\fBN\fR \- mode line letter.
.SH DESCRIPTION
This  mode  can  not  be set  and is  used  to  indicate  whether  the  buffer
contains a narrow, created by the
.Ht narrow-buffer 2
command. The the  location of any narrow  region  lines  contained  within the
buffer may be determined with 
.Ht $line-flags 5 .
.SH "SEE ALSO"
.na
.Hl "Operating Modes" Modes - ,
.Ht $line-flags 5 ,
.Ht narrow-buffer 2 ,
.Ht narrow-search-backward 3 ,
.Ht narrow-search-forward 3 .
.ad
.FH
