.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2mod011.2,v 2.8 2009/10/03 16:35:40 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH cr 2m
.XI cr - "File's carriage return (CR) style"
.SH NAME
cr \- File's carriage return (CR) style
.SH SYNOPSIS
.B "crlf Mode"
.sp
\fBc\fR \- mode line letter.
.SH DESCRIPTION
When  enabled  \fBcr\fR  indicates  that a carriage  return  should be written
out at the end of the line. Typically enabled independently for different line
ending styles used in \s-1DOS\s0  and  \s-1UNIX\s0.  When 1 then  \fB\\r\fR is
included in the line ending; when 0 then \fB\\r\fR is not included in the line
ending.
.SH NOTES
This mode only effects the style in which the buffer is written if
.Ht auto 2m
mode is enabled. \fBcr\fR mode is used in conjunction with 
.Ht lf 2m 
to control the line feed.
.SH "SEE ALSO"
.na
.Hl "Operating Modes" Modes - ,
.Ht auto 2m ,
.Ht lf 2m ,
.Ht ctrlz 2m ,
.Ht save-buffer 2 ,
.Ht find-file 2 ,
.Ht $buffer-fmod 5 .
.ad
.FH
