.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sun Aug 23 15:42:05 1998
.\"
.Id $Id: m2nar002.2,v 2.7 2009/08/29 17:13:40 jon Exp $
.Im MicroEmacs
.so me.tni
.TH CompanyProfiles 2
.XI CompanyProfiles - "Defining a company profile"
.SH "COMPANY PROFILES"
This section  describes  how a company  profile  should be  incorporated  into
\*(mE. A company  profile  defines a set of  extensions  to  MicroEmacs  which
encapsulate  settings  which are used on a company  wide  basis.  This type of
configuration is typically used with a networked  (shared)  installation.  The
company profile would typically include:-
.BS
Name of the company.
.BU
Standard header files including company copyright statements.
.BU
Standard file layouts
.BU
Company defined language extensions.
.BE 0
.SS "Location Of The Company Information"
It is  suggested  that all of the  company  extensions  applied  to \*(mE  are
performed  in a separate  directory  location  which  shadows  the  MicroEmacs
standard macro file  directory.  This enables the original files to be sourced
if a user does not want to include the company  files. This method also allows
MicroEmacs to be updated in the future,  whilst  retaining the company  files.
.PP
The company  files are  generally  placed in the  \fCcompany\fR  sub-directory
described in the installation notes.
.SS "Content Of The Company Information"
.BP "Company macro file"
The   company   file  is   typically   called  by  the   company   name  (i.e.
\fCjasspa.emf\fR)  create a new company file. The file  includes  your company
name and hook  functions for any new file types that have been defined for the
company, an example  company file for \fBJasspa\fR might be defined as:-
.RS
.Me $emf-scheme
.CS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  Author        : Jasspa
;  Created       : Thu Jul 24 09:44:49 1997
;  Last Modified : <220105.2244>
;
;  Description     Extensions for Jasspa
;
;  Notes
;
;  History
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Define the name of the company.
set-variable %company-name "Jasspa"
; Add Jasspa specific file hooks
; Make-up foo file hook
add-file-hook ".foo"    fhook-foo
1 add-file-hook "-!-[ \\t]*foobar.*-!-" fhook-foo ; -!- foobar -!-
; Override the make with localised build command
set-variable %compile-com "build"
.CE
.Me $ehf-scheme
The file contains company specific file hooks and the name of the company.
.RE
.BP "Other Company Files"
Files defined on behalf of the company are included in the company  directory.
These would include:-
.RS
.BS
Template header files
.Ht etf 8 .
.BU
Hook  file  definitions  (\fBhk\fR\fIXXX\fR\fB.emf\fR)  for  company  specific
files, see
.Ht add-file-hook 2 .
.BU
Extensions to the standard hook definitions  (\fBmy\fR\fIXXX\fR\fB.emf\fR) for
company specific language extensions to the standard hook files. See
.Hl "File Hooks" fileHooks 2
and
.Hl "File Language Templates" languageTemplates 2 .
.BE 0
.RE
.SH "SEE ALSO"
.na
.Ht $MEINSTALLPATH 5 ,
.Ht $MENAME 5 ,
.Ht $MEPATH 5 ,
.Hl "File Hooks" fileHooks 2 ,
.Hl "File Language Templates" languageTemplates 2 ,
.Hl "Installation" Installation 1 ,
.Ht user-setup 3 ,
.Hl "User Profiles" userProfiles 2 .
.ad
.FH
