.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sun Aug 23 15:42:05 1998
.\"
.Id $Id: m2nar003.2,v 2.11 2009/08/29 17:13:40 jon Exp $
.Im MicroEmacs
.so me.tni
.TH "User Profiles" 2
.XI UserProfiles - "Defining a user profile"
.SH "USER PROFILES"
This section describes how a user profile should be incorporated into \*(mE. A
user profile  defines a set of  extensions  to MicroEmacs  which  encapsulates
settings which are used by an individual user.
.PP
The user profile allows:-
.BS
Saving of the last session (history), allowing the next invocation of \*(mE to
restore your previous session. The \fB\-c\fR option to
.Ht me 1
restores a previous  sessions  buffers to the same state  prior to exiting the
editor.
.BU
Personalized spelling dictionaries.
.BU
Redefinition  of \*(mE  operation,  allowing  the editor to be  tailored to an
individual's  requirements.  Including the re-binding of keys, modification of
the screen colors. Definition of personal macros etc.
.BE 0
.SS "Identification"
In order to identify a user \*(mE uses  information in the system to determine
the name of the user, and in turn the configuration to use. On all systems the
value of the environment variable
.Ht $MENAME 5
takes priority over any other means of user  identification.  If this variable
is not  defined  then  the host  system  typically  provides  a  mechanism  to
determine  the current  user.  \s-1MS-DOS\s0  and  Microsoft  Windows  systems
present problems where a login prompt is not used.
.PP
Each of the supported platforms are now described.
.BP UNIX
The login name is determined from the \fC/etc/passwd\fR file and defines
.Ht $user-name 5 .
The environment variable
.Ht $MENAME 5
may be defined alter the default user configuration file name.
.BP DOS
\s-1MS\-DOS\s0 typically has no concept of the user name. The user name may be
defined in the \fCautoexec.bat\fR file, choose a name of 8 characters or less,
i.e. to fix the user name to \fCfred\fR then add the following line:-
.RS
.CS
SET MENAME=fred
.CE
Remember to re-boot the system  before the new command  takes effect. (see the
next step, there is another change to \fCautoexec.bat\fR).
.RE
.BP "Microsoft Windows"
Microsoft  windows  environments may, or may not, have login enabled. If login
is enabled then
.Ht $user-name 5
is set to the login user name. The login name may be overridden by setting the
environment variable
.Ht $MENAME 5 .
.SS "Shared Platforms"
Platforms  may share the same set of  configuration  files.  Consider a system
which may boot under  \s-1MS-DOS\s0,  Windows '98, NT and Linux. Provided that
the macro files are located on a file system that may be mounted by all of the
other operating systems and the
.Ht $MEUSERPATH 5
and
.Ht $MEPATH 5
are  set  appropriately  to  point  to the  users  private  \*(mS  and  system
directories,  then a  single  set of macro  files  may be  shared  across  all
platforms.
.SS "Personal MicroEmacs Directory"
The private user profile is stored in a separate directory. The directory that
\*(mS uses is typically  automatically created at start up, but may be created
manually by the user. If the  directory is to be placed in a special  location
then the
.Ht $MEUSERPATH 5
environment  variable  should be  defined  and set to point at this  directory
location.
.BP UNIX
In the \s-1UNIX\s0  environment then the local directory is typically  created
in the users home directory  obtained from the  \fC/etc/passwd\fR  file and is
called  \fC~/.jasspa\fR.  \*(mS will automatically look for this directory and
set the
.Ht $user-path 5
variable  to this  value.  The  location  may be  overridden  by  setting  the
environment variable
.Ht $MEUSERPATH 5
to reference a different directory location.
.BP DOS
For MS-DOS environments, there is typically no user directory, it is suggested
that the user  directory  is  created  in the  MicroEmacs  directory,  use the
\fC$MENAME\fR defined in the previous step i.e.
.RS
.CS
mkdir c:\\jasspa\\fred
.CE
Change or add the environment variable
.Ht $MEUSERPATH 5
in the \fBautoexec.bat\fR to include the new directory i.e.
.CS
SET MEUSERPATH=c:\\jasspa\\fred
.CE 0
.RE
.BP "Windows"
In Microsoft Windows environment using Explorer 4.0 or later then a user application data directory exists
(\fC$APPDATA\fR) and \*(mS will create a directory \fCjasspa\fR in this directory location to hold private data. If
there is no such data area then all user configuration is stored in the executable directory location (or a
sub-directory called
.Ht $user-name 5 ).
.IP
The user data area
.Ht $user-path 5
may be  modified  by  creating a new  directory  and  setting the  environment
variable
.Ht $MEUSERPATH 5
to point to this new directory location.
.SS "Creating Your Profile"
On  starting  \*(mS for the  first  time then the user is guided  through  the
configuration file setup to create any local configuration  files. Once set up
then \*(mS may be configured using the
.Ht user-setup 3
dialog:-
.CS
Tools -> User Setup
.CE 0
.SS "The User Profile"
Files created in the user directory include:-
.BS
Setup registry and previous session history
.Hl $user-name $user-name 5 .erf
(see
.Ht erf 8 ).
This stores the  \fBuser-setup\fR  settings and the context from previous edit
sessions.
.BU
Users start-up file
.Hl $user-name $user-name 5 .emf
(see
.Ht emf 8 ).
This is typically referred to as "\|\fIuser.emf\fR\|" in the documentation and
means the users  private \*(mS macro file. The user may make local  changes to
\*(mS in this file, this may include  definition of new key bindings, defining
new hook  functions etc. You should  override the standard \*(mS settings from
your start-up file rather than modifying the standard \*(mS files.
.BU
Personal spelling dictionary \fBlsdp\fR\|\fIlang\fR\|.edf (see
.Ht edf 8 ).
Multiple  spelling  dictionaries  may be created, one for each  language.  Any
words that are added to the spelling dictionary are stored in these files.
.BE
In addition to the above, if new private macro files are constructed then they
should be added to this directory (if they are not global to the company).
.SH EXAMPLE
The following are examples of some individuals start-up files:-
.Me $emf-scheme
.CS
; Jon's special settings
;
; Last Modified <190698.2226>
;
; Macro to delete the whitespace, or if an a word all of the
; word until the next word is reached.
define-macro super-delete
    set-variable #l0 0
    !while &not &sin @wc " \\t\\n"
        forward-char
        set-variable #l0 &add #l0 1
    !done
    !repeat
        !force forward-char
        !if $status
            set-variable #l0 &add #l0 1
        !endif
    !until &or &seq @wc "" &not &sin @wc " \\t\\n"
    #l0 backward-delete-char
    !return
!emacro
; Make a previous-buffer command.
define-macro previous-buffer
    &neg @# next-buffer
!emacro
; spotless; Perform a clean and remove any multi-blank lines.
define-macro spotless
    -1 clean
!emacro
; comment-adjust; Used for comments in electric-c mode (and the other
; electic modes. Moves to the comment fill position, saves having to mess
; around with comments at the end of the line.
0 define-macro comment-adjust
    ; delete all spaces up until the next character
    !while &sin @wc " \\t"
        forward-delete-char
    !done
    ; Fill the line to the current $c-margin. We use this as
    ; this is the only variable that tells us where the margin
    ; should be.
    !if &gre $window-acol 0
        backward-char
        !if &sin @wc " \\t"
	    forward-delete-char
            !jump -4
        !else
            forward-char
        !endif
    !endif
    ; Now fill to the $c-margin
    &sub $c-margin $window-acol insert-string " "
!emacro
; Macro to force buffer to compile buffer for C-x '
define-macro compile-error-buffer
    !force delete-buffer *compile*
    change-buffer-name "*compile*"
!emacro
;
; Set up the bindings.
;
global-bind-key super-delete            "C-delete"
global-bind-key beginning-of-line       "home"
global-bind-key end-of-line             "end"
global-bind-key undo                    "f4"
!if &seq %emulate "ERROR"
    global-bind-key comment-adjust      "esc tab"
    global-bind-key comment-adjust      "C-insert"
    ; Like a korn shell please.
    ml-bind-key tab "esc esc"
!endif
;
; Setup for windows and UNIX.
;
; Define my hilighting colour for Windows and UNIX.
!if &equ &band $system 0x001 0
    !if &not &seq $platform "win32"
        ; Small bold font is better for me.
        change-font "-*-clean-medium-r-*-*-*-130-*-*-*-*-*-*"
    !endif
!endif
; Change the default diff command-line for GNU diff utility all platforms
set-variable %diff-com "diff --context --minimal --ignore-space-change --report-identical-files --recursive"
set-variable %gdiff-com "diff --context --ignore-space-change -w"
; Setup for cygwin
!if &seq $platform "win32"
    set-variable %cygwin-path "c:/cygwin"
    set-variable %cygwin-hilight 1
!endif
; Set up the ftp flags. The letters have the following meaning:
; c   - Create a console (*ftp-console* for ftp, *http-console* for http)
; s   - Show the console
; p   - Show download progress ('#' every 2Kb downloaded)
set-variable %ftp-flags "csp"
; Info files
;To hilight the .info and also the dir file
add-file-hook ".info dir"                                   fhook-info   ; Info-files
;To hilight all info files without the extension .info
;but starting with the text "This is info file..
-2 add-file-hook "This is Info file"                        fhook-info

; Finished
ml-write "Configured to Jon's requirements"
.CE 0
.Me $ehf-scheme
.SH "SEE ALSO"
.na
.Ht user-setup 3 ,
.Ht $search-path 5 ,
.Ht $user-name 5 ,
.Ht $user-path 5 ,
.Ht $MEINSTALLPATH 5 ,
.Ht $MENAME 5 ,
.Ht $MEPATH 5 ,
.Ht $MEUSERPATH 5 ,
.Hl "Company Profiles" companyProfiles 2 ,
.Hl "File Hooks" fileHooks 2 ,
.Hl "File Language Templates" languageTemplates 2 ,
.Hl "Installation" Installation 1 .
.ad
.FH
