.\"*-*- nroff -*-*************************************************************
.\"
.\"			Copyright 1999 Samsung (SERI) Ltd.
.\"			      All Rights Reserved
.\"
.\"
.\"  System        :
.\"  Module        :
.\"  Object Name   : m3fcl002.3
.\"  Created By    : Jon Green
.\"  Created       : Mon Jul 5 21:40:07 1999
.\"  Last Modified : <000719.1013>
.\"
.\"  Description
.\"
.\"  Notes
.\"
.\"  History
.\"
.\"***************************************************************************
.\"
.\"  Copyright (c) 1999 Samsung (SERI) Ltd.
.\"
.\"  All Rights Reserved.
.\"
.\"  This  document  may not, in  whole  or in part, be  copied,  photocopied,
.\"  reproduced,  translated, or reduced to any  electronic  medium or machine
.\"  readable form without prior written consent from Samsung (SERI) Ltd.
.\"
.\"***************************************************************************
.\"
.Id $Id: m3fcl002.3,v 2.1 2001-05-14 19:54:08 jon Exp $
.Im MicroEmacs filter
.so me.tni
.TH dos2unix 3f
.XI dos2unix - "Convert DOS format files to UNIX format files"
.SH NAME
dos2unix \-  Convert DOS format files to UNIX format files
.Me $a
.SH SYNOPSIS
.na
\fBme\fR "@dos2unix" \fI<files>\fR
.ad
.SH DESCRIPTION
The start-up file \fCdos2unix.emf\fR may be invoked from the command line as a
filter to convert  all files in  \s-1MS-DOS\s0  (or  Windows)  format into the
correct \s-1UNIX\s0 format.
.PP
Each file  specified on the command line is  interrogated  and the line ending
modified to \s-1UNIX\s0.
.SH "SEE ALSO"
.na
.Ht start-up 3 ,
.Ht auto 2m ,
.Ht crlf 2m ,
.Ht ctrlz 2m .
.ad
.FH
