.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Mon Jul 5 21:40:07 1999
.\"
.Id $Id: m3fcl005.3,v 2.6 2009/08/29 17:13:41 jon Exp $
.Im MicroEmacs filter
.so me.tni
.TH ehftools 3f
.XI ehftools - "Generate a \*(mS help file"
.SH NAME
ehftools \- Generate a \*(mS help file
.Me $a
.SH SYNOPSIS
.na
\fBme\fR "@ehftools" *.htm
.ad
.SH DESCRIPTION
The start-up file  \fCehftools.emf\fR  may be invoked from the command line to
generate  a \*(mS  help  file  from a set of HTML  files  (with the  extension
\fC.htm\fR).
.PP
The \*(mS  documentation  suite of tools has not been  officially  released as
part of the  distribution.  For reference, the sequence of operations that are
performed from the command line or shell script are:-
.CS
make meehf.hts
hts2html -l .htm meehf.hts
mv me.htm me/1.htm
cd me
me "@ehftools" *.htm
.CE 0
.SH NOTES
The \fInroff\fR to HTML generator leaves the special markers 
.C "<!-- XI: %s -->"
in the generated HTML code which contain the hypertext link information.
.SH "SEE ALSO"
.na
.Ht start-up 3 ,
.Ht ehf 8 .
.ad
.FH
