.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Wed Jan 20 21:57:53 1999
.\"
.Id $Id: m3mac036.3,v 2.9 2009-08-29 17:13:59 jon Exp $
.Im MicroEmacs command|registry|macrodevelop
.so me.tni
.TH copy-registry 3
.XI copy-registry - "Recursive copy of registry subtree"
.SH NAME
copy-registry \- Recursive copy of registry subtree
.SH SYNOPSIS
.na
.B copy-registry
"\fIfrom\fR"
"\fIto\fR"
.ad
.SH DESCRIPTION
.B copy-registry
is a macro  language  construct  only  that  performs  a  recursive  copy of a
registry  subtree,  copying all child nodes of \fIfrom\fR and  recreating  the
subtree at \fIto\fR,  where  \fIfrom\fR and \fIto\fR  defines the paths to the
registry tree.
.SH NOTES 
The
.B copy-registry
command is not  publically  available  from the command  line, but may be used
within macros to perform the copy.
.PP
This command is implemented as a recursive macro in \fCutils.emf\fR.
.SH "SEE ALSO"
.na
.Ht delete-registry 2 ,
.Ht find-registry 2 ,
.Ht list-registry 2 ,
.Ht mark-registry 2 ,
.Ht read-registry 2 ,
.Ht save-session 3 ,
.Ht set-registry 2 ,
.Ht &reg 4 ,
.Ht erf 8 .
.ad
.FH
