.\" -*- nroff -*-
.Id $Id: m3mac038.3,v 1.1.1.1 2000-07-25 22:04:01 jon Exp $
.Im MicroEmacs command
.so me.tni
.TH which 3
.XI which - "Program finder"
.XI .which.result 5 "Program path"
.SH NAME
.Me "|which"
which \- Program finder
.br
.Me "|.which.result"
\&.which.result \- Program path
.Me $a
.SH SYNOPSIS
.na
\fBwhich\fR
"\fIprogname\fR"
.br
\fB.which.result\fR "\fIstring\fR"
.ad
.SH DESCRIPTION
.B which
searches for the given program "\fIprogname\fR" on the system path (set by the
environment  variable  \fB$PATH\fR).  If found the  location is printed on the
message line, otherwise an error message is printed and the command fails.
.PP
The  variable  \fB.which.result\fR  is set to the last  found  program  or the
string "\fCERROR\fR" if the program was not found.
.SH NOTES
.B which
is a macro defined in \fCtools.emf\fR, it used the &which macro directive.
.SH "SEE ALSO"
.na
.Ht &which 4 .
.ad
.FH
