.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m3mac041.3,v 2.6 2009/08/29 17:13:59 jon Exp $
.Im MicroEmacs command
.so me.tni
.TH change-buffer-charset 3
.XI change-buffer-charset - "Convert buffer between two character sets"
.SH NAME
.Me "|change-buffer-charset"
change-buffer-charset \- Convert buffer; between two character sets
.Me $a
.SH SYNOPSIS
.na
\fBchange-buffer-charset\fR
.ad
.SH DESCRIPTION
\fBchange-buffer-charset\fR opens a dialog allowing the user to select a \fBFrom\fR and \fBTo\fR character set. If the
\fIConvert\fR button is selected the current buffer is converted to the destination character set. The command assumes
that the current buffer is written in the \fBFrom\fR character set, no attempt is made to verify this.
.PP
The command also provides the ability to convert to and from UTF-8. \*(mS cannot directly support Unicode, UTF-8 or 
and multi-byte code pages, for various reasons (insert FAQ ref here) \*(mS only supports a single byte code page 
restricting the user to working with 255 characters at any one time. However, \fBchange-buffer-charset\fR does provide 
the user with the ability to load a UTF-8 file, losslessly convert the loaded file to the current code-page, edit the 
file and then convert it back to UTF-8 before saving.
.PP
The lossless conversion makes use of 2 special prefix characters, \fB0x01\fR and \fB0x02\fR, followed by 3 or 5
hexadecimal digits respectively. It is important to understand that these 4 or 6 character strings are just that to
the rest of the system, as a result operations like
.Ht kill-rectangle 2
could split the character strings and invalidate them in any later conversion process. This is not an ideal solution
but better than losing the characters entirely. The prefix characters are rendered as \fC[u]\fR and \fC[U]\fR if
extended character rendering is enabled, see bit \fB0x10000\fR of
.Ht $system 5
for more information.
.PP
\fBchange-buffer-charset\fR also allows unsupported characters to be changed to the unsupported character (\fB0x07\fR) 
or the characters can be removed.
.PP
The current character set is configured using the
.Ht user-setup 3
dialog (see
.Hl "Display Font Set" user-setup 3 ).
This in turn uses the command
.Ht set-char-mask 2
to create the low level character conversion tables.
.SH NOTES
\fBchange-buffer-charset\fR is a macro defined in \fCcharsutl.emf\fR.
.SH "SEE ALSO"
.na
.Ht user-setup 3 ,
.Ht set-char-mask 2 ,
.Ht &uni 4 ,
.Hl "Locale Support" localeSupport 2 .
.ad
.FH
