.\" -*- nroff -*-
.\" Copyright (C) 1998-2009 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.Id $Id: m3mac103.3,v 2.2 2025/07/23 00:10:58 jon Exp $
.Im MicroEmacs command|transposition
.so me.tni
.TH transpose-region-line 3
.XI transpose-region-line - "Exchange (swap) region with adjacent line"
.SH NAME
transpose-region-line \- Exchange (swap) region with adjacent line
.Me $a
.SH SYNOPSIS
.na
.I n
.B transpose-region-line
.ad
.SH DESCRIPTION
.B transpose-region-line
swaps the current region with the next line and moves the cursor with the region, effectively  retaining the same text  
position. Repeating  this \fIn\fR times moves the current region \fIn\fR lines down, if \fIn\fR is negative the region 
is moved up 0-\fIn\fR lines.
.PP
If no region is currently active the command moves the current line instead, defaulting to the same behaviour as
.Ht transpose-lines 2 .
.SH NOTES
\fBtranspose-region-line\fR is a macro defined in \fCformat.emf\fR.
.SH "SEE ALSO"
.na
.Ht transpose-lines 2 .
.ad
.FH
