.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 2000-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Tue Jan 25 23:22:52 2000
.\"
.Id $Id: m3mac051.3,v 2.7 2009-08-29 17:13:59 jon Exp $
.Im MicroEmacs command
.so me.tni
.TH display-whitespaces 3
.XI display-whitespaces - "Toggle the displaying of white characters"
.XI display-white-chars - "Toggle the displaying of white characters"
.SH NAME
display-whitespaces \- Toggle the displaying of white characters
.Me $a
.SH SYNOPSIS
.na
.B display-whitespaces
.ad
.SH DESCRIPTION
.B display-whitespaces
toggles the  displaying  of white  characters  in the main display. By default
white  characters,  space tab and new-lines, are  represented  with  invisible
characters  such as one or more '\fC \fR's for spaces and tabs and text moving
to the next  line for  new-lines.  The user can make  this  characters  become
\&'visible'  using this  function.
.PP
When this function is first  called it toggle  enables the displaying of these
characters, other  characters  are drawn in their  place to make them visible.
A subsequent call will disable the displaying of them.
.SH NOTES
\fBdisplay-whitespaces\fR is a macro implemented in \fCmisc.emf\fR and uses bit
\fC0x80000\fR of the
.Ht $system 5
variable.
.PP
The  displaying  of white  characters  can be enabled or  disabled at start-up
using
.Ht user-setup 3 .
.PP
This  feature  may be more  confusing  on some  terminals  due to the  lack of
characters  available for displaying the white characters. The characters used
when displaying white characters are defined in the variable
.Ht $window-chars 5 .
.PP
The macro  \fBdisplay-white-chars\fR  was renamed to \fBdisplay-whitespaces\fR
in September 2006. 
.SH "SEE ALSO"
.na
.Ht $system 5 ,
.Ht user-setup 3 ,
.Ht $window-chars 5 .
.ad
.FH
