.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Mon Jul 5 18:16:21 1999
.\"
.Id $Id: m3mac058.3,v 2.4 2002-01-11 21:58:42 jon Exp $
.Im MicroEmacs shell|search
.so me.tni
.TH occur 3
.XI occur - "Regular expression search for occurrences"
.SH NAME
.Me $a
.SH SYNOPSIS
.na
.B occur
.ad
.SH DESCRIPTION
\fB\&occur\fR\&  performs a regular  expression search for a string in the current
buffer; generating a list of every occurrence of the regular  expression in the
buffer. 
.PP
On invocation the user is prompted for a 
.Hl "Regular Expressions" RegularExpressions 2
the buffer is searched for the expression and the results are presented in the
\fC*item-list*\fR  window  appearing  at  the  left-hand  side  of the  window.
.PP
The user may interact with the \fC\&*item-list*\fR\& buffer using the mouse or
\fC<RETURN>\fR,   on   selecting  a  line  then  the  user  is  moved  to  the
corresponding line in the original buffer.
.SH NOTES
The  \fC*item-list*\fR  window  may be closed with the command 
.Ht item-list-close 3 
typically bound to \fCesc-F7\fR.
.PP
.B occur
is a macro defined in \fCitemlist.emf\fR.
.SH "SEE ALSO"
.na
.Ht item-list 3 ,
.Ht item-list-close 3 ,
.Ht search-forward 2 ,
.Hl "Regular Expressions" RegularExpressions 2
.ad
.FH
