.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 2000-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Tue Jan 25 23:22:52 2000
.\"
.Id $Id: m3mac052.3,v 2.7 2009/08/29 17:13:59 jon Exp $
.Im MicroEmacs command
.so me.tni
.TH check-line-length 3
.XI check-line-length - "Check the length of text lines are valid"
.SH NAME
check-line-length \- Check the length of text lines are valid
.Me $a
.SH SYNOPSIS
.na
.B check-line-length
.ad
.SH DESCRIPTION
\fBcheck-line-length\fR  checks  that the  length of each line of the  current
buffer, starting with the current line, is less than or equal to
.Ht $buffer-fill-col 5 .
The  command  aborts if a line too long is found,  leaving  the  cursor on the
offending line. If no invalid lines are found the command succeeds leaving the
cursor at the end of the buffer.
.SH NOTES
\fBcheck-line-length\fR is a macro implemented in \fCmisc.emf\fR.
.SH "SEE ALSO"
.na
.Ht $buffer-fill-col 5 .
.ad
.FH
