.\" -*- nroff -*-
.\" Copyright (C) 1998-2009 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.Id $Id: m3mac102.3,v 2.2 2026/08/04 23:12:19 jon Exp $
.Im MicroEmacs command|shell
.so me.tni
.TH keep-buffer 3
.XI keep-buffer - "Rename the current buffer"
.SH NAME
keep-buffer \- Rename the current buffer
.Me $a
.SH SYNOPSIS
.na
.B keep-buffer
.ad
.SH DESCRIPTION
.B keep-buffer
renames the current buffer by appending a number to the end of the current buffer name. This ensures that, if the command used to 
generate the buffer (such as
.Ht compile 3
and
.Ht grep 3 )
is rerun, the current buffer will not be deleted.
.PP
This command is useful when the current buffer is time consuming to generate and another compile or grep is needed 
before it has been fully processed.
.PP
It can also be used as a quick way to create multiple
.Hl ishells ishell 3 ,
by executing this macro on the first \fC*shell*\fR buffer, which will rename it to \fC*shell*1\fR, executing 
\fBishell\fR will create a new shell. 
.SH NOTES
\fBkeep-buffer\fR is a macro defined in \fCtools.emf\fR.
.SH "SEE ALSO"
.na
.Ht compile 3 ,
.Ht grep 3 ,
.Ht ishell 3 .
.ad
.FH
