.\" -*- nroff -*-
.\" Copyright (C) 1999-2009 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Mon Jul 5 18:16:21 1999
.\"
.Id $Id: m3mac058.3,v 2.5 2024/10/06 17:13:59 jon Exp $
.Im MicroEmacs shell|search
.so me.tni
.TH occur 3
.XI occur - "Regular expression search for occurrences"
.SH NAME
.Me $a
.SH SYNOPSIS
.na
.I n
.B occur
"\|\fIsearch-string\fR\|"
.ad
.SH DESCRIPTION
\fB\&occur\fR\&  performs a  search for a string in the current
buffer;  generating  a list  of  every  occurrence  found.  If the  \fIsearch-string\fR  has not  been  given  via the
command-line  and the buffer has an active  region  when the command is called, the content of the region will be used
as the search string, otherwise the string will be prompted for.
.PP
The buffer's
.Ht magic 2m
mode setting is used to determine whether the  \fIsearch-string\fR is a the regular expression or not, except with the
current region is used.
.PP
The results are presented in the \fC*item-list*\fR window, the user may interact with the \fC\&*item-list*\fR\& buffer
using  the  mouse or  \fC<RETURN>\fR,  on  selecting  a line then the user is moved to the  corresponding  line in the
original buffer.
.PP
If an argument  \fBn\fR is given then the width of the match sample  string is limited to 15 or 28 chars, with a value
of 1 or 2, on each side of the match making the output  narrower; this can be used to allow the buffer to be placed in
a side window such as a toolbar.
.SH NOTES
The  \fC*item-list*\fR  window  may be closed with the command 
.Ht item-list-close 3 
typically bound to \fCesc-F7\fR.
.PP
.B occur
is a macro defined in \fCitemlist.emf\fR.
.SH "SEE ALSO"
.na
.Ht item-list 3 ,
.Ht item-list-close 3 ,
.Ht search-forward 2 ,
.Ht magic 2m ,
.Hl "Regular Expressions" RegularExpressions 2
.ad
.FH
