.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m3mac019.3,v 2.7 2009/08/29 17:13:42 jon Exp $
.Im MicroEmacs command|macrodevelop
.so me.tni
.TH ascii-time 3
.XI ascii-time - "Return the current time as a string"
.XI .ascii-time.format 5 "Set the format of the date string"
.SH NAME
ascii-time \- Return the current time as a string
.Me $a
.SH SYNOPSIS
.na
\fBascii-time\fR
.ad
.SH DESCRIPTION
\fBascii-time\fR  returns the current time as a formatted  string in \fC#p9\fR
which is  equivalent  to  \fC#l9\fR  for the calling  macro. The format of the
resultant string is determined by the variable
.B .ascii-time.format
which is defined using the following escape characters:
.RS
.sp
.nf
.na
\fC%%\ \fR - \fC%\fR char
\fC%Y\ \fR - 4 digit year
\fC%y\ \fR - 2 digit year
\fC%B\ \fR - Full month word
\fC%b\ \fR - 3 letter month
\fC%m\ \fR - 2 digit month
\fC%#m\fR - 1 digit month
\fC%d\ \fR - 2 digit day
\fC%#d\fR - 1 digit day
\fC%A\ \fR - Fill Week day word
\fC%a\ \fR - 3 letter week day
\fC%H\ \fR - 2 digit 24 hour
\fC%M\ \fR - 2 digit minute
\fC%S\ \fR - 2 digit second
.ad
.fi
.RE
.sp
The default value of 
.B .ascii-time.format
when not defined is:
.IP
"\fC%a %b %d %H:%M:%S %Y\fR"
.LP
To change the default date layout then 
.B .ascii-time.format 
should be defined in \fIuser\fR\|\fB.emf\fR. i.e.
.Me $emf-scheme
.CS
set-variable .ascii-time.format "%H:%M:%S %Y-%m-%d"
.CE 0
.Me $ehf-scheme
.SH EXAMPLE
The  following  is  taken  from  etfinsrt.emf,  it  uses  \fBascii-time\fR  in
replacing "\fC$ASCII_TIME$\fR" with the current.
.Me $emf-scheme
.CS
0 define-macro etfinsrt
    .
    .
    ; Change the create date $ASCII_TIME$.
    beginning-of-buffer
    ; Get ASCII time in #l9
    ascii-time
    !force replace-string "\\\\$ASCII_TIME\\\\$" #l9
    .
    .
!emacro
.CE 0
.Me $ehf-scheme
.SH NOTES
\fBascii-time\fR is a macro defined in \fCutils.emf\fR.
.SH "SEE ALSO"
.na
.Ht $buffer-fhook 5 ,
.Ht etfinsrt 3 ,
.Ht &find 4 .
.ad
.FH
