.Id $Id: m3mac003.3,v 2.4 2001-12-18 16:52:53 jon Exp $
.Im MicroEmacs command|paragraph
.so me.tni
.TH paragraph-to-line 3
.XI paragraph-to-line \- "Convert a paragraph to a single line"
.SH NAME
paragraph-to-line \- Convert a paragraph to a single line
.Me $a
.SH SYNOPSIS
.na
.I n
\fBparagraph-to-line\fR
.ad
.SH DESCRIPTION
.B paragraph-to-line
is a variation of
.Ht fill-paragraph 2 .
.B paragraph-to-line
reduces each of the next \fIn\fR paragraphs of text to single lines. This  command is
typically  used to  prepare  text for  import  into a word  processor  such as
\fBMicrosoft Word\fR or \fBWord Perfect\fR. Reduction of text to a single line
allows the word processor to import the raw text file and keep the text within
paragraph  blocks. If the text is not prepared then all of the line-feeds  have
to be manually deleted.
.PP
.B paragraph-to-line
allows text based documents to be prepared in \*(mE and imported into the
word processor at the final stage for formatting and layout.
.SH NOTES
\fBparagraph-to-line\fR is a macro defined in \fCformat.emf\fR.
.SH "SEE ALSO"
.na
.Ht fill-paragraph 2 .
.ad
.FH
