.\" -*- nroff -*-
.\" Copyright (C) 1998-2009 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.Id $Id: m3mac030.3,v 2.7 2025/01/12 09:09:04 jon Exp $
.Im MicroEmacs command|file
.ds C0 "(\fB\*(cX\*ch\fR)\ \&
.so me.tni
.TH find-hfile 3
.XI find-hfile - "\*(C0Load a file using selected handler"
.XI find-bfile - "Load a file as binary data"
.XI find-cfile - "Load a crypted file"
.SH NAME
.Me "|find-hfile"
find-hfile \- Load a file using selected handler
.br
.Me "|find-bfile"
find-bfile \- Load a file as binary data
.br
.Me "|find-cfile"
find-cfile \- Load a crypted file
.Me $a
.SH SYNOPSIS
.na
.I n
.B find-hfile
"\fIh\fR" "\fIfile-name\fR" \*(C0
.br
.I n
.B find-bfile
"\fIfile-name\fR"
.br
.I n
.B find-cfile
"\fIfile-name\fR"
.ad
.SH DESCRIPTION
\fBfind-hfile\fR  first prompts the user for the read handler \fIh\fR required
to load the file into \*(mS, where \fIh\fR can be:
.IP \fBC\fR
As with  \fBc\fR  below exect that the user is prompted  for a second  handler
which is combined with crypt. Support secondary  handlers are \fBb\fR, \fBr\fR
and \fBt\fR, when used this handler must be given first.
.Ht binary 2m
mode for more information.
.IP \fBb\fR
Standard binary file handler, see 
.Ht binary 2m
mode for more information.
.IP \fBc\fR
Encrypted file handler, see 
.Ht crypt 2m
mode for more information.
.IP \fBr\fR
Reduced binary file handler, see 
.Ht rbin 2m
mode for more information.
.IP \fBt\fR
Normal text file, equivalent to standard use of
.Ht find-file 2 .
.IP \fBz\fR
Zip file handler, see 
.Ht find-zfile 3
for more information. This handler cannot currently be combined with \fBC\fR.
.PP
The macro then calls the  appropriate  underlying  command  with the  required
numerical argument to load \fIfile-name\fR correctly.
.PP
\fBfind-bfile\fR and \fBfind-cfile\fR provide a simple interface to loading files in
.Ht binary 2m
and
.Ht crypt 2m
modes respectively. The numeric argument has the same effect as with the
.Ht find-file 2
command except the respective modes are always enabled. See documentation on the modes an \fBfind-file\fR command for
more information.
.SH NOTES
\fBfind-hfile\fR, \fBfind-bfile\fR and \fBfind-cfile\fR are macros defined in file \fCtools.emf\fR.
.PP
Buffers  containing  directory  listings generated by \fBfind-file\fR  and zip
content listings created by \fBfind-zfile\fR provide a similar interface
to \fBfind-hfile\fR bound to the letter \fBh\fR. 
.PP
The command
.Ht find-file 2
is bound to key "\fC\*(cX9\fR" with a numeric argument of 3, this is equivalent to executing \fBfind-bfile\fR with no
argument.
.SH "SEE ALSO"
.na
.Ht find-file 2 ,
.Ht find-zfile 3 ,
.Ht binary 2m ,
.Ht crypt 2m ,
.Ht rbin 2m .
.ad
.rm C0
.FH
