.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Mon Aug 31 21:02:32 1998
.\"
.Id $Id: m3mac033.3,v 2.8 2009/08/29 17:13:59 jon Exp $
.Im MicroEmacs shell
.so me.tni
.TH cygwin 3
.XI cygwin - "Open a Cygwin BASH window" shell|command
.XI %cygwin-path 5 "Cygwin root directory" shell|variable
.XI %cygwin-hilight  5 "Cygwin shell hilight enable flag" shell|variable
.XI %cygwin-prompt   5 "Cygwin shell prompt" shell|variable
.SH NAME
.Me "|cygwin"
cygwin \- Open a Cygwin BASH window
.br
.Me "|%cygwin-path"
%cygwin-path \- Cygwin root directory
.br
.Me "|%cygwin-hilight"
%cygwin-hilight \- Cygwin shell hilight enable flag
.br
.Me "|%cygwin-prompt"
%cygwin-prompt \- Cygwin shell prompt
.Me $a
.SH PLATFORM
Windows '95/'98/NT/2K/XP/Vista/7/10/11 - windows ONLY
.SH SYNOPSIS
.na
\fBcygwin\fR
.sp
.B %cygwin-path
"\|\fIpath\fR\|"
.br
.B %cygwin-hilight
[\fC0\fR|\fC1\fR]
.br
.B %cygwin-prompt
"\|\fIhilightString\fR\|"
.ad
.SH DESCRIPTION
\fBcygwin\fR  creates an  interactive  BASH shell  window  within a MicroEmacs
buffer window,  providing a UNIX command line  facility  within the Microsoft
Windows environment. This is a preferable  environment to the MS-DOS shell and
is certainly far more comfortable for those familiar with UNIX.
.PP
Within the window BASH  commands may be entered and  executed, the results are
shown  in the  window.  Within  the  context  of the BASH  shell  window  then
directory naming conforms to the \fBcygwin\fR standard conventions (as opposed
to the Microsoft directory naming).
.PP
On running  \fBcygwin\fR a new buffer is created called  \fC*cygwin*\fR  which
contains the shell.  Executing  the command  again  creates a new shell window
called  \fC*cygwin1*\fR,  and so on. If a cygwin window is killed off then the
available window is used next time the command is run.
.PP
Additional  controls  are  available  within the shell  window to control  the
editors interaction with the window. The operating mode is shown as a digit on
the buffer mode line (2/3/4) which is defined in the  following  sections. The
operational mode is changed with the \fBF3\fR function key.
.IP "\fBMode 2 - Browse Mode\fR"
Locks the  window  and allows  local  editing to be  performed.  All  commands
entered  into the window are  interpreted  by the editor. Mode 2 is  typically
entered to cut and paste from the window, search for text strings etc. In mode
2, a \fB2\fR is shown on the mode line.
.IP "\fBMode 3 - Semi-immersion\fR"
The  normal  operating  mode, text typed into the window is  presented  to the
shell window. Translation of MicroEmacs commands (i.e.  beginning-of-word) are
translated  and passed to the shell. For  interactive  use this is the default
mode. In mode 3, a \fB3\fR is shown on the mode line.
.IP "\fBMode 4 - Full Immersion\fR"
All input is passed to the shell, no MicroEmacs  commands are  interpreted and
keys are passed  straight to the shell window. This mode is used where none of
the keys to be entered are to be interpreted by MicroEmacs. Note that you have
to un-toggle mode 4 before you can swap buffers as this effectively  locks the
editor into the window.
.IP \fBF5\fR
Clears  the  buffer  contents.  This  simply  erases  all  of  the  historical
information in the buffer. The operation of the shell is unaffected.
.LP
To exit the shell then end the shell session using "\fCexit\fR" or "\fCC-d\fR"
as normal and then close the buffer. A short cut "\fCC-c  C-k\fR" is available
to kill off the pipe. However, it is not recommended  that this method is used
as it effectively performs a hard kill of the buffer and attached process
.PP
.B %cygwin-path
is a user  defined  variable  that  defines  the file  system  location of the
\fIcygwin\fR directory, this is typically  \fCc:/cygwin\fR. If \fIcygwin\fR is
located at a  different  location  then the  variable  \s-1MUST\s0  be defined
within the user start up script in order for the \fBcygwin\fR command to start
the shell. With a default  installation of \fIcygwin\fR  then the settings are
typically defined as:-
.PP
.B "Current Release"
.Me $emf-scheme
.CS
set-variable %cygwin-path "c:/cygwin"
.CE
.Me $ehf-scheme
.B %cygwin-hilight
is a boolean  flag  which  controls  how the cygwin  command  shell  window is
hilighted.  This value  \s-1MUST\s0 be defined within the user start up script
prior to executing  \s-1cygwin\s0  if  hilighting is to be disabled; by default
hilighting is enabled. A value of 0 disables shell hilighting i.e.
.Me $emf-scheme
.CS
set-variable %cygwin-hilight 0
.CE
.Me $ehf-scheme
.B %cygwin-prompt
is   an   optional    variable    that   is   used   in    conjunction    with
\fB%cygwin-hilight\fR,  it  defines  the  hilighting  string  identifying  the
prompt.  This  allows the prompt to be  rendered  with a different  color. The
default prompt is \fCbash-x.yyr$\fR and may be hilighted using a definition:-
.Me $emf-scheme
.CS
set-variable %cygwin-prompt "bash-2.01$"
.CE
.Me $ehf-scheme
The user typically  overrides the prompt  definition  within the \s-1BASH\s0
startup file, a more appropriate definition of the prompt may be:-
.Me $emf-scheme
.CS
set-variable %cygwin-prompt "^[a-z]*@[^>]*>"
.CE 0
.Me $ehf-scheme
.SH NOTES
The \fBcygwin\fR command uses the
.Ht ipipe-shell-command 2
to manage the pipe between the editor and the \fBbash\fR  shell. The window is
controlled by the macro file \fChkcygwin.emf\fR which controls the interaction
with the shell.
.PP
The macro
.B cygwin
in  \fChkcygwin.emf\fR  defines the  parameter  setup to connect to the cygwin
bash  shell,  installed  in the  default  location  \fCc:/cygwin\fR.  If  your
installation  of cygwin is in a different  location  then correct the macro to
match   your   install   location,    preferably   correct   by   creating   a
\fImycygwin.emf\fR  file in your user directory simply containing a re-defined
\fBcygwin\fR macro.
.PP
If you have exported some of the cygwin  environment  variables in your
\fCautoexec.bat\fR  then  you  will  have to  figure  out for  yourself  what
variables macro \fIcygwin\fR needs to export - the current configuration is
for a vanilla install.
.PP
The \fBbash\fR shell is executed with options \fB-i\fR, for interactive  shell
and \fB-m\fR to enable job control.
.PP
As of the 2004  release  then the  \fBCygwin\fR/\fBCygnus\fR  support has been
revised in light of the changes in \fBcygwin\fR
.BS
Renamed the command from \fBcygnus\fR to \fBcygwin\fR.
.BU
Following a change in the
.Hr bash 1
command  line  operation,  which now no longer echos user input, then the user
input is processed by \*(mS. This does cause some problems with completion as
the Cygwin  environment  has a  different  name  space. The  completion  still
requires some more work, but sufficient for smaller tasks.
.BE 0
.SH "TESTED CONFIGURATIONS"
This  configuration  has only  been  tested  on a Windows  2000  installation,
whether this works on Windows  95/98/NT is unknown  while XP is very likely to
work.
.PP
We have only been running  "make"  operations in the shell and do not know how
the likes of "more", "man" or anything other terminal interaction works.
.IP "\fBTested Configurations\fR"
Windows 2K (Pentium-4) and Windows 2K (SunPCi-III)
.IP
cygwin latest version as of February 2004.
.SH BUGS
.IP  "\fBBreak Key\fR"
A break in a bash shell is \fCC-c\fR, the macros define the key \fCC-c\ C-c\fR
to perform the break. 
.\"If the shell  environment  is not  configured  then this
.\"will cause the shell to close down. Configuring bash resolves this problem.
There does not appear to be a way to prevent  this from  happening as trapping
the interrupt does not appear to be supported in Cygwin Bash i.e.  "\fCtrap\fR
\fC''\fR \fCINT\fR". 
.IP "\fBCompletion\fR"
Completion  processing  needs  to  be  improved.  The  directory  location  is
retrieved from
.Hr bash 1
on each  command  line prompt, this is used for file  completion.  There is no
command completion. Room for some improvement here.
.SH "SEE ALSO"
.na
.Ht ipipe-shell-command 2 ,
.Ht ishell 3 .
.br
Cygwin home site
.B www.cygwin.com
.ad
.FH
