.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Steven Phillips
.\"  Created       : Fri Aug 7 07:32:59 1998
.\"
.Id $Id: m3mac027.3,v 2.6 2004-01-11 01:11:18 jon Exp $
.Im MicroEmacs command|file|essential
.ds C0 "(\fB\*(fA\fR)\ \&
.so me.tni
.TH file-browser 3
.XI file-browser - "\*(C0Browse the file system"
.XI file-browser-close - "Close the file-browser"
.XI file-browser-swap-buffers - "Swap between file-browser windows"
.SH NAME
file-browser \- Browse the file system
file-browser-close \- Close the file-browser
file-browser-swap-buffers \- Swap between file-browser windows
.Me $a
.SH SYNOPSIS
.na
\fBfile-browser\fR \*(C0
.br
\fBfile-browser-close\fR
.br
\fBfile-browser-swap-buffers\fR
.ad
.SH DESCRIPTION
\fBfile-browser\fR  can be used to browse  around the file  system. When first
executed \fBfile-browser\fR creates 2 buffers, "\fC*directory*\fR"  displaying
the directory  structure and "\fC*files*\fR"  listing the files in the current
directory  with  information on each file.  \fBfile-browser\fR  displays these
buffers side by side, splitting the current window horizontally if required.
.PP
Once open the user can browse  through the system using the following  keys in
the \fC*directory*\fR buffer:
.IP \fCspace\fR
Selects the  directory  on the current  line and  up-dates  the  \fC*files*\fR
buffer  with  the  information  on this  directory.  This  can also be done by
clicking the left mouse button on the directory name. 
.IP \fCreturn\fR
Selects the directory on the current line, if open (sub-directories displayed)
then closes it or if closed it is opened. The \fC*files*\fR buffer is up-dated
with the  information on the directory.  This can also be done by clicking the
left  mouse  button on the  '\fC+\fR'  or  '\fC-\fR'  symbol  just  before the
directory name.
.IP \fCC-return\fR
As with \fCreturn\fR expect  sub-directories are recursively opened or closed,
note that this could take some time on large file  systems.  This can also be
done by clicking  the right mouse button on the '\fC+\fR' or '\fC-\fR'  symbol
just before the directory name.
.IP \fCtab\fR
Move to the \fC*files*\fR buffer.
.IP \fCdelete\fR
Closes file-browser.
.PP
The following  keys can be used in the \fC*files*\fR buffer:
.IP \fCreturn\fR
If the  current  line is a  directory,  this  because  the current  directory,
updating both the \fC*directory*\fR and \fC*files*\fR  buffers. If the line is
a file then it is opened using
.Ht find-file 2 .
This can also be done by clicking the left mouse button on the file name.
.IP \fCspace\fR
Toggles  the tag state of the file on the current  line, see \fCx\fR  command.
This can also be done by clicking  the left mouse button  anywhere  before the
file name, or for multiple files drag a region with the left mouse button.
.IP "\fCX\fR or \fCx\fR"
Executes a
.Ht shell-command 2
on all  tagged  files. The user is  prompted  for the  command  line which can
contain the following special tokens:
.RS
.nf
\fC%p  \fRFull file name, including path.
\fC%f  \fRThe file name without the path.
.fi
.RE
As the  \fBshell-command\fR  is executed in the directory  \fC%f\fR is safe to
use in a command such as "\fCdel %f\fR".
.IP "\fCD\fR or \fCd\fR"
Deletes all the tags in the buffer.
.IP \fCtab\fR
Move to the \fC*directory*\fR buffer.
.IP \fCdelete\fR
Closes file-browser.
.PP
\fBfile-browser-swap-buffers\fR   swaps  between  the   \fC*directory*\fR  and
\fC*file*\fR  windows,  making the other the current  window,  this is usually
locally bound to the \fCtab\fR key.
.PP 
\fBfile-browser-close\fR  hides both the  \fC*directory*\fR  and  \fC*file*\fR
windows,  closing  the  file-browser,  this is  usually  locally  bound to the
\fCdelete\fR key.
.SH "SEE ALSO"
.na
.Ht directory-tree 2 ,
.Ht find-file 2 ,
.Ht shell-command 2 .
.ad
.rm C0
.FH

