.\"*-*- nroff -*-*************************************************************
.\"
.\"			Copyright 1998 JASSPA.
.\"			      All Rights Reserved
.\"
.\"
.\"  System        :
.\"  Module        :
.\"  Object Name   : m3osd000.3
.\"  Created By    : Steven Phillips
.\"  Created       : Sat Aug 22 09:00:06 1998
.\"  Last Modified : <000719.1013>
.\"
.\"  Description
.\"
.\"  Notes
.\"
.\"  History
.\"
.\"***************************************************************************
.\"
.\"  Copyright (c) 1998 JASSPA.
.\"
.\"  All Rights Reserved.
.\"
.\"  This  document  may not, in  whole  or in part, be  copied,  photocopied,
.\"  reproduced,  translated, or reduced to any  electronic  medium or machine
.\"  readable form without prior written consent from JASSPA.
.\"
.\"***************************************************************************
.\"
.Id $Id: m3osd011.3,v 2.3 2001-12-18 16:52:53 jon Exp $
.Im MicroEmacs command|osd
.so me.tni
.TH buffer-help 3
.XI buffer-help - "Displays help page for current buffer"
.SH NAME
buffer-help \- Displays help page for current buffer
.Me $a
.SH SYNOPSIS
.na
.B buffer-help
.ad
.SH DESCRIPTION
\fBbuffer-help\fR  opens a dialog  giving  the user a brief help page on tools
available for the current buffer. The help page changes  depending on the type
of the current buffer.
.SH "SEE ALSO"
.na
.Ht buffer-setup 3 .
.ad
.FH
