.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m4fil013.4,v 2.11 2009/10/03 16:35:40 jon Exp $
.Im MicroEmacs macro;directive|miscellaneousOperators
.so me.tni
.TH !bell 4
.XI !bell - "Sound audio alarm"
.SH NAME
!bell \- Sound audio alarm
.SH SYNOPSIS
.na
.nf
\fB!bell\fR [\fIn\fR]
.fi
.ad
.SH DESCRIPTION
\fB!bell\fR  provides  a warning  (audible  or  visual) to alert the user of a
problem. \fB!bell\fR honors the
.Ht quiet 5
setting, as such if  \fBquiet\fR  mode is  disabled an audible  warning is given,
otherwise  a  visual  warning  is  given  to the  user  (usually  the  message
"\fI[BELL]\fR" in the bottom left hand corner of the message line).
.PP
The optional  numerical  argument  \fIn\fR  over-rides the current  setting of
\fBquite\fR,  a value of \fC0\fR  specifies  a quite bell,  \fC2\fR an audible
one, when omitted the default is \fC1\fR  honoring the setting of  \fBquite\fR
mode.
.PP
\fB!bell\fR is generally used in conjunction with
.Hl !abort !abort 4 ,
the !bell function warning the user and the !abort function to quit the macro.
.SH EXAMPLE
The  following  macro  example  checks  for  incoming  mail and is taken  from
\fCmail.emf\fR.  If any mail has  arrived  an  audible  warning  is assured by
toggling the \fBquiet\fR mode.
.Me $emf-scheme
.CS
;
; Mail checker
define-macro mail-check
    !if &seq &set %vm-mail-src &reg &spr "/history/%s/mail-src"  $platform ""
        ml-write "[Incoming mail file not setup! Execute mail-setup to configure]"
        !abort
    !endif
    600000 create-callback mail-check
    ml-write &spr "Checking for mail in %s..." %vm-mail-src
    set-variable #l0 &cond &gre &stat "s" %vm-mail-src 0 "M" "-"
    !if &not &seq &mid $mode-line 2 1 #l0
        set-variable #l1 &rig $mode-line &cond &seq &mid $mode-line 2 1 "%" 4 3
        set-variable $mode-line &cat &cat &lef $mode-line 2 #l0 #l1
        screen-update
        !if &seq #l0 "M"
            ; use an argument to !bell so it toggles it back to its original state
            !bell 0
            !bell 2
        !endif
    !endif
    0 ml-write
!emacro
.CE 0
.Me $ehf-scheme
.SH "SEE ALSO"
.na
.Ht !abort 4 ,
.Ht abort-command 2 ,
.Ht !bell 4 .
.ad
.FH
