.\" -*- nroff -*-
.Id $Id: m5var016.5,v 2.1 2001-05-14 19:54:39 jon Exp $
.Im MicroEmacs variable|scuts
.so me.tni
.TH $c-margin 5
.XI $c-margin - "C-mode; trailing comment margin"
.SH NAME
$c-margin \- C-mode; trailing comment margin
.Me $a
.SH SYNOPSIS
\fB$c-margin\fR \fIinteger\fR; Default is \fC-1\fR
.sp
\-1 <= \fIinteger\fR <= \fIn\fR
.SH DESCRIPTION
.B $c-margin
is part of the
.Ht cmode 2m
environment for C programmers.
.PP
If inserting a comment at the  end of a C line,  it is tedious typing \fIx\fR number
of spaces to the comment column (by default tab  doesn't insert a tab when
.Ht cmode 2m
is enabled,  it  reformats the  indentation  of the  line  regardless of  the cursor
position). This variable sets the indent column of these comments. So with the
default settings and the following line,
.CS
        xxxxxx ;/
.CE
when a '*' is type the line becomes
.CS
        xxxxxx ;                /*
.CE
The  indenting  of the  "\fC/*\fR"  occurs  only if  there is text on the line
before  it,  and  none  after  it. If  the  current  column  is  already  past
\fB$c-margin\fR then it is indented to the next tab stop.
.PP
A value of -1 disables this feature.
.SH "SEE ALSO"
.na
.Ht cmode 2m .
.ad
.FH
