.\" -*- nroff -*-
.Id $Id: m5var014.5,v 2.0 2001-03-08 21:30:14 jon Exp $
.Im MicroEmacs variable|scuts
.so me.tni
.TH $c-case 5
.XI $c-case - "C-mode; case indentation"
.XI $c-switch - "C-mode; switch indentation"
.SH NAME
.Me "|$c-case"
$c-case \- C-mode; case indentation
.br
.Me "|$c-switch"
$c-switch \- C-mode; switch indentation
.Me $a
.SH SYNOPSIS
\fB$c-case\fR \fIinteger\fR; Default is \fC-4\fR
.br
\fI\-n\fR <= \fIinteger\fR <= \fIn\fR
.sp
\fB$c-switch\fR \fIinteger\fR; Default is \fC0\fR
.br
\fI\-n\fR <= \fIinteger\fR <= \fIn\fR
.SH DESCRIPTION
.B $c-case
and 
.B $c-switch
are part of the
.Ht cmode 2m
environment for C programmers.
.PP 
\fB$c-switch\fR  sets the offset of a "\fCcase\fR"  entry  statement  from the
opening brace left margin position. The default value is zero. e.g.
.CS
                switch(xxxxxxxxx)
                {
                case 1:
                    xxxxxxxxxx
                    xxxxxxxxxx
                case 2:
                    xxxxxxxxxx
                }                   
.CE
Setting  the  value to 4,  increases  the  leading  space on the  "\fCcase\fR"
statement, e.g.
.CS
                switch(xxxxxxxxx)
                {
                    case 1:
                        xxxxxxxxxx
                        xxxxxxxxxx
                    case 2:
                        xxxxxxxxxx
                }                   
.CE
\fB$c-case\fR sets the offset of the lines following a "\fCcase\fR" statement,
from the  current  indent. For  example,  using the default  settings,  if the
current  indent  was 20 then a line  starting  with a  "\fCcase\fR"  would  be
indented to 16, i.e.
.CS
                    xxxxxxxxxx
                case xxxxxxxxxx
                    xxxxxxxxxx
.CE                    
This is used inside  "\fCswitch\fR" statements, the default setting give the following
lay-out:-
.CS
                switch(xxxxxxxxxx)
                {
                case 1:
                    xxxxxxxxxx
                    xxxxxxxxxx
                case 2:
.CE                    
This works in  conjunction with the 
.Ht $c-statement 5 ,
a change  to \fB$c-statement\fR will change the position of '\fC{\fR's.
.SH "SEE ALSO"
.na
.Ht cmode 2m ,
.Ht $c-statement 5 .
.ad
.FH
