.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m5var032.5,v 2.6 2009-08-29 17:14:15 jon Exp $
.Im MicroEmacs variable|buffer|modeline;variable|hilight
.so me.tni
.TH $mode-line-scheme 5
.XI $mode-line-scheme - "Mode line color scheme"
.SH NAME
$mode-line-scheme \- Mode line color scheme
.Me $a
.SH SYNOPSIS
\fB$mode-line-scheme\fR \fIschemeNum\fR; Default is \fC1\fR
.SH DESCRIPTION
Sets  the  window   mode-line  color  scheme,  defining  the  foreground  and
background colors. The \fIschemeNum\fR is defined by a previous invocation to 
.Ht add-color-scheme 2 . 
.SH "SEE ALSO"
.na
.Ht add-color-scheme 2 ,
.Ht $global-scheme 5 ,
.Ht $ml-scheme 5 ,
.Ht $scroll-bar-scheme 5 ,
.Ht $system 5 .
.ad
.FH
