.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m5var021.5,v 2.5 2002-01-11 21:58:43 jon Exp $
.Im MicroEmacs variable|paragraph
.so me.tni
.TH $fill-col 5
.XI $fill-col - "Paragraph Mode; right fill column"
.SH NAME
$fill-col \- Paragraph Mode; right fill column
.Me $a
.SH SYNOPSIS
\fB$fill-col\fR \fIcolumnNumber\fR; Default is \fC78\fR
.sp
-1 <= \fIcolumnNumber\fR <= 32767
.SH DESCRIPTION
.B $fill-col
defines the current fill column number. \fIcolumnNumber\fR defaults to 78 when
undefined. This value is used in conjunction with 
.Ht justify 2m
and
.Ht wrap 2m 
modes.
.SH "SEE ALSO"
.na
.Ht buffer-mode 2 ,
.Ht fill-paragraph 2 ,
.Ht justify 2m ,
.Ht wrap 2m .
.ad
.FH
