.\" -*- nroff -*-
.\" Copyright (C) 1998-2009 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.Id $Id: m5var066.5,v 2.7 2025/08/28 02:15:19 jon Exp $
.Im MicroEmacs variable|macrodevelop
.so me.tni
.TH $progname 5
.XI $progname - "Program file name"
.SH NAME
$progname \- Program file name
.Me $a
.SH SYNOPSIS
.B $progname
.I string
.SH DESCRIPTION
.B $progname 
contains the absolute file and path to the \*(mS binary file  currently  being
executed.  This value is typically  used by macros to spawning  another  \*(mS
sessions and to determine where \*(mS is being executed from.
.SH EXAMPLE
The  following  example is used to spawn of another  \*(mS command to create a
C-tags file:-
.CS
shell-command &cat $progname " \\"@ctags\\" *.c *.h" 
.CE 0
.SH "SEE ALSO"
.na
.Ht me 1 ,
.Ht shell-command 2 ,
.Ht $progdata 5 ,
.Ht $home 5 ,
.Ht $search-path 5 ,
.Ht $user-name 5 ,
.Ht $user-path 5 .
.ad
.FH
