.\" -*- nroff -*-
.Id $Id: m5var024.5,v 2.3 2001-12-06 00:04:32 jon Exp $
.Im MicroEmacs variable|hilight
.so me.tni
.TH $global-scheme 5
.XI $global-scheme - "Global buffer color scheme"
.SH NAME
$global-scheme \- Default global buffer color scheme.
.Me $a
.SH SYNOPSIS
\fC$global-scheme\fR \fCschemeNum\fR; Default is \fC0\fR
.SH DESCRIPTION
.B $global-scheme
defines the default buffer color scheme to  \fIschemeNum\fR,  a color
scheme defined by
.Ht add-color-scheme 2 .
.SH "SEE ALSO"
.na
.Ht add-color 2 ,
.Ht add-color-scheme 2 ,
.Ht $buffer-hilight 5 ,
.Ht $buffer-scheme 5 ,
.Ht $cursor-color 5 ,
.Ht $trunc-scheme 5 ,
.Ht $ml-scheme 5 ,
.Ht $osd-scheme 5 ,
.Ht $mode-line-scheme 5 ,
.Ht $scroll-bar-scheme 5 ,
.Ht $system 5 .
.ad
.FH
