.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2004 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m5var086.5,v 2.1 2004-01-17 22:27:28 jon Exp $
.Im MicroEmacs variable|window
.so me.tni
.TH $frame-id 5
.XI $frame-id - "Current frame identity"
.SH NAME
$frame-id \- Current frame identity
.SH SYNOPSIS
\fB$frame-id\fR
.SH DESCRIPTION
\fB$frame-id\fR retrieves the identity of the current frame, this is a integer
value (1..n) that is automatically allocated when the frame was created using 
.Ht create-frame 2 .
.PP
The  \fB$frame-id\fR  is  guaranteed  to be unique  and is  typically  used in
macros to locate a previously created frame.
.SH "SEE ALSO"
.na
.Ht create-frame 2 ,
.Ht delete-frame 2 ,
.Ht next-frame 2 ,
.Ht $window-id 5 .
.ad
.FH
