.\" -*- nroff -*-
.Id $Id: m5var063.5,v 1.1.1.1 2000-07-25 22:04:06 jon Exp $
.Im MicroEmacs variable|macrodevelop
.so me.tni
.TH .calc.result 5
.XI .calc.result - "Last calc calculation result"
.SH NAME
\&.calc.result \- Last calc calculation result
.Me $a
.SH SYNOPSIS
\fB.calc.result\fR \fIinteger\fR
.SH DESCRIPTION
.B .calc.result
is used to store the result of the last calculation made by
.Ht calc 3 .
.PP
The "\fILR\fR" (Last Result) in the next  calculation is substituted with this
value.
.SH "SEE ALSO"
.na
.Ht calc 3 .
.ad
.FH
