.\" -*- nroff -*-
.Id $Id: m5var080.5,v 1.1.1.1 2000-07-25 22:04:07 jon Exp $
.Im MicroEmacs variable|hilight
.so me.tni
.TH $trunc-scheme 5
.XI $trunc-scheme - "Truncation color scheme"
.SH NAME
$trunc-scheme \- Truncation color scheme.
.Me $a
.SH SYNOPSIS
\fB$trunc-scheme\fR \fIschemeNum\fR; Default is \fC0\fR
.SH DESCRIPTION
.B $trunc-scheme
sets the  color  scheme  used  when  drawing a line  truncation  indicator  (a
\&'\fC$\fR'  character).  A '$'  character  drawn  at the  start  of the  line
indicates that the line has been scrolled to the right and therefore the start
of the line has been  truncated.  A '$' at the end of the line  indicates  the
remainder  of the line is too long to fit onto the width of the  window so the
end has been truncated and the indicator drawn.
.PP
The \fIschemeNum\fR selected must be a color scheme defined with
.Ht add-color-scheme 2 ,
which identifies the foreground and background color schemes. A hilight scheme
can define its own truncation color scheme, see
.Ht hilight 2
for more information.
.SH "SEE ALSO"
.na
.Ht $buffer-scheme 5 ,
.Ht $global-scheme 5 ,
.Ht add-color-scheme 2 ,
.Ht hilight 2 .
.ad
.FH
