.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m5var087.5,v 2.2 2009-08-29 17:14:33 jon Exp $
.Im MicroEmacs variable|window
.so me.tni
.TH $window-id 5
.XI $window-id - "Current window identity"
.SH NAME
$window-id \- Current window identity
.SH SYNOPSIS
\fB$window-id\fR
.SH DESCRIPTION
\fB$window-id\fR  retrieves  the  identity  of the current  window,  this is a
integer  value  (1..n)  that is  automatically  allocated  when a window is 
created using 
.Ht split-window-horizontally 2
or
.Ht split-window-vertically 2 .
.PP
The  \fB$window-id\fR  is  guaranteed  to be unique  and is  typically  used in
macros to locate a previous window.
.SH "SEE ALSO"
.na
.Ht next-window 2 ,
.Ht split-window-horizontally 2 ,
.Ht split-window-vertically 2 ,
.Ht $frame-id 5 .
.ad
.FH
