.\"*-*- nroff -*-*************************************************************
.\"
.\"			     Copyright 2000 JASSPA.
.\"			      All Rights Reserved
.\"
.\"
.\"  System        :
.\"  Module        :
.\"  Object Name   : m5var049.5
.\"  Created By    : Jon Green
.\"  Created       : Wed Jan 26 00:47:52 2000
.\"  Last Modified : <000719.1013>
.\"
.\"  Description
.\"
.\"  Notes
.\"
.\"  History
.\"
.\"***************************************************************************
.\"
.\"  Copyright (c) 2000 JASSPA.
.\"
.\"  All Rights Reserved.
.\"
.\"  This  document  may not, in  whole  or in part, be  copied,  photocopied,
.\"  reproduced,  translated, or reduced to any  electronic  medium or machine
.\"  readable form without prior written consent from JASSPA.
.\"
.\"***************************************************************************
.\"
.\" -*- nroff -*-
.Id $Id: m5var049.5,v 2.2 2001-07-14 10:11:51 jon Exp $
.Im MicroEmacs variable|file
.so me.tni
.TH %ftp-flags 5
.XI %ftp-flags - "Configure the FTP console"
.XI %http-flags - "Configure the HTTP console"
.SH NAME
.Me "|%ftp-flags"
%ftp-flags \- "Configure the FTP console"
.br
.Me "|%http-flags"
%http-flags \- "Configure the HTTP console"
.Me $a
.SH SYNOPSIS
\fB%ftp-flags\fR "[\fCc\fR|\fCs\fR|\fCp\fR]" ; Default is undefined.
.br
\fB%http-flags\fR "[\fCc\fR|\fCs\fR|\fCp\fR]" ; Default is undefined.
.SH DESCRIPTION
The \fB%ftp-flags\fR and \fB%http-flags\fR  modify the behavior of the editor
during FTP and HTTP file transfers, respectively.
(see
.Ht ftp 3
and
.Ht find-file 2 ).
.PP
By default, the flags are disabled, the facilities  outlined below are enabled
by setting the  variable in the user  configuration.  The flag values for both
flags are defined as follows:-
.IP \fBc\fR
Create a console buffer (\fC*ftp-console*\fR for ftp, \fC*http-console*\fR for
http) into which the FTP/HTTP command  interactions with the remote server are
logged.
.IP \fBs\fR
Show the console  whenever a FTP/HTTP  operation is performed.  The console is
popped into the display pane and shows the current interaction status.
.IP \fBp\fR
Show the download  progress within the console window ('\fC#\fR' for every 2Kb
downloaded)
.LP
Typically the following flags are enabled in the \fIuser\fR.emf file:-
.Me $emf-scheme
.CS
set-variable %ftp-flags "csp"
set-variable %http-flags "csp"
.CE
.Me $ehf-scheme
Once familiar with this facility the console pop-up becomes  inconvenient  and
the flags are typically reduced to:-
.Me $emf-scheme
.CS
set-variable %ftp-flags "cp"
set-variable %http-flags "cp"
.CE
.Me $ehf-scheme
This disables the pop-up feature of the console. Enabling the limited flag set
allows some post mortem  debugging to be performed if anything goes wrong. The
console buffers are manually selected when these flags are set.
.SH NOTES
Note that ftp and http facilities are available on \s-1UNIX\s0 by default, but
must be compiled in for Windows versions.
.SH "SEE ALSO"
.na
.Ht %http-proxy-addr 5 ,
.Ht find-file 2 ,
.Ht ftp 3 .
.ad
.FH
