.\" -*- nroff -*-
.Id $Id: m5var017.5,v 1.2 2000-10-21 17:10:48 jon Exp $
.Im MicroEmacs variable|scuts
.so me.tni
.TH $c-statement 5
.XI $c-statement - "C-mode; statement indentation"
.SH NAME
$c-statement \- C-mode; statement indentation
.Me $a
.SH SYNOPSIS
\fB$c-statement\fR \fIinteger\fR; Default is \fC4\fR
.sp
\fI\-n\fR <= \fIinteger\fR <= \fIn\fR
.SH DESCRIPTION
.B $c-statement
is part of the
.Ht cmode 2m
environment for C programmers.
.PP
The indent of the current  line is derived  from  \fB$c-statement\fR  plus the
indent of the last c token  (\fIif\fR,  \fIelse\fR,  \fIwhile\fR  etc.) or the
last  '\fC{\fR'  (which ever was found first). i.e. if the last  '\fC{\fR' was
found at column 16 then the current line will be indented to 20:-
.CS
        {
            xxxxxxxxxx
            xxxxxxxxxx
.CE
or
.CS
        if(xxxxx)
            xxxxxxxxxx
.CE                    
C tokens are only used to indent the next line, whereas  '\fC{\fR' are used in
indenting every line to it's partnering '\fC}\fR'.
.SH "SEE ALSO"
.na
.Ht cmode 2m .
.ad
.FH
