.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ010.9,v 2.6 2009/08/29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH p 9
.XI p - "Pascal File"
.XI pas - "Pascal File"
.SH SYNOPSIS
p, pas \- Pascal files
.SH FILES
.na
.B hkpascal.emf
\- Pascal hook definition
.br
.B pascal.etf
\- Pascal template file.
.ad
.SH EXTENSIONS
.na
\fB.p\fR, \fB.pas\fR \- Pascal file
.ad
.SH DESCRIPTION
The  \fBpascal\fR  file type  template  provides  simple  hilighting of Pascal
files, the template provides minimal hilighting.
.SH BUGS
None reported.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
