.\" -*- nroff -*-
.\" Copyright (C) 1999-2009 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.\"  Created By    : Detlef Groth
.\"  Created       : Mon Mar 10 09:14:00 2025
.\"
.Id $Id: m9typ049.9,v 2.8 2025/03/26 14:27:37 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH go 9
.XI go - "Go programming language"
.SH SYNOPSIS
go \- Go programming language templates
.SH FILES
.na
.B hkgo.emf
\- Go programming language hook definition
.br
.B go.etf
\- Go programming language template file
.ad
.SH EXTENSIONS
.na
\fB.go\fR \- Go
.ad
.SH DESCRIPTION
The \fBgo\fR file type  templates share much with the 
.Ht c 9 
template definitions, utilising the electric 'C' features for automatic layout
of text.
.IP "\fBGeneral Editing\fR"
On creating a new file, a new header is automatically included into the file.
.Ht time 2m
is by default enabled, allowing the modification time-stamp to be maintained in
the header.
.IP \fBHilighting\fR
The  hilighting  features allow  commands,  variables,  logical,  preprocessor
definitions,   comments,   strings  and  characters  of  the  language  to  be
differentiated and rendered in different colors.
.IP "\fBAuto Layout\fR"
The C-Mode
.Ht indent 2
performs automatic layout of the text.
.IP
.Ht restyle-region 3
and
.Ht restyle-buffer 3
are available to reformat  (re-layout) selected sections of the buffer, or the
whole buffer, respectively.
.IP
Comments  may be formatted  using  \fC\*eo\fR,  which  reformats  the  comments
according  to  the  current  fill  paragraph.  If  a  comment  commences  with
\fC/***...\fR then the comment is automatically formatted to a box.
.IP "\fBFolding and Information Hiding\fR"
Generic folding is enabled within the Java Go. The folds occur about functions starting
with the  \fCfunc\fR  keyword and a closing  curly brace at he  beginning  of a
line.
.Ht collapse-all 3
(un)folds all regions in the file,
.Ht collapse-current 3
(un)folds the current region.
.IP "\fBWorking Environment\fR"
.Ht compile 3
may be invoked to rebuild the source, the user is prompted to save any files.
.IP "\fBShort Cuts\fR"
The short cut keys used within the buffer are:-
.IP
\fB\*cc \*cc\fR \- Comment out the current line.
.br
\fB\*cc \*cd\fR \- Uncomment the current line.
.br
\fB\*cc \*ce\fR \- Comment to the end of the line with stars (*).
.br
\fB\*a\*ci\fR \- Restyle the current region.
.br
\fB\*eq\fR \- Format a comment.
.br
\fB\*eo\fR \- Format a comment.
.br
\fBf2\fR \- (Un)fold the current region.
.br
\fB\*cf2\fR \- (Un)fold all regions.
.br
\fBf6\fR \- List items.
.br
\fB\*ef6\fR \- Close item list,
.SH NOTES
.PP
The  hilighting  is  typically   extended  using  a  file   \fBmygo.emf\fR
.SH "SEE ALSO"
.na
.Ht c 9 ,
.Ht collapse-all 3 ,
.Ht collapse-current 3 ,
.Ht compile 3 ,
.Ht restyle-buffer 3 ,
.Ht restyle-region 3 ,
.Ht time 2m .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
