.\" -*- nroff -*-
.\" Copyright (C) 1999-2025 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.\"  Created By    : Detlef Groth
.\"  Created       : Tue Jul 05 09:12:00 2025
.\"
.Id $Id: m9typ054.9,v 2.8 2025/07/30 21:58:36 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH vlang 9
.XI vlang - "V programming language"
.SH SYNOPSIS
V-lang \- V programming language 
.SH FILES
.na
.B hkv.emf
\- V programming language hook definition
.br
.B v.eaf
\- V programming language abbreviation file
.br
.B v.etf
\- V programming language template file
.ad
.SH EXTENSIONS
.na
\fB.v\fR \- V-lang
.ad
.SH DESCRIPTION
The \fBv\fR file type  templates share much with the 
.Ht c 9 
template definitions, utilising the electric 'C' features for automatic layout
of text.
.IP "\fBGeneral Editing\fR"
On creating a new file, a new header is automatically included into the file.
.Ht time 2m
is by default enabled, allowing the modification time-stamp to be maintained in
the header.
.IP "\fBHilighting\fR"
The  hilighting  features allow  commands,  variables,  logical,  preprocessor
definitions,   comments,   strings  and  characters  of  the  language  to  be
differentiated and rendered in different colors.
.IP "\fBAuto Layout\fR"
The C-Mode
.Ht indent 2
performs automatic layout of the text.
.IP
.Ht restyle-region 3
and
.Ht restyle-buffer 3
are available to reformat  (re-layout) selected sections of the buffer, or the
whole buffer, respectively.
.IP
Comments  may be formatted  using  \fC\*eo\fR,  which  reformats  the  comments
according  to  the  current  fill  paragraph.  If  a  comment  commences  with
\fC/***...\fR then the comment is automatically formatted to a box.
.IP "\fBFolding and Information Hiding\fR"
Generic  folding  is  enabled  within  the V  file. The folds  occur  about
functions defined with the \fBfn\fR keyword and  a closing  curly brace both 
at the  beginning  of a line.
.Ht collapse-all 3
(un)folds all regions in the file,
.Ht collapse-current 3
(un)folds the current region.
.IP "\fBNavigation via Item List\fR"
The V mode offers beside folding as well support for displaying an outline of the
functions and structures of the V file for easy navigation using the 
.Ht item-list 3
command. Public functions are highlighted with color in the item list.
.IP "\fBAbbreviations\fR"
The  installation  comes with a default  abbreviation  file for V language file  editing
which  can  be  used  by  writing  short   abbreviations   like   "\fBfor\fR",
"\fBif\fR", "\fBelif\fR" (else if), "\fBstr\fR" (public structure)  or "\fBfn\fR" (function) -
and then pressing the key-binding for the 
.Ht expand-abbrev-handle 3
command.  The  list  of  abbreviations  can be used  interactively  in the GUI
version of \*(mE using the 
.Ht abbrev-list 3
command.
.IP "\fBWorking Environment\fR"
.Ht compile 3
may be invoked to rebuild the source, the user is prompted to save any files.
.IP "\fBShort Cuts\fR"
The short cut keys used within the buffer are:-
.IP
\fB\*cc \*cc\fR \- Comment out the current line.
.br
\fB\*cc \*cd\fR \- Uncomment the current line.
.br
\fB\*cc \*ce\fR \- Comment to the end of the line with stars (*).
.br
\fB\*a\*ci\fR \- Restyle the current region.
.br
\fB\*eq\fR \- Format a comment.
.br
\fB\*eo\fR \- Format a comment.
.br
\fBf2\fR \- (Un)fold the current region.
.br
\fB\*cf2\fR \- (Un)fold all regions.
.br
\fBf6\fR \- List items.
.br
\fB\*ef6\fR \- Close item list,
.IP "\fBExecuting, Formatting and Linting V Code\fR"
The V file hook supports the 
.Ht file-exec 3 ,
the 
.Ht file-format 3
and the 
.Ht file-lint 3
macros.  The  tools,  compilers  which  are  currently  supported  are  just the V
sub-commands usable for this task so "v run", "v fmt" and "v vet".
.SH NOTES
.PP
The  hilighting  or the addition of new item list matches  is  typically
extended  using  a  file   \fBmyv.emf\fR.
.PP
As this language shares the same extensions as Verilog files you might be adding the add the 
following line to your user emf file.
.Me $emf-scheme
.CS
add-file-hook ".v" fhook-v
.CE 0
.Me $ehf-scheme
.PP
As an alternative you can add the following first line to your V-files so that
they are automatically recognized as V language files and not as Verilog files.
.CS
// -!- v-lang -!-
.CE 0
.SH "SEE ALSO"
.na
.Ht abbrev-list 3 ,
.Ht c 9 ,
.Ht collapse-all 3 ,
.Ht collapse-current 3 ,
.Ht compile 3 ,
.Ht expand-abbrev-handle 3 ,
.Ht file-exec 3 ,
.Ht file-format 3 ,
.Ht file-lint 3 ,
.Ht item-list 3 ,
.Ht restyle-buffer 3 ,
.Ht restyle-region 3 ,
.Ht time 2m .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
