.\"*-*- nroff -*-*************************************************************
.\"
.\"			Copyright 1999 JASSPA.
.\"			      All Rights Reserved
.\"
.\"
.\"  System        :
.\"  Module        :
.\"  Object Name   : m9typ001.9
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"  Last Modified : <000719.1013>
.\"
.\"  Description
.\"
.\"  Notes
.\"
.\"  History
.\"
.\"***************************************************************************
.\"
.\"  Copyright (c) 1999 JASSPA.
.\"
.\"  All Rights Reserved.
.\"
.\"  This  document  may not, in  whole  or in part, be  copied,  photocopied,
.\"  reproduced,  translated, or reduced to any  electronic  medium or machine
.\"  readable form without prior written consent from JASSPA.
.\"
.\"***************************************************************************
.\"
.Id $Id: m9typ001.9,v 1.2 2000-10-21 17:11:05 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH ehf 9
.XI ehf - "\*(mE help file"
.SH SYNOPSIS
ehf \- \*(mE help file
.SH FILES
.na
.B hkehf.emf
\- \*(mE help file.
.ad
.SH EXTENSIONS
.na
\fB.ehf\fR, \fB*help*\fR
.ad
.SH DESCRIPTION
The \fBehf\fR file type template performs the hilighting of the help file. The
\fBehf\fR  file is a computer  generated  file and uses special  embedded text
markers to indicate the required color scheme.
.PP
The macro file includes special macros to locate help information.
.SH "SEE ALSO"
.na
.Ht help 2 .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
