.\" -*- nroff -*-
.\" Copyright (C) 1999-2025 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Thu Jun 24 22:02:47 1999
.\"
.Id $Id: m9typ048.9,v 2.6 2025/07/23 18:28:38 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH r 9
.XI r - "R Language File"
.SH SYNOPSIS
r \- R Language File.
.SH FILES
.na
.B hkr.emf
\- R Language file hook definition
.br
.B r.eaf
\- R language abbreviation file
.br
.B r.etf
\- R language template file
.ad
.SH EXTENSIONS
.na
\fB.r\fR \- R file
.ad
.SH "MAGIC STRINGS"
.TP
\fB^#![ \\t]*/.*env[ \\t]+Rscript\fR
.\"
\*(mE recognizes the magic string on the first line of the file used to locate
the  executable.  The  Rscript  files  may  be  extension-less  and  are  still
recognized.
.SH DESCRIPTION
The  \fBR\fR  macro  file  hook  provides   simple   hilighting  of  R  files,
inserting abbreviations and browsing the structure of the file using item-list
and folding..
.PP
File  recognition  is performed  using the standard file  extension  \fB.r\fR,
\fB.R\fR or by the magic string.
.IP "\fBAbbreviations\fR"
The  installation  comes with a default  abbreviation  file for R code  editing
which  can  be  used  by  writing  short   abbreviations   like   "\fBmain\fR"
for a default Rscript application outline,"\fBfor\fR",
"\fBif\fR"  or  "\fBfun\fR"  -  for  a R  function  - and  then  pressing  the
key-binding  for the 
.Ht expand-abbrev-handle 3
command.  The  list  of  abbreviations  can be used  interactively  in the GUI
version of \*(mE using the 
.Ht abbrev-list 3
command.
.IP "\fBFolding and Information Hiding\fR"
Generic  folding is enabled  within the R files. The folds occur about
the \fBfunction\fR keywords located on the left-hand margin at the beginning 
of the line if the smaller-minus assignment operator is used.
The following commands are supported to show and hide the function bodies.
.Ht collapse-all 3
(un)folds all regions in the file,
.Ht collapse-current 3
(un)folds the current region.
.IP "\fBList Items\fR"
Item listing is available and the key  constructs of the file may be listed in
the \fIitem-list\fR.
.IP "\fBShort Cuts\fR"
The short cut keys used within the buffer are:-
.IP
\fB\*cc \*cc\fR \- Comment out the current line.
.br
\fB\*cc \*cd\fR \- Uncomment the current line.
.br
\fB\*cc \*ce\fR \- Comment to the end of the line with stars (*).
.br
\fB\*a\*ci\fR \- Restyle the current region.
.br
\fBf2\fR \- (un)fold the current region
.br
\fBf3\fR \- (un)fold all regions
.br
\fBf6\fR \- list items
.br
\fB\*e f6\fR \- close list items
.SH BUGS
Functions with using the equal operator for  assignments  are not shown in the
function  outline,  this should be seen as a feature  which allow you to write
hidden internal functions within other functions.
.SH "SEE ALSO"
.na
.Ht abbrev-list 3 ,
.Ht c 9 ,
.Ht collapse-all 3 ,
.Ht collapse-current 3 ,
.Ht compile 3 ,
.Ht expand-abbrev-handle 3 ,
.Ht item-list 3 ,
.Ht restyle-buffer 3 ,
.Ht restyle-region 3 ,
.Ht py 9 .
.Ht sh 9 .
.Hl "Supported File Types" FileTypes -
.ad
.FH

