.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ013.9,v 2.6 2009-08-29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH sql 9
.XI sql - "SQL File"
.SH SYNOPSIS
sql \- SQL files
.SH FILES
.na
.B hksql.emf
\- SQL hook definition
.br
.B sql.etf
\- SQL template file.
.ad
.SH EXTENSIONS
.na
\fB.sql\fR \- SQL file
.ad
.SH DESCRIPTION
The  \fBsql\fR  file type  template  provides  simple  hilighting of SQL
files, the template provides minimal hilighting.
.SH BUGS
None reported.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
