.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ021.9,v 2.7 2009/08/29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH erf 9
.XI erf - "\*(mE registry file"
.SH SYNOPSIS
erf \- \*(mS registry file
.SH FILES
.na
.B hkerf.emf
\- \*(mS registry file.
.ad
.SH EXTENSIONS
.na
\fB.erf\fR, \fB*registry*\fR
.ad
.SH DESCRIPTION
The \fBerf\fR file type template performs the hilighting of the registry file.
.IP \fBHilighting\fR
The  hilighting  features allows components of  the  language  to  be
differentiated and rendered in different colors.
.IP "\fBAuto Layout\fR"
The
.Hl "indentation mechanism" indent 2 
is enabled which performs automatic layout of the text.
.Ht restyle-region 3
and
.Ht restyle-buffer 3
are available to reformat  (re-layout) selected sections of the buffer, or the
whole buffer, respectively.
.SH "SEE ALSO"
.na
.Ht list-registry 2 ,
.Ht erf 8 .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
