.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ006.9,v 2.6 2009-08-29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH imakefile 9
.XI imakefile - "Make file"
.SH SYNOPSIS
imakefile \- Make file
.SH FILES
.na
.B hkimake.emf
\- Imakefile hook definition
.br
.B imake.etf
\- Template file
.ad
.SH EXTENSIONS
.na
\fBImakefile\fR, \fBimakefile\fR \- Imakefiles.
.ad
.SH DESCRIPTION
The   \fBImakefile\fR   file  type   template   handles  the   hilighting   of  the
Imakefile files. 
.IP "\fBGeneral Editing\fR"
On creating a new file, a new header is automatically included into the file.
.Ht time 2m
is by default enabled, allowing the modification time-stamp to be maintained in
the header.
.IP
By default,  \fCTAB\fR's are enabled as this is the syntactical feature of the
file.
.IP \fBHilighting\fR
The  hilighting  emphasizes the keywords and comments  within the Imakefile. 
.SH BUGS
No attempt is made to hilight any embedded shell commands.
.SH "SEE ALSO"
.na
.Ht makefile 9 ,
.Ht time 2m .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
