.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Thu Jun 24 21:54:42 1999
.\"
.Id $Id: m9typ032.9,v 2.6 2009/08/29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH m4 9
.XI m4 - "M4 Macro Processor"
.SH SYNOPSIS
me \- M4 Macro Processor
.SH FILES
.na
.B hkm4.emf
\- M4 macro processor macro file.
.br
.B m4.etf
\- M4 macro processor header template file.
.ad
.SH EXTENSIONS
.na
\fB.m4\fR
.ad
.SH DESCRIPTION
The \fBM4 macro processor\fR  template performs simple hilighting of \fB.m4\fR
files. The file type is recognized by the standard extension only.
.IP \fBHilighting\fR
The  hilighting  features allows components of  the  language  to  be
differentiated and rendered in different colors.
.SH NOTES
The M4 hilighting is minimal, no other features have been implemented.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
