.\"*-*- nroff -*-*************************************************************
.\"
.\"			Copyright 1999 JASSPA.
.\"			      All Rights Reserved
.\"
.\"
.\"  System        :
.\"  Module        :
.\"  Object Name   : m9typ018.9
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"  Last Modified : <000719.1013>
.\"
.\"  Description
.\"
.\"  Notes
.\"
.\"  History
.\"
.\"***************************************************************************
.\"
.\"  Copyright (c) 1999 JASSPA.
.\"
.\"  All Rights Reserved.
.\"
.\"  This  document  may not, in  whole  or in part, be  copied,  photocopied,
.\"  reproduced,  translated, or reduced to any  electronic  medium or machine
.\"  readable form without prior written consent from JASSPA.
.\"
.\"***************************************************************************
.\"
.Id $Id: m9typ018.9,v 1.1.1.1 2000-07-25 22:04:09 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH java 9
.XI java - "Java programming language"
.XI jav - "Java programming language"
.SH SYNOPSIS
java \- Java programming language templates
.SH FILES
.na
.B hkjava.emf
\- Java programming language hook definition
.br
.B java.etf
\- Java programming language template file
.ad
.SH EXTENSIONS
.na
\fB.java\fR, \fB.jav\fR \- Java 
.ad
.SH DESCRIPTION
The \fBjava\fR file type  templates share much with the 
.Ht c 9 
template definitions, utilising the electric 'C' features for automatic layout
of text.
.IP "\fBGeneral Editing\fR"
On creating a new file, a new header is automatically included into the file.
.Ht time 2m
is by default enabled, allowing the modification time-stamp to be maintained in
the header.
.IP \fBHilighting\fR
The  hilighting  features allow  commands,  variables,  logical,  preprocessor
definitions,   comments,   strings  and  characters  of  the  language  to  be
differentiated and rendered in different colors.
.IP "\fBAuto Layout\fR"
The electric C-Mode
.Ht cmode 2m
performs automatic layout of the text, variables such as
.Ht c-brace 5
allow the brace position and text formation to be modified.
.IP
.Ht restyle-region 3
and
.Ht restyle-buffer 3
are available to reformat  (re-layout) selected sections of the buffer, or the
whole buffer, respectively.
.IP
Comments  may be formatted  using  \fC\*eo\fR,  which  reformats  the  comments
according  to  the  current  fill  paragraph.  If  a  comment  commences  with
\fC/***...\fR then the comment is automatically formatted to a box.
.IP "\fBFolding and Information Hiding\fR"
Generic folding is enabled within the Java files. The folds occur about braces
\fB{\fR...\fB}\fR located on the left-hand margin.
.Ht fold-all 3
(un)folds all regions in the file,
.Ht fold-current 3
(un)folds the current region.
Note that  folding does not operate on K&R style code, with the trailing  open
brace.
.IP "\fBWorking Environment\fR"
.Ht compile 3
may be invoked to rebuild the source, the user is prompted to save any files.
.IP
.Ht rcs-file 2
is automatically  invoked if an RCS file is detected, the normal  check-in/out
operations may be performed through the editor.
.IP "\fBShort Cuts\fR"
The short cut keys used within the buffer are:-
.IP
\fB\*cc \*cc\fR \- Comment out the current line.
.br
\fB\*cc \*cd\fR \- Uncomment the current line.
.br
\fB\*cc \*ce\fR \- Comment to the end of the line with stars (*).
.br
\fB\*a\*ci\fR \- Restyle the current region.
.br
\fB\*eq\fR \- Format a comment.
.br
\fB\*eo\fR \- Format a comment.
.br
\fBf2\fR \- (un)fold the current region
.br
\fBf3\fR \- (un)fold all regions
.SH NOTES
.PP
The  hilighting  is  typically   extended  using  a  file   \fBmyjava.emf\fR
.SH "SEE ALSO"
.na
.Ht c 9 ,
.Ht c-brace 5 ,
.Ht cmode 2m ,
.Ht compile 3 ,
.Ht find-tag 2 ,
.Ht fold-all 3 ,
.Ht fold-current 3 ,
.Ht rcs-file 2 ,
.Ht restyle-buffer 3 ,
.Ht restyle-region 3 ,
.Ht time 2m .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
