.\" -*- nroff -*-
.\" Copyright (C) 1999-2009 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ002.9,v 2.7 2025/07/04 12:11:39 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH emf 9
.XI emf - "\*(mE Macro File"
.SH SYNOPSIS
emf \- \*(mE Macro File
.SH FILES
.na
.B hkemf.emf
\- \*(mE Macro File hook definition
.br
.B eaf.etf
\- Abbreviation file
.br
.B emf.etf
\- Template file
.ad
.SH EXTENSIONS
.na
\fB.emf\fR \- \*(mE Macro File
.ad
.SH DESCRIPTION
The \fBemf\fR  file type  template  handles the  hilighting of the \*(mE macro
files. 
.IP "\fBGeneral Editing\fR"
On creating a new file, a new header is automatically included into the file.
.Ht time 2m
is by default enabled, allowing the modification time-stamp to be maintained in
the header.
.IP \fBHilighting\fR
The hilighting  features allow commands, variables, logical, comments, strings
and characters of the language to be differentiated  and rendered in different
colors.
.IP "\fBAuto Layout\fR"
The 
.Hl "indentation mechanism" indent 2 
is enabled which performs 
performs automatic layout of the text.
.Ht restyle-region 3
and
.Ht restyle-buffer 3
are available to reformat  (re-layout) selected sections of the buffer, or the
whole buffer, respectively.
.IP "\fBTags\fR"
A C-tags file may be generated within the editor using the \fBTools\fR \->
\fBEmf-Tools\fR \-> \fBCreate Tag File\fR.
.Ht find-tag 2
takes the user to the file using the tag information.
.IP "\fBFolding and Information Hiding\fR"
Generic  folding is enabled  within the \fBemf\fR files. The folds occur about
\fBdefine-macro\fR and \fB!emacro\fR text located on the left-hand margin.
.Ht collapse-all 3
(un)folds all regions in the file,
.Ht collapse-current 3
(un)folds the current region.
.IP "\fBNavigation via Item List\fR"
The Emf macro mode offers beside folding as well support for displaying an outline of the
functions and help definitions of the Macro file for easy navigation using the 
.Ht item-list 3
command.
.IP "\fBAbbreviations\fR"
The  installation  comes with a default  abbreviation  file for MicroEmacs macro file  editing
which  can  be  used  by  writing  short   abbreviations   like   "\fB!w\fR" (while),
"\fB!i\fR" (if) or "\fBde\fR" (define-macro)- and then pressing the key-binding for the 
.Ht expand-abbrev-handle 3
command.  The  list  of  abbreviations  can be used  interactively  in the GUI
version of \*(mE using the 
.Ht abbrev-list 3
command.
.IP "\fBShort Cuts\fR"
The short cut keys used within the buffer are:-
.IP
\fB\*cc \*cc\fR \- Comment out the current line.
.br
\fB\*cc \*cd\fR \- Uncomment the current line.
.br
\fB\*cc \*e\*e\fR \- Command complete.
.br
\fB\*a\*ci\fR \- Restyle the current region.
.br
\fBf2\fR \- (un)fold the current region
.br
\fBf3\fR \- (un)fold all regions
.SH BUGS
No bugs reported
.SH "SEE ALSO"
.na
.Ht abbrev-list 3 ,
.Ht collapse-all 3 ,
.Ht collapse-current 3 ,
.Ht emftags 3f ,
.Ht expand-abbrev-handle 3 ,
.Ht find-tag 2 ,
.Ht indent 2 ,
.Ht item-list 3 ,
.Ht restyle-buffer 3 ,
.Ht restyle-region 3 ,
.Ht time 2m .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
