.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ015.9,v 2.5 2002-01-11 21:58:43 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH awk 9
.XI awk - "AWK File"
.XI gawk - "GNU AWK File"
.XI nawk - "New AWK File"
.SH SYNOPSIS
awk \- AWK files
.SH FILES
.na
.B hkawk.emf
\- AWK hook definition
.br
.B awk.etf
\- AWKL template file.
.ad
.SH EXTENSIONS
.na
\fB.awk\fR \- AWK file
.br
\fB.gawk\fR \- GNU AWK file
.br
\fB.nawk\fR \- New AWK file
.ad
.SH "MAGIC STRINGS"
.TP 
\fB#![ \\t]*/.*awk\fR
.\"
\*(mE recognises the magic string on the first line of the file used to locate
the executable. The awk files may be extensionless and are still recognised.
.SH DESCRIPTION
The  \fBawk\fR  file type  template  provides  simple  hilighting of AWK
files, the template provides minimal hilighting.
.SH BUGS
None  reported.  Template  could  probably  benifit  from  some  form  of auto
indentation.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
