.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ014.9,v 2.6 2009/08/29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH vhdl 9
.XI vhdl - "VHDL hardware simulation File"
.SH SYNOPSIS
vhdl \- VHDL hardware simulation files
.SH FILES
.na
.B hkvhdl.emf
\- VHDL hook definition
.br
.B vhdl.etf
\- VHDL template file.
.ad
.SH EXTENSIONS
.na
\fB.vhdl\fR, \fB.vhd\fR \- VHDL file
.ad
.SH DESCRIPTION
The  \fBvhdl\fR  file type  template  provides  simple  hilighting of VHDL
files, the template provides minimal hilighting.
.SH BUGS
None  reported.  Template  could  probably  benifit  from  some  form  of auto
indentation.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
