.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ004.9,v 2.7 2009/08/29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH latex 9
.XI latex - "TeX Documentation"
.XI bib - "TeX Bibliography File"
.XI tex - "TeX Documentation"
.XI sty - "TeX Style File"
.SH SYNOPSIS
latex \- TeX Documentation
.SH FILES
.na
.B hklatex.emf
\- Tex File hook definition
.br
.B latex.etf
\- Template file
.br
.B hkbibtex.emf
\- TeX Bibliography Files
.ad
.SH EXTENSIONS
.na
\fB.tex\fR \- TeX Documentation
.br
\fB.bib\fR \- TeX Bibliography Files
.br
\fB.sty\fR \- TeX Style file
.ad
.SH DESCRIPTION
The  \fBlatex\fR  file  type  template  handles  the  hilighting  of  the  TeX
files. The hilighting is minimal, hilighting the key words and comments.
.IP "\fBGeneral Editing\fR"
On creating a new file, a new header is automatically included into the file.
.Ht time 2m
is by default enabled, allowing the modification time-stamp to be maintained in
the header.
.IP \fBHilighting\fR
The  hilighting  emphasizes the Tex embedded  command  strings and comments. No
special recognition of the command strings is performed.
.IP "\fBOutline Hilighting\fR"
The LaTeX content may be viewed with synthetic  hilighting  such that headers,
text  in  bold  and  italic  are   displayed,   removing  the  LaTeX   control
sequences.
.IP "\fBFolding and Information Hiding\fR"
Generic  folding is enabled,  the folds occur about
\fB\\section{...}\fR and \fB\\subsection{...}\fR constructs.
.Ht collapse-all 3
(un)folds all regions in the file,
.Ht collapse-current 3
(un)folds the current region.
.IP "\fBSpelling\fR"
Buffer spell checking is LaTeX aware.
.IP "\fBList Items\fR"
Item listing is available and the key  constructs of the file may be listed in
the \fIitem-list\fR.
.IP "\fBBuffer Commands\fR"
.B latex-verify
verifies  the  syntax  of the  (La)TeX  from  the  current  position  forward,
reporting braces that are not matched.
.IP "\fBShort Cuts\fR"
The short cut keys used within the buffer are:-
.IP
\fB\*cc \*cc\fR \- Comment out the current line.
.br
\fB\*cc \*cd\fR \- Uncomment the current line.
.br
\fB\*cc \*ce\fR \- Comment to the end of the line with hash (%).
.br
\fB\*cc \*co\fR \- Format a comment
.br
\fBf2\fR \- (un)fold the current region
.br
\fBf3\fR \- (un)fold all regions
.br
\fBf6\fR \- List items.
.br
\fB\*ef6\fR \- Close list items window.
.sp 1
The command  \fBlatex-compile\fR  is available within the buffer which invokes
an external process to build the text.
.br
.SH BUGS
No bugs reported
.SH "SEE ALSO"
.na
.Ht time 2m .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
