.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ020.9,v 2.6 2009-08-29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH asn.1 9
.XI asn.1 - "ASN.1 file"
.SH SYNOPSIS
asn.1 \- ASN.1 File
.SH FILES
.na
.B asn1.emf
\- asn.1 file hook definition
.br
.B ans1.etf
\- Template file
.ad
.SH EXTENSIONS
.na
\fBasn1\fR \- ASN.1 files.
.ad
.SH "MAGIC STRINGS"
.IP "\fB-!- asn.1 -!-\fR"
Recognized by MicroEmacs only, defines the file to be a asn.1.
.SH DESCRIPTION
The   \fBasn1\fR   file  type   template   handles  the   hilighting   of  the
asn.1 files.
.IP "\fBGeneral Editing\fR"
On creating a new file, a new header is automatically included into the file.
.Ht time 2m
is by default enabled, allowing the modification time-stamp to be maintained in
the header.
.IP
By default,  \fCTAB\fR's are enabled as this is the syntactical feature of the
file.
.IP \fBHilighting\fR
The  hilighting  emphasizes the keywords and comments  within the asn.1.
.SH BUGS
None reported.
.SH "SEE ALSO"
.na
.Ht time 2m .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
