.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ044.9,v 1.2 2009/08/29 17:14:33 jon Exp $
.Im MicroEmacs 
.so me.tni
.TH php 9
.XI php - "PHP: Hypertext Preprocessor Language" filetype
.XI php3 - "PHP: Hypertext Preprocessor Language" filetype
.XI php4 - "PHP: Hypertext Preprocessor Language" filetype
.XI phphtml - "PHP: Hypertext Preprocessor Language"
.SH SYNOPSIS
php \- PHP: Hypertext Preprocessor Language File.
.SH FILES
.na
.B hkphp.emf
\- PHP: Hypertext Preprocessor file hook definition
.ad
.SH EXTENSIONS
.na
\fB.php\fR, \fB.php3\fR, \fB.php4\fR, \fB.phphtml\fR \- PHP: Hypertext Preprocessor Language Language File.
.ad
.SH DESCRIPTION
The \fBphp\fR file type template provides simple hilighting of the Open Source
general-purpose  scripting  language PHP files. PHP is typically used embedded
within
.Ht html 9 
files.
.IP "\fBList Items\fR"
Item listing is available and the key  constructs of the file may be listed in
the \fIitem-list\fR.
.IP "\fBShort Cuts\fR"
The short cut keys used within the buffer are:-
.IP
\fB\*eh\fR \- Key binding help information.
.br
\fB\*cc \*cc\fR \- Comment out the current line.
.br
\fB\*cc \*cd\fR \- Uncomment the current line.
.br
\fB\*cc \*ce\fR \- Comment to the end of the line with hash (#).
.br
\fB\*cc \*co\fR \- Format a comment
.br
\fBf6\fR \- List items.
.br
\fB\*ef6\fR \- Close list items window.
.SH BUGS
None  reported.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
