.\" -*- nroff -*-
.\" Copyright (C) 1999-2025 JASSPA (www.jasspa.com)
.\"
.\" This is part of JASSPA's MicroEmacs, see the LICENSE file for licensing and
.\" copying information.
.\"
.\"  Created By    : Detlef Groth
.\"  Created       : 2025-07-23
.\"
.Id $Id: m9typ057.9,v 2.6 2025/07/23 22:50:38 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH jl 9
.XI jl - "Julia File"
.XI julia - "Julia File"
.SH SYNOPSIS
p, pas \- Julia files
.SH FILES
.na
.B hkjulia.emf
\- Julia hook definition
.br
.B julia.eaf
\- Julia abbreviation file
.br
.B julia.etf
\- Julia template file.
.ad
.SH EXTENSIONS
.na
\fB.jl\fR \- Julia file
.ad
.SH DESCRIPTION
The  \fBJulia\fR  file type  editing provides  simple  hilighting of Julia
files, abbreviations, folding and an item-list.
.IP "\fBAbbreviations\fR"
The  installation  comes with a default  abbreviation  file for Julia file  editing
which  can  be  used  by  writing   short   abbreviations   like   "\fBif\fR",
"\fBel\fR" (else) or "\fBfu\fR" (function) - and then pressing the key-binding for the 
.Ht expand-abbrev-handle 3
command.  
The  list  of  abbreviations  can be used  interactively  in the GUI
version of \*(mE using the 
.Ht abbrev-list 3
command.
.IP "\fBFolding and Information Hiding\fR"
Generic  folding  is  enabled  within  the Julia  file. The folds  occur  about
functions,  macros and structs as long as these declarations are on
one line and ending at a line starting with the \fBend\fR keyword.
.Ht collapse-all 3
(un)folds all regions in the file,
.Ht collapse-current 3
(un)folds the current region.
.IP "\fBNavigation via Item List\fR"
The Julia mode offers beside folding as well support for displaying an outline of the
functions, macros and structs for easy navigation using the 
.Ht item-list 3
command.
.IP "\fBShort Cuts\fR"
The short cut keys used within the buffer are:-
.IP
\fB\*cc \*cc\fR \- Comment out the current line.
.br
\fB\*cc \*cd\fR \- Uncomment the current line.
.br
\fB\*cc \*ce\fR \- Comment to the end of the line with stars (#).
.br
\fB\*a\*ci\fR \- Restyle the current region.
.br
\fB\*eq\fR \- Format a comment.
.br
\fB\*eo\fR \- Format a comment.
.br
\fBf2\fR \- (Un)fold the current region.
.br
\fB\*cf2\fR \- (Un)fold all regions.
.br
\fBf6\fR \- List items.
.br
\fB\*ef6\fR \- Close item list,
.SH BUGS
None reported so far.
.SH "SEE ALSO"
.na
.Ht abbrev-list 3 ,
.Ht collapse-all 3 ,
.Ht collapse-current 3 ,
.Ht expand-abbrev-handle 3 ,
.Ht item-list 3 ,
.Ht restyle-buffer 3 ,
.Ht restyle-region 3 ,
.Ht time 2m .
.sp 1
.Hl "Supported File Types" FileTypes -
.ad
.FH
