.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Thu Jun 24 22:14:09 1999
.\"
.Id $Id: m9typ034.9,v 2.6 2009-08-29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH scheme 9
.XI scheme - "Scheme File"
.XI scm - "Scheme File"
.XI sch - "Scheme File"
.SH SYNOPSIS
scheme \- Scheme File.
.SH FILES
.na
.B hkscheme.emf
\- Scheme file hook definition
.ad
.SH EXTENSIONS
.na
\fB.scm\fR, \fB.sch\fR \- Scheme file
.ad
.SH DESCRIPTION
The  \fBscheme\fR  file type  template  provides  simple  hilighting of Scheme
files, the template provides minimal hilighting.
.PP
File recognition is performed using the standard file extensions  \fB.scm\fR or
\fB.sch\fR.
.SH NOTES
\s-1JASSPA\s0 have no idea as to the state of this file hook definition.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH

