##############################################################################
# This is part of the JASSPA MicroEmacs.
# Copyright (C) 1997-2009 JASSPA (www.jasspa.com)
# See the file COPYING for copying and conditions.
#
# Created:       Thu Feb 5 21:36:24 2004
# Synopsis:      Installation Makefile
# Authors:       Jon Green
#
##############################################################################

TOPDIR=..
include $(TOPDIR)/etc/makeinc
#
# Build components
#
HTSS	=	me.hts
HLPS	=	me.rtf
SMS	=	me.sm
LIBS	=	me.lbn
PSOS	=	me.pso
EHFS	=	meehf.hts
MANLOG	=	man.log
#
# Build text files.
#
READTXT	=	readme.txt
FAQTXT	=	faq.txt
BUILDTXT=	build.txt
PATCHTXT=	patch.txt
CATMAN1=	me.1 ne.1 me.1.gz ne.1.gz
MISCTXT=	cygwin.txt	infolist.txt
#
# Define components
#
TXTS	=	$(READTXT) $(FAQTXT) $(BUILDTXT) $(PATCHTXT) $(MISCTXT)
#
RTFS	=	me.rtf me.hpj logo.bmp me.hhp
#
MEHTMZIP=	jasspa-mehtm-20$(MEYY)$(MEMM)$(MEDD).zip
MEHTMLTGZ=	jasspa-mehtml-20$(MEYY)$(MEMM)$(MEDD).tar.gz
#
MAN1	=	$(DOCDIR)m1cmd000.1 $(DOCDIR)m1cmd002.1
#
CMD2_000=	$(DOCDIR)m2cmd000.2 $(DOCDIR)m2cmd001.2 $(DOCDIR)m2cmd002.2\
		$(DOCDIR)m2cmd003.2 $(DOCDIR)m2cmd004.2 $(DOCDIR)m2cmd005.2\
		$(DOCDIR)m2cmd006.2 $(DOCDIR)m2cmd007.2 $(DOCDIR)m2cmd008.2\
		$(DOCDIR)m2cmd009.2
CMD2_010=	$(DOCDIR)m2cmd010.2 $(DOCDIR)m2cmd011.2 $(DOCDIR)m2cmd012.2\
		$(DOCDIR)m2cmd013.2 $(DOCDIR)m2cmd014.2 $(DOCDIR)m2cmd015.2\
		$(DOCDIR)m2cmd017.2 $(DOCDIR)m2cmd018.2\
		$(DOCDIR)m2cmd019.2
CMD2_020=	$(DOCDIR)m2cmd020.2 $(DOCDIR)m2cmd021.2 $(DOCDIR)m2cmd022.2\
		$(DOCDIR)m2cmd023.2 $(DOCDIR)m2cmd024.2 $(DOCDIR)m2cmd025.2\
		$(DOCDIR)m2cmd026.2 $(DOCDIR)m2cmd027.2 $(DOCDIR)m2cmd028.2\
		$(DOCDIR)m2cmd029.2
CMD2_030=	$(DOCDIR)m2cmd030.2 $(DOCDIR)m2cmd031.2 $(DOCDIR)m2cmd032.2\
		$(DOCDIR)m2cmd033.2 $(DOCDIR)m2cmd034.2 $(DOCDIR)m2cmd035.2\
		$(DOCDIR)m2cmd036.2 $(DOCDIR)m2cmd037.2 $(DOCDIR)m2cmd038.2\
		$(DOCDIR)m2cmd039.2
CMD2_040=	$(DOCDIR)m2cmd040.2 $(DOCDIR)m2cmd041.2 $(DOCDIR)m2cmd042.2\
		$(DOCDIR)m2cmd043.2 $(DOCDIR)m2cmd044.2 $(DOCDIR)m2cmd045.2\
		$(DOCDIR)m2cmd046.2 $(DOCDIR)m2cmd047.2 $(DOCDIR)m2cmd048.2\
		$(DOCDIR)m2cmd049.2
CMD2_050=	$(DOCDIR)m2cmd050.2 $(DOCDIR)m2cmd051.2 $(DOCDIR)m2cmd052.2\
		$(DOCDIR)m2cmd053.2 \
		$(DOCDIR)m2cmd056.2 $(DOCDIR)m2cmd057.2 $(DOCDIR)m2cmd058.2\
		$(DOCDIR)m2cmd059.2
CMD2_060=	$(DOCDIR)m2cmd060.2 $(DOCDIR)m2cmd061.2 $(DOCDIR)m2cmd062.2\
		$(DOCDIR)m2cmd063.2 $(DOCDIR)m2cmd064.2 $(DOCDIR)m2cmd065.2\
		$(DOCDIR)m2cmd066.2 $(DOCDIR)m2cmd067.2 $(DOCDIR)m2cmd068.2\
		$(DOCDIR)m2cmd069.2
CMD2_070=	$(DOCDIR)m2cmd070.2 $(DOCDIR)m2cmd071.2 $(DOCDIR)m2cmd072.2\
		$(DOCDIR)m2cmd073.2 $(DOCDIR)m2cmd074.2 $(DOCDIR)m2cmd075.2\
		$(DOCDIR)m2cmd076.2 $(DOCDIR)m2cmd077.2 $(DOCDIR)m2cmd078.2\
		$(DOCDIR)m2cmd079.2
CMD2_080=	$(DOCDIR)m2cmd080.2 $(DOCDIR)m2cmd081.2 $(DOCDIR)m2cmd082.2\
		$(DOCDIR)m2cmd083.2 $(DOCDIR)m2cmd084.2 $(DOCDIR)m2cmd085.2\
		$(DOCDIR)m2cmd086.2 $(DOCDIR)m2cmd087.2 $(DOCDIR)m2cmd088.2\
		$(DOCDIR)m2cmd089.2
CMD2_090=	$(DOCDIR)m2cmd090.2 $(DOCDIR)m2cmd091.2 $(DOCDIR)m2cmd092.2\
		$(DOCDIR)m2cmd093.2 $(DOCDIR)m2cmd094.2 $(DOCDIR)m2cmd095.2\
		$(DOCDIR)m2cmd096.2 $(DOCDIR)m2cmd097.2 $(DOCDIR)m2cmd098.2\
		$(DOCDIR)m2cmd099.2
CMD2_100=	$(DOCDIR)m2cmd100.2 $(DOCDIR)m2cmd101.2 $(DOCDIR)m2cmd102.2\
		$(DOCDIR)m2cmd103.2 $(DOCDIR)m2cmd104.2 $(DOCDIR)m2cmd105.2\
		$(DOCDIR)m2cmd106.2 $(DOCDIR)m2cmd107.2 $(DOCDIR)m2cmd108.2\
		$(DOCDIR)m2cmd109.2
CMD2_110=	$(DOCDIR)m2cmd110.2 $(DOCDIR)m2cmd111.2 $(DOCDIR)m2cmd112.2\
		$(DOCDIR)m2cmd113.2 $(DOCDIR)m2cmd114.2 $(DOCDIR)m2cmd115.2\
		$(DOCDIR)m2cmd116.2 $(DOCDIR)m2cmd117.2 $(DOCDIR)m2cmd118.2\
		$(DOCDIR)m2cmd119.2
CMD2_120=	$(DOCDIR)m2cmd120.2 $(DOCDIR)m2cmd121.2 $(DOCDIR)m2cmd122.2\
		$(DOCDIR)m2cmd123.2 $(DOCDIR)m2cmd124.2 $(DOCDIR)m2cmd125.2\
		$(DOCDIR)m2cmd126.2 $(DOCDIR)m2cmd127.2 $(DOCDIR)m2cmd128.2\
		$(DOCDIR)m2cmd129.2
CMD2_130=	$(DOCDIR)m2cmd130.2 $(DOCDIR)m2cmd131.2 $(DOCDIR)m2cmd132.2\
		$(DOCDIR)m2cmd133.2 $(DOCDIR)m2cmd134.2 $(DOCDIR)m2cmd135.2\
		$(DOCDIR)m2cmd136.2 $(DOCDIR)m2cmd137.2 $(DOCDIR)m2cmd138.2\
		$(DOCDIR)m2cmd139.2
CMD2_140=	$(DOCDIR)m2cmd140.2 $(DOCDIR)m2cmd141.2 $(DOCDIR)m2cmd142.2\
		$(DOCDIR)m2cmd143.2			$(DOCDIR)m2cmd145.2\
		$(DOCDIR)m2cmd146.2 $(DOCDIR)m2cmd147.2 $(DOCDIR)m2cmd148.2\
		$(DOCDIR)m2cmd149.2
CMD2_150=	$(DOCDIR)m2cmd150.2 $(DOCDIR)m2cmd151.2 $(DOCDIR)m2cmd152.2\
		$(DOCDIR)m2cmd153.2 $(DOCDIR)m2cmd154.2 $(DOCDIR)m2cmd155.2\
		$(DOCDIR)m2cmd156.2 $(DOCDIR)m2cmd157.2 $(DOCDIR)m2cmd158.2\
		$(DOCDIR)m2cmd159.2
CMD2_160=	$(DOCDIR)m2cmd160.2 $(DOCDIR)m2cmd161.2 $(DOCDIR)m2cmd162.2\
		$(DOCDIR)m2cmd163.2
#
CMD2_200=	$(DOCDIR)m2cmd200.2 $(DOCDIR)m2cmd201.2 $(DOCDIR)m2cmd202.2\
		$(DOCDIR)m2cmd203.2
#
NAR2_000=	$(DOCDIR)m2nar000.2 $(DOCDIR)m2nar001.2	$(DOCDIR)m2nar002.2 \
		$(DOCDIR)m2nar003.2 $(DOCDIR)m2nar004.2 $(DOCDIR)m2nar005.2 \
		$(DOCDIR)m2nar006.2 $(DOCDIR)m2nar007.2 $(DOCDIR)m2nar008.2 \
		$(DOCDIR)m2nar009.2
NAR2_010=	$(DOCDIR)m2nar010.2 $(DOCDIR)m2nar011.2 $(DOCDIR)m2nar012.2
#
MOD2_000=	$(DOCDIR)m2mod000.2 $(DOCDIR)m2mod001.2 \
		$(DOCDIR)m2mod003.2 $(DOCDIR)m2mod004.2 $(DOCDIR)m2mod005.2\
		$(DOCDIR)m2mod006.2 \
		$(DOCDIR)m2mod009.2
MOD2_010=	$(DOCDIR)m2mod010.2 $(DOCDIR)m2mod011.2 $(DOCDIR)m2mod012.2\
		$(DOCDIR)m2mod013.2 $(DOCDIR)m2mod014.2 \
		$(DOCDIR)m2mod016.2 $(DOCDIR)m2mod017.2 $(DOCDIR)m2mod018.2\
		$(DOCDIR)m2mod019.2
MOD2_020=	$(DOCDIR)m2mod020.2 $(DOCDIR)m2mod021.2 $(DOCDIR)m2mod022.2\
		$(DOCDIR)m2mod023.2 $(DOCDIR)m2mod024.2 $(DOCDIR)m2mod025.2\
		$(DOCDIR)m2mod029.2
MOD2_030=	$(DOCDIR)m2mod030.2 $(DOCDIR)m2mod031.2 $(DOCDIR)m2mod032.2
#
MAC3_000=	$(DOCDIR)m3mac000.3 $(DOCDIR)m3mac001.3 $(DOCDIR)m3mac002.3\
		$(DOCDIR)m3mac003.3 $(DOCDIR)m3mac004.3 $(DOCDIR)m3mac005.3\
		$(DOCDIR)m3mac006.3 $(DOCDIR)m3mac007.3 $(DOCDIR)m3mac008.3\
		$(DOCDIR)m3mac009.3
MAC3_010=	$(DOCDIR)m3mac010.3 $(DOCDIR)m3mac011.3 $(DOCDIR)m3mac012.3\
		$(DOCDIR)m3mac013.3 $(DOCDIR)m3mac014.3 $(DOCDIR)m3mac015.3\
		$(DOCDIR)m3mac016.3 $(DOCDIR)m3mac017.3 $(DOCDIR)m3mac018.3\
		$(DOCDIR)m3mac019.3
MAC3_020=	$(DOCDIR)m3mac020.3 $(DOCDIR)m3mac021.3 $(DOCDIR)m3mac022.3\
		$(DOCDIR)m3mac023.3 $(DOCDIR)m3mac024.3 $(DOCDIR)m3mac025.3\
		$(DOCDIR)m3mac026.3 $(DOCDIR)m3mac027.3 $(DOCDIR)m3mac028.3\
		$(DOCDIR)m3mac029.3
MAC3_030=	$(DOCDIR)m3mac030.3 $(DOCDIR)m3mac031.3 $(DOCDIR)m3mac032.3\
		$(DOCDIR)m3mac033.3 $(DOCDIR)m3mac034.3 $(DOCDIR)m3mac035.3\
		$(DOCDIR)m3mac036.3 $(DOCDIR)m3mac037.3 $(DOCDIR)m3mac038.3\
		$(DOCDIR)m3mac039.3
MAC3_040=	$(DOCDIR)m3mac040.3 $(DOCDIR)m3mac041.3 $(DOCDIR)m3mac042.3\
		$(DOCDIR)m3mac043.3 $(DOCDIR)m3mac044.3 $(DOCDIR)m3mac045.3\
		$(DOCDIR)m3mac046.3 $(DOCDIR)m3mac047.3 $(DOCDIR)m3mac048.3\
		$(DOCDIR)m3mac049.3
MAC3_050=	$(DOCDIR)m3mac050.3 $(DOCDIR)m3mac051.3 $(DOCDIR)m3mac052.3\
		$(DOCDIR)m3mac053.3 $(DOCDIR)m3mac054.3 $(DOCDIR)m3mac055.3\
		$(DOCDIR)m3mac056.3 $(DOCDIR)m3mac057.3 $(DOCDIR)m3mac058.3\
		$(DOCDIR)m3mac059.3
MAC3_060=	$(DOCDIR)m3mac060.3 $(DOCDIR)m3mac061.3 $(DOCDIR)m3mac062.3\
		$(DOCDIR)m3mac063.3 $(DOCDIR)m3mac064.3 $(DOCDIR)m3mac065.3\
		$(DOCDIR)m3mac066.3 $(DOCDIR)m3mac067.3 $(DOCDIR)m3mac068.3\
		$(DOCDIR)m3mac069.3
MAC3_070=	$(DOCDIR)m3mac070.3 $(DOCDIR)m3mac071.3 $(DOCDIR)m3mac072.3\
		$(DOCDIR)m3mac073.3 $(DOCDIR)m3mac074.3 $(DOCDIR)m3mac075.3\
		$(DOCDIR)m3mac076.3 $(DOCDIR)m3mac077.3 $(DOCDIR)m3mac078.3\
		$(DOCDIR)m3mac079.3
MAC3_080=	$(DOCDIR)m3mac080.3 $(DOCDIR)m3mac081.3 $(DOCDIR)m3mac082.3\
		$(DOCDIR)m3mac083.3 $(DOCDIR)m3mac084.3 $(DOCDIR)m3mac085.3\
		$(DOCDIR)m3mac086.3 $(DOCDIR)m3mac087.3 $(DOCDIR)m3mac088.3\
		$(DOCDIR)m3mac089.3
MAC3_090=	$(DOCDIR)m3mac090.3 $(DOCDIR)m3mac091.3 $(DOCDIR)m3mac092.3\
		$(DOCDIR)m3mac093.3 $(DOCDIR)m3mac094.3 $(DOCDIR)m3mac095.3\
		$(DOCDIR)m3mac096.3
# TODO: doc change-font-size, copy-file, delete-file & git interface
#
OSD3_000=	$(DOCDIR)m3osd000.3 $(DOCDIR)m3osd001.3 $(DOCDIR)m3osd002.3\
		$(DOCDIR)m3osd003.3 $(DOCDIR)m3osd004.3 $(DOCDIR)m3osd005.3\
		$(DOCDIR)m3osd006.3 $(DOCDIR)m3osd007.3 $(DOCDIR)m3osd008.3\
		$(DOCDIR)m3osd009.3
OSD3_010=	$(DOCDIR)m3osd010.3 $(DOCDIR)m3osd011.3 $(DOCDIR)m3osd012.3\
		$(DOCDIR)m3osd013.3 $(DOCDIR)m3osd014.3 $(DOCDIR)m3osd015.3\
		$(DOCDIR)m3osd016.3 $(DOCDIR)m3osd017.3
#
FCL3_000=	$(DOCDIR)m3fcl001.3 $(DOCDIR)m3fcl002.3 $(DOCDIR)m3fcl003.3\
		$(DOCDIR)m3fcl004.3 $(DOCDIR)m3fcl005.3 $(DOCDIR)m3fcl006.3\
		$(DOCDIR)m3fcl007.3 $(DOCDIR)m3fcl008.3 $(DOCDIR)m3fcl009.3
#
FCL3_010=	$(DOCDIR)m3fcl010.3 $(DOCDIR)m3fcl011.3 $(DOCDIR)m3fcl012.3
#
FIL4_000=	$(DOCDIR)m4fil000.4 $(DOCDIR)m4fil001.4 $(DOCDIR)m4fil002.4\
		$(DOCDIR)m4fil003.4 $(DOCDIR)m4fil004.4 $(DOCDIR)m4fil005.4\
		$(DOCDIR)m4fil006.4 $(DOCDIR)m4fil007.4 $(DOCDIR)m4fil008.4\
		$(DOCDIR)m4fil009.4
FIL4_010=	$(DOCDIR)m4fil010.4 $(DOCDIR)m4fil011.4 $(DOCDIR)m4fil012.4\
		$(DOCDIR)m4fil013.4 $(DOCDIR)m4fil014.4 $(DOCDIR)m4fil015.4\
		$(DOCDIR)m4fil016.4 $(DOCDIR)m4fil017.4 $(DOCDIR)m4fil018.4\
		$(DOCDIR)m4fil019.4
FIL4_020=	$(DOCDIR)m4fil020.4 $(DOCDIR)m4fil021.4 $(DOCDIR)m4fil022.4\
		$(DOCDIR)m4fil023.4 $(DOCDIR)m4fil024.4 $(DOCDIR)m4fil025.4\
		$(DOCDIR)m4fil026.4 $(DOCDIR)m4fil027.4 $(DOCDIR)m4fil028.4\
		$(DOCDIR)m4fil029.4
FIL4_030=	$(DOCDIR)m4fil030.4 $(DOCDIR)m4fil031.4 $(DOCDIR)m4fil032.4\
		$(DOCDIR)m4fil033.4 $(DOCDIR)m4fil034.4 $(DOCDIR)m4fil035.4\
		$(DOCDIR)m4fil036.4 $(DOCDIR)m4fil037.4 $(DOCDIR)m4fil038.4
#
VAR5_000=	$(DOCDIR)m5var000.5 $(DOCDIR)m5var001.5 $(DOCDIR)m5var002.5\
		$(DOCDIR)m5var003.5 $(DOCDIR)m5var004.5 $(DOCDIR)m5var005.5\
		$(DOCDIR)m5var006.5 $(DOCDIR)m5var007.5 $(DOCDIR)m5var008.5\
		$(DOCDIR)m5var009.5
VAR5_010=	$(DOCDIR)m5var010.5 $(DOCDIR)m5var011.5 $(DOCDIR)m5var012.5\
		$(DOCDIR)m5var013.5 $(DOCDIR)m5var014.5 $(DOCDIR)m5var015.5\
		$(DOCDIR)m5var016.5 \
		$(DOCDIR)m5var019.5
VAR5_020=	$(DOCDIR)m5var020.5 $(DOCDIR)m5var021.5 $(DOCDIR)m5var022.5\
		$(DOCDIR)m5var023.5 $(DOCDIR)m5var024.5 $(DOCDIR)m5var025.5\
		$(DOCDIR)m5var026.5 $(DOCDIR)m5var027.5 $(DOCDIR)m5var028.5\
		$(DOCDIR)m5var029.5
VAR5_030=	$(DOCDIR)m5var030.5 $(DOCDIR)m5var031.5 $(DOCDIR)m5var032.5\
		$(DOCDIR)m5var033.5 $(DOCDIR)m5var034.5 $(DOCDIR)m5var035.5\
		$(DOCDIR)m5var036.5 $(DOCDIR)m5var037.5 $(DOCDIR)m5var038.5\
		$(DOCDIR)m5var039.5
VAR5_040=	$(DOCDIR)m5var040.5 $(DOCDIR)m5var041.5 $(DOCDIR)m5var042.5\
		$(DOCDIR)m5var043.5 $(DOCDIR)m5var044.5 $(DOCDIR)m5var045.5\
		$(DOCDIR)m5var046.5 $(DOCDIR)m5var047.5 $(DOCDIR)m5var048.5\
		$(DOCDIR)m5var049.5
VAR5_050=	$(DOCDIR)m5var050.5 $(DOCDIR)m5var051.5 $(DOCDIR)m5var052.5\
		$(DOCDIR)m5var053.5 $(DOCDIR)m5var054.5 $(DOCDIR)m5var055.5\
		$(DOCDIR)m5var056.5 $(DOCDIR)m5var057.5 $(DOCDIR)m5var058.5\
		$(DOCDIR)m5var059.5
VAR5_060=	$(DOCDIR)m5var060.5 $(DOCDIR)m5var061.5 $(DOCDIR)m5var062.5\
		$(DOCDIR)m5var063.5 $(DOCDIR)m5var064.5 $(DOCDIR)m5var065.5\
		$(DOCDIR)m5var066.5 $(DOCDIR)m5var067.5 $(DOCDIR)m5var068.5\
		$(DOCDIR)m5var069.5
VAR5_070=	$(DOCDIR)m5var070.5 $(DOCDIR)m5var071.5 $(DOCDIR)m5var072.5\
		$(DOCDIR)m5var073.5 $(DOCDIR)m5var074.5 $(DOCDIR)m5var075.5\
		$(DOCDIR)m5var076.5 $(DOCDIR)m5var077.5 $(DOCDIR)m5var078.5\
		$(DOCDIR)m5var079.5
VAR5_080=	$(DOCDIR)m5var080.5 $(DOCDIR)m5var081.5 $(DOCDIR)m5var082.5\
		$(DOCDIR)m5var083.5 $(DOCDIR)m5var084.5 $(DOCDIR)m5var085.5\
		$(DOCDIR)m5var086.5 $(DOCDIR)m5var087.5 $(DOCDIR)m5var088.5\
		$(DOCDIR)m5var089.5
VAR5_090=	$(DOCDIR)m5var090.5 $(DOCDIR)m5var091.5 $(DOCDIR)m5var092.5 \
		$(DOCDIR)m5var093.5 $(DOCDIR)m5var094.5
#
FIL8_000=	$(DOCDIR)m8fil000.8 $(DOCDIR)m8fil001.8 $(DOCDIR)m8fil002.8\
		$(DOCDIR)m8fil003.8 $(DOCDIR)m8fil004.8 $(DOCDIR)m8fil005.8\
		$(DOCDIR)m8fil007.8 $(DOCDIR)m8fil008.8
#
TYP9_000=	$(DOCDIR)m9typ000.9 $(DOCDIR)m9typ001.9 $(DOCDIR)m9typ002.9\
		$(DOCDIR)m9typ003.9 $(DOCDIR)m9typ004.9 $(DOCDIR)m9typ005.9\
		$(DOCDIR)m9typ006.9 $(DOCDIR)m9typ007.9 $(DOCDIR)m9typ008.9\
		$(DOCDIR)m9typ009.9
TYP9_010=	$(DOCDIR)m9typ010.9 $(DOCDIR)m9typ011.9 $(DOCDIR)m9typ012.9\
		$(DOCDIR)m9typ013.9 $(DOCDIR)m9typ014.9 $(DOCDIR)m9typ015.9\
		$(DOCDIR)m9typ016.9 $(DOCDIR)m9typ017.9 $(DOCDIR)m9typ018.9\
		$(DOCDIR)m9typ019.9
TYP9_020=	$(DOCDIR)m9typ020.9 $(DOCDIR)m9typ021.9 $(DOCDIR)m9typ022.9\
		$(DOCDIR)m9typ023.9 $(DOCDIR)m9typ024.9 $(DOCDIR)m9typ025.9\
		$(DOCDIR)m9typ026.9 $(DOCDIR)m9typ027.9 $(DOCDIR)m9typ028.9\
		$(DOCDIR)m9typ029.9
TYP9_030=	$(DOCDIR)m9typ030.9 $(DOCDIR)m9typ031.9 $(DOCDIR)m9typ032.9\
		$(DOCDIR)m9typ033.9 $(DOCDIR)m9typ034.9 $(DOCDIR)m9typ035.9\
		$(DOCDIR)m9typ036.9 $(DOCDIR)m9typ037.9 $(DOCDIR)m9typ038.9\
		$(DOCDIR)m9typ039.9
TYP9_040=	$(DOCDIR)m9typ040.9 $(DOCDIR)m9typ041.9 $(DOCDIR)m9typ042.9\
		$(DOCDIR)m9typ043.9 $(DOCDIR)m9typ044.9 $(DOCDIR)m9typ045.9\
		$(DOCDIR)m9typ046.9 $(DOCDIR)m9typ047.9
#
TNIS	=	me.tni

TEMPSMS	=	cmd2_000.sm	cmd2_010.sm	cmd2_020.sm	cmd2_030.sm \
		cmd2_040.sm	cmd2_050.sm	cmd2_060.sm	cmd2_070.sm \
		cmd2_080.sm	cmd2_090.sm	cmd2_100.sm	cmd2_110.sm \
		cmd2_120.sm	cmd2_130.sm	cmd2_140.sm	cmd2_150.sm \
		cmd2_160.sm	cmd2_200.sm \
		nar2_000.sm	nar2_010.sm \
		mod2_000.sm	mod2_010.sm	mod2_020.sm	mod2_030.sm \
		mac3_000.sm	mac3_010.sm	mac3_020.sm	mac3_030.sm \
		mac3_040.sm	mac3_050.sm	mac3_060.sm	mac3_070.sm \
		mac3_080.sm	mac3_090.sm \
		osd3_000.sm	osd3_010.sm \
		fcl3_000.sm	fcl3_010.sm \
		fil4_000.sm	fil4_010.sm	fil4_020.sm	fil4_030.sm \
		var5_000.sm	var5_010.sm	var5_020.sm	var5_030.sm \
		var5_040.sm	var5_050.sm	var5_060.sm	var5_070.sm \
		var5_080.sm	var5_090.sm \
		fil8_000.sm \
		typ9_000.sm	typ9_010.sm	typ9_020.sm	typ9_030.sm \
		typ9_040.sm \
		faq.2

all:	$(HTSS) $(HLPS) $(SMS) $(EHFS) $(TXTS) $(CATMAN1)
#
# Release
#
RELWWWDOCDIR=	$(WWWRELDIR)/doc
RELRTFS=	$(RTFS:%=$(RTFRELDIR)/%)
RELZIPS=	$(MEHTMZIP:%=$(WWWRELDIR)/%)
RELTARS=	$(MEHTMLTGZ:%=$(WWWRELDIR)/%)
RELTXTS=	$(TXTS:%=$(RELWWWDOCDIR)/%) $(TXTS:%=$(MERELDIR)/%) \
		$(TXTS:%=$(SRCRELDIR)/%)
RELEHF=		$(JASMACDIR)/me.ehf
RELCAT1=	$(CATMAN1:%=$(WWWRELDIR)/%)
RELEASE=	$(RELRTFS)	$(RELZIPS)	$(RELTARS)	$(RELTXTS) \
		$(RELEHF)	$(RELCAT1)

release:	$(RELEASE)

# Windows RTF
$(RELRTFS):	$(RTFS)
		$(MKDIR) $(@D)
		$(INSTALL_FIL) $(@F) $(@D)
# Zips
$(RELZIPS):	$(MEHTMZIP)
		$(MKDIR) $(@D)
		$(INSTALL_FIL) $(@F) $(@D)
# Tars
$(RELTARS):	$(MEHTMLTGZ)
		$(MKDIR) $(@D)
		$(INSTALL_FIL) $(@F) $(@D)
# Txts
$(RELTXTS):	$(TXTS)
		$(MKDIR) $(@D)
		$(INSTALL_FIL) $(@F) $(@D)
# Ehf
$(RELEHF):	me.ehf
		$(MKDIR) $(@D)
		$(INSTALL_FIL) $(@F) $(@D)
# Catman pages
$(RELCAT1):	$(CATMAN1)
		$(MKDIR) $(@D)
		$(INSTALL_FIL) $(@F) $(@D)
#
clean::
	$(RM) *.sm
	$(RM) $(MANLOG)
	$(RM) me.err
	$(RM) me.lbn
	$(RM) me.gid
#
spotless:: clean
	$(RM) *~
	$(RM) core
	$(RM) *.log
	$(RM) tags
##############################################################################
#
# Build the main components.
#
##############################################################################
# Commands
cmd2_000.sm:	$(CMD2_000)
	$(SUPERMAN) -o $@ $(CMD2_000)
cmd2_010.sm:	$(CMD2_010)
	$(SUPERMAN) -o $@ $(CMD2_010)
cmd2_020.sm:	$(CMD2_020)
	$(SUPERMAN) -o $@ $(CMD2_020)
cmd2_030.sm:	$(CMD2_030)
	$(SUPERMAN) -o $@ $(CMD2_030)
cmd2_040.sm:	$(CMD2_040)
	$(SUPERMAN) -o $@ $(CMD2_040)
cmd2_050.sm:	$(CMD2_050)
	$(SUPERMAN) -o $@ $(CMD2_050)
cmd2_060.sm:	$(CMD2_060)
	$(SUPERMAN) -o $@ $(CMD2_060)
cmd2_070.sm:	$(CMD2_070)
	$(SUPERMAN) -o $@ $(CMD2_070)
cmd2_080.sm:	$(CMD2_080)
	$(SUPERMAN) -o $@ $(CMD2_080)
cmd2_090.sm:	$(CMD2_090)
	$(SUPERMAN) -o $@ $(CMD2_090)
cmd2_100.sm:	$(CMD2_100)
	$(SUPERMAN) -o $@ $(CMD2_100)
cmd2_110.sm:	$(CMD2_110)
	$(SUPERMAN) -o $@ $(CMD2_110)
cmd2_120.sm:	$(CMD2_120)
	$(SUPERMAN) -o $@ $(CMD2_120)
cmd2_130.sm:	$(CMD2_130)
	$(SUPERMAN) -o $@ $(CMD2_130)
cmd2_140.sm:	$(CMD2_140)
	$(SUPERMAN) -o $@ $(CMD2_140)
cmd2_150.sm:	$(CMD2_150)
	$(SUPERMAN) -o $@ $(CMD2_150)
cmd2_160.sm:	$(CMD2_160)
	$(SUPERMAN) -o $@ $(CMD2_160)
cmd2_200.sm:	$(CMD2_200)
	$(SUPERMAN) -o $@ $(CMD2_200)
# Modes
mod2_000.sm:	$(MOD2_000)
	$(SUPERMAN) -o $@ $(MOD2_000)
mod2_010.sm:	$(MOD2_010)
	$(SUPERMAN) -o $@ $(MOD2_010)
mod2_020.sm:	$(MOD2_020)
	$(SUPERMAN) -o $@ $(MOD2_020)
mod2_030.sm:	$(MOD2_030)
	$(SUPERMAN) -o $@ $(MOD2_030)
# Macros
mac3_000.sm:	$(MAC3_000)
	$(SUPERMAN) -o $@ $(MAC3_000)
mac3_010.sm:	$(MAC3_010)
	$(SUPERMAN) -o $@ $(MAC3_010)
mac3_020.sm:	$(MAC3_020)
	$(SUPERMAN) -o $@ $(MAC3_020)
mac3_030.sm:	$(MAC3_030)
	$(SUPERMAN) -o $@ $(MAC3_030)
mac3_040.sm:	$(MAC3_040)
	$(SUPERMAN) -o $@ $(MAC3_040)
mac3_050.sm:	$(MAC3_050)
	$(SUPERMAN) -o $@ $(MAC3_050)
mac3_060.sm:	$(MAC3_060)
	$(SUPERMAN) -o $@ $(MAC3_060)
mac3_070.sm:	$(MAC3_070)
	$(SUPERMAN) -o $@ $(MAC3_070)
mac3_080.sm:	$(MAC3_080)
	$(SUPERMAN) -o $@ $(MAC3_080)
mac3_090.sm:	$(MAC3_090)
	$(SUPERMAN) -o $@ $(MAC3_090)
# OSD
osd3_000.sm:	$(OSD3_000)
	$(SUPERMAN) -o $@ $(OSD3_000)
osd3_010.sm:	$(OSD3_010)
	$(SUPERMAN) -o $@ $(OSD3_010)
#
fcl3_000.sm:	$(FCL_000)
	$(SUPERMAN) -o $@ $(FCL3_000)
fcl3_010.sm:	$(FCL_010)
	$(SUPERMAN) -o $@ $(FCL3_010)
# File definitions
fil4_000.sm:	$(FIL4_000)
	$(SUPERMAN) -o $@ $(FIL4_000)
fil4_010.sm:	$(FIL4_010)
	$(SUPERMAN) -o $@ $(FIL4_010)
fil4_020.sm:	$(FIL4_020)
	$(SUPERMAN) -o $@ $(FIL4_020)
fil4_030.sm:	$(FIL4_030)
	$(SUPERMAN) -o $@ $(FIL4_030)
# Variables
var5_000.sm:	$(VAR5_000)
	$(SUPERMAN) -o $@ $(VAR5_000)
var5_010.sm:	$(VAR5_010)
	$(SUPERMAN) -o $@ $(VAR5_010)
var5_020.sm:	$(VAR5_020)
	$(SUPERMAN) -o $@ $(VAR5_020)
var5_030.sm:	$(VAR5_030)
	$(SUPERMAN) -o $@ $(VAR5_030)
var5_040.sm:	$(VAR5_040)
	$(SUPERMAN) -o $@ $(VAR5_040)
var5_050.sm:	$(VAR5_050)
	$(SUPERMAN) -o $@ $(VAR5_050)
var5_060.sm:	$(VAR5_060)
	$(SUPERMAN) -o $@ $(VAR5_060)
var5_070.sm:	$(VAR5_070)
	$(SUPERMAN) -o $@ $(VAR5_070)
var5_080.sm:	$(VAR5_080)
	$(SUPERMAN) -o $@ $(VAR5_080)
var5_090.sm:	$(VAR5_090)
	$(SUPERMAN) -o $@ $(VAR5_090)
# Files
fil8_000.sm:	$(FIL8_000)
	$(SUPERMAN) -o $@ $(FIL8_000)
# Types
typ9_000.sm:	$(FIL9_000)
	$(SUPERMAN) -o $@ $(TYP9_000)
typ9_010.sm:	$(FIL9_010)
	$(SUPERMAN) -o $@ $(TYP9_010)
typ9_020.sm:	$(FIL9_020)
	$(SUPERMAN) -o $@ $(TYP9_020)
typ9_030.sm:	$(FIL9_030)
	$(SUPERMAN) -o $@ $(TYP9_030)
typ9_040.sm:	$(FIL9_040)
	$(SUPERMAN) -o $@ $(TYP9_040)
# Narratives
nar2_000.sm:	$(NAR2_000)
	$(SUPERMAN) -o $@ $(NAR2_000)
nar2_010.sm:	$(NAR2_010)
	$(SUPERMAN) -o $@ $(NAR2_010)
# Superman file
me.sm: $(TEMPSMS) $(TNIS) $(MAN1)
	$(SUPERMAN) -o $@ $(TNIS) $(MAN1) $(TEMPSMS)
clean::
	$(RM) *.sm
# Zip 8.3 HTML (.htm) archive
$(MEHTMZIP): me.hts
	$(RMDIR) htm
	$(MKDIR) htm
	$(MKDIR) htm$(pc)me
	cd htm$(sc) $(HTS2HTML) -l .htm ..$(pc)me.hts
	cd htm$(sc) $(ZIP) -r mehtm me.htm me
	$(CP) htm$(pc)mehtm.zip $@
	$(RMDIR) htm
# Microsoft project file.
me.hhp:	me.hts
	$(RMDIR) htm
	$(MKDIR) htm
	$(MKDIR) htm$(pc)me
	cd htm$(sc) $(HTS2HTML) -l .htm ..$(pc)me.hts
	echo "[OPTIONS]" > me.hhp
	echo "Compatibility=1.1 or later" >> me.hhp
	echo "Compiled file=me.chm" >> me.hhp
	echo "Default topic=me.htm" >> me.hhp
	echo "Display compile progress=Yes" >> me.hhp
	echo "Language=0x409 English (United States)" >> me.hhp
	echo "Title=JASSPA MicroEmacs Help" >> me.hhp
	echo "" >> me.hhp
	echo "[FILES]" >> me.hhp
	(cd htm$(sc) find . -type f -print |  sed -e "s/^\\.\\///g" -e "s/\\//\\\\/g" >> ../me.hhp)
	echo "" >> me.hhp
	echo "[INFOTYPES]" >> me.hhp
	$(RMDIR) htm
clean::
	$(RMDIR) htm
	$(RM) $(MEHTMZIP)
	$(RM) me.hhp
# Tar 8.4 HTML (.html) archive
$(MEHTMLTGZ): me.hts
	$(RMDIR) html
	$(MKDIR) html
	$(MKDIR) html$(pc)me
	cd html$(sc) $(HTS2HTML) -l .html ..$(pc)me.hts
	cd html$(sc) $(TAR) cvf mehtml.tar me.html me
	cd html$(sc) $(GZIP) mehtml.tar
	$(CP) html$(pc)mehtml.tar.gz $@
	$(RMDIR) html
clean::
	$(RMDIR) html
	$(RM) $(MEHTMLTGZ)
#
# Build the txt readme files.
#
$(READTXT): m2nar001.2 m2nar003.2 m2nar002.2
	    $(DROFF) -l10000 -c JASSPA -p -o $@ m2nar001.2 m2nar003.2 m2nar002.2
clean::
	$(RM) $(READTXT)
#
# Build the nroff pages
#
me.1: m1cmd000.1 $(TNIS) tmac.ad
	$(SED) -e "s/so me.tni/\\\\\" Removed definition file inclusion/g" tmac.ad me.tni m1cmd000.1 > $@
ne.1: m1cmd002.1 $(TNIS) tmac.ad
	$(SED) -e "s/so me.tni/\\\\\" Removed definition file inclusion/g" tmac.ad me.tni m1cmd002.1 > $@
#
# Build the catman pages
#
me.1.gz: m1cmd000.1 $(TNIS)
	    $(DROFF) -c JASSPA -o catme.1 m1cmd000.1
	    $(GZIP) -c -n catme.1 > $@
	    $(RM) catme.1
ne.1.gz: m1cmd002.1 $(TNIS)
	    $(DROFF) -c JASSPA -o catne.1 m1cmd002.1
	    $(GZIP) -c -n catne.1 > $@
	    $(RM) catne.1
clean::
	$(RM) me.1
	$(RM) ne.1
	$(RM) me.1.gz
	$(RM) ne.1.gz
	$(RM) catme.1
	$(RM) catne.1
$(BUILDTXT): m2nar007.2
	    $(DROFF) -l10000 -c JASSPA -p -o $@ m2nar007.2
clean::
	$(RM) $(BUILDTXT)
$(FAQTXT):  faq.2
	    $(DROFF) -l10000 -c JASSPA -p -o $@ faq.2
clean::
	$(RM) $(FAQTXT)
$(PATCHTXT): m2nar009.2
	    $(DROFF) -l10000 -c JASSPA -p -o $@ m2nar009.2
clean::
	$(RM) $(PATCHTXT)
# Build the local index page.
me.0: me.sm me.nrs
	$(NRSEARCH) -E $(MANLOG) -d -o $@ -n me.nrs me.sm
clean::
	$(RM) me.0
# Build symbol library
me.lbn: me.sm me.0
	$(NRAR) -E $(MANLOG) -M me me.0 me.sm
clean::
	$(RM) me.lbn
# Build HTML archive
me.hts: me.sm me.0 me.lbn me.tni forward.lbn logo.png
	$(NR2HTML) -E $(MANLOG)			\
		   -c JASSPA			\
		   -x -M me			\
		   -n me			\
		   -H me			\
		   -L. -lme -l$(DOCDIR)forward	\
		   -tCommands:CommandGlossary	\
		   -tVariables:VariableGlossary	\
		   -tMacro-Dev:MacroGlossary	\
		   -tGlossary:Glossary		\
		   me.sm me.0
	$(HTS) -a $@ -E $(MANLOG) -s me/logo -b logo.png
clean::
	$(RM) me.hts
# Build Windows Help File.
me.hlp: $(HC31) me.hpj
	$(HC31) me.hpj
me.rtf: me.sm me.0 me.lbn me.tni forward.lbn me.hpj logo.bmp
	$(NR2RTF)  -E $(MANLOG)			\
		   -c JASSPA			\
		   -x -M me			\
		   -n me			\
		   -H me			\
		   -L. -lme -l$(DOCDIR)forward	\
		   -tHome:me			\
		   -tCommands:CommandGlossary   \
		   -tVariables:VariableGlossary \
		   -tMacro-Dev:MacroGlossary    \
		   -tGlossary:Glossary		\
		    me.sm me.0
clean::
	$(RM) me.rtf
# Build MicroEmacs EHF file.
me.ehf: meehf.hts
	$(RMDIR) ehf
	$(MKDIR) ehf
	$(MKDIR) ehf$(pc)me
	$(RM) ehf$(pc)me$(pc)*.htm
	$(RM) ehf$(pc)me$(pc)me.ehf
	cd ehf$(sc) $(HTS2HTML) -l .htm ..$(pc)meehf.hts
	$(CP) ehf$(pc)me.htm ehf$(pc)me$(pc)1.htm
	cd ehf$(pc)me$(sc) $(ME) -P "@ehftools" *.htm
	$(CP) ehf$(pc)me$(pc)me.ehf .
	#$(RMDIR) ehf
clean::
	$(RMDIR) ehf
	$(RM) me.ehf
# HTML Archive
meehf.hts: me.sm me.0 me.lbn me.tni forward.lbn logo.png
	$(NR2HTML) -E $(MANLOG)				\
		   -b -c JASSPA				\
		   -x -M me				\
		   -n me -o meehf.hts			\
		   -H me				\
		   -L. -lme -l$(DOCDIR)forward		\
		   -t Commands:CommandGlossary		\
		   -t Variables:VariableGlossary	\
		   -t Macro-Dev:MacroGlossary		\
		   -t Glossary:Glossary			\
		    me.sm me.0
	$(HTS) -a $@ -E $(MANLOG) -b logo.gif
	- $(RM) *.so
clean::
	$(RM) meehf.hts
# Build the postscript print job ordering files.
me.pso:	me.sm me.tni
		$(NRORDER) $(NROFLAGS) -z -o $@ me.sm
clean::
	$(RM) me.pso
