.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Thu Jul 16 23:13:14 1998
.\"
.Id $Id: m2cmd025.2,v 2.5 2002-01-11 21:58:42 jon Exp $
.Im MicroEmacs command|registry
.so me.tni
.TH list-registry 2
.XI list-registry - "Display the registry in a buffer"
.SH NAME
list-registry \- Display the registry in a buffer
.Me $a
.SH SYNOPSIS
.na
.B list-registry
.ad
.SH DESCRIPTION
.B list-registry
lists the contents of the registry in the a buffer in a hierarchical format.
The key name and any associated string is shown as a hierarchical tree.
.PP
The registry listing is generated in the buffer "\fC*registry*\fR".
.SH "SEE ALSO"
.na
.Ht read-registry 2 ,
.Ht erf 8 .
.ad
.FH
