.\" -*- nroff -*-
.Id $Id: m2cmd016.2,v 2.4 2001-12-18 16:52:52 jon Exp $
.Im MicroEmacs command|file
.so me.tni
.TH change-directory 2
.XI change-directory - "[\\fB\*(cX\*cd\\fR] Change the current working directory"
.SH NAME
change-directory \- Change the current working directory
.Me $a
.SH SYNOPSIS
.na
.B change-directory
"\fIdir-name\fR" 
(\fB\*(cX\*cd\fR)
.ad
.SH DESCRIPTION
.B change-directory
changes the current working  directory to \fIdir-name\fR, on certain platforms
(\s-1MS-DOS\s0)  this can also  change the  current  drive. This  command  is
largely redundant as any shell command automatically inherits the directory of
the current buffer's file.
.SH "SEE ALSO"
.na
.Ht change-file-name 2 .
.ad
.FH
