.\" -*- nroff -*-
.Id $Id: m2cmd158.2,v 1.3 2000-11-18 01:47:12 jon Exp $
.Im MicroEmacs command|file
.so me.tni
.TH copy-file 2
.XI copy-file \- "Copy, move or delete a file"
.SH NAME
copy-file \- Copy, move or delete a file
.Me $a
.SH SYNOPSIS
.na
.I n
.B copy-file
"\fIfrom-file-name\fR" [ "\fIto-file-name\fR" ]
.ad
.SH DESCRIPTION
.B copy-file
copies the source file  \fIfrom-file-name\fR to \fIto-file-name\fR, the source
file  must be a  single  file,  i.e. no  wild-cards  and not a  directory.  If
\fIto-file-name\fR  is a directory  the base name of  \fIfrom-file-name\fR  is
automatically appended.
.PP
The  argument  \fIn\fR  can  be  used  to  change  the  default  behavior  of
copy-file, \fIn\fR is a bit based flag where:-
.IP \fB0x01\fR
Enables  validity  checks  (default).  These include a check that the proposed
file does not already exist, if so  confirmation  of writing is requested from
the user.  Also  \*(mS  checks  all  other  current  buffers  for one with the
proposed file name, if found, again  confirmation  is requested.  Without this
flag the command will always succeed wherever possible.
.IP \fB0x02\fR
Creates a backup of the  \fIto-file-name\fR  if it already exists. When moving
or deleting the source file, the source file is also backed-up.
.IP \fB0x04\fR
When this bit is set the command  functionality is changed to delete-file, the
specified  \fIfrom-file-name\fR is deleted and the \fIto-file-name\fR argument
is not  required. If flag  \fB0x01\fR is set then the user is prompted  before
the file is removed and if bit  \fB0x02\fR is set a backup of the file is made
first. Bit \fB0x08\fR is ignored.    
.IP \fB0x08\fR
When this bit is set the command  functionality is changed to move-file, the
specified   \fIfrom-file-name\fR   is  moved  to  \fIto-file-name\fR.  If  bit
\fB0x02\fR is set a backup of the source file is also made.
.SH NOTES
\fBhttp\fR  files are not  supported  except as the source file when  copying.
\fBftp\fR files are fully supported with the restriction  that the from and to
files cannot both be url (http or ftp) files.
.PP
The command is used by
.Ht file-browser 3
and
.Ht ftp 3
which provides an easy to use interfaces for file manipulation.
.SH "SEE ALSO"
.na
.Ht file-browser 3 ,
.Ht ftp 3 ,
.Ht find-file 2 ,
.Ht write-buffer 2 .
.ad
.FH
