.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd152.2,v 2.6 2002-10-16 22:28:04 jon Exp $
.Im MicroEmacs command|window
.so me.tni
.TH change-window-width 2
.XI change-window-width \- "Change the width of the current window"
.XI grow-window-horizontally \- "Enlarge current window horizontally (relative)"
.XI shrink-window-horizontally \- "Shrink current window horizontally (relative)"
.XI resize-window-horizontally \- "Resize current window horizontally (absolute)"
.SH NAME
.Me "|change-window-width"
change-window-width \- Change the width of the current window
.br
.Me "|grow-window-horizontally"
grow-window-horizontally \- Enlarge current window horizontally (relative)
.br
.Me "|shrink-window-horizontally"
shrink-window-horizontally \- Shrink current window horizontally (relative)
.br
.Me "|resize-window-horizontally"
resize-window-horizontally \- Resize current window horizontally (absolute)
.Me $a
.SH SYNOPSIS
.na
\fIn\fR \fBchange-window-width\fR [ "\fIwidth\fR" ]
.sp
\fIn\fR \fBgrow-window-horizontally\fR
.br
\fIn\fR \fBshrink-window-horizontally\fR
.br
\fIn\fR \fBresize-window-horizontally\fR
.ad
.SH DESCRIPTION
\fBchange-window-width\fR  changes  the width of the  current  window,  if the
numeric  argument \fIn\fR is given then the window width is changed by \fIn\fR
characters.  If  \fIn\fR is not  specified  the user is  prompted  for the new
\fIwidth\fR  and the window  width will be changed to this value. The  command
aborts if the requested  size cannot be achieved (the window becomes too small
or a neighbouring does).
.SH EXAMPLE
Refer to  \fCmouse.emf\fR  for an example of window  growth using the mouse to
manipulate the size of the windows.
.SH NOTES
Commands  \fBgrow-window-horizontally\fR,   \fBshrink-window-horizontally\fR
and    \fBresize-window-horizontally\fR    were    replaced    by   the   new
\fBchange-window-width\fR   command  in  April  2002.   Following   are  macro
implementations of the old commands:
.Me $emf-scheme
.CS
define-macro grow-window-horizontally
    @# change-window-width
!emacro

define-macro shrink-window-horizontally
    &neg @# change-window-width
!emacro

define-macro resize-window-horizontally
    !if &not @?
        !abort
    !endif
    change-window-width @#
!emacro
.CE 0
.Me $ehf-scheme
.SH "SEE ALSO"
.na
.Ht change-window-depth 2 ,
.Ht resize-all-windows 2 ,
.Ht split-window-horizontally 2 .
.ad
.FH
