.\" -*- nroff -*-
.Id $Id: m2cmd144.2,v 2.3 2001-12-06 00:04:31 jon Exp $
.Im MicroEmacs command|scuts
.so me.tni
.TH save-history 2
.XI save-history - "Write history information to history file"
.SH NAME
save-history \- Write history information to history file
.Me $a
.SH SYNOPSIS
.na
.I n
.B save-history
"\fIhist-file\fR"
.ad
.SH DESCRIPTION
.B save-history
writes out \*(mE's current  history  information  into the given history file.
.PP
The command
.Ht read-history 2
can set a default  history  file in which  case the  history is  automatically
written  out to this  file if an  argument  of zero is given;  the user is not
prompted for a file. \*(mE  automatically  tries to write the default  history
whenever it is exited.
.SH NOTES
The history information is saved in a registry format file (see
.Ht erf 8 ).
Reference should be made to the notes included in
.Ht erf 8
as to how the  history  file may be  edited  and  effected  in the same  \*(mE
session.
.SH "SEE ALSO"
.na
.Ht erf 8 ,
.Ht read-history 2 .
.ad
.FH
