.\" -*- nroff -*-
.Id $Id: m2cmd130.2,v 2.5 2001-12-20 17:29:48 jon Exp $
.Im MicroEmacs command|file
.so me.tni
.TH suspend-emacs 2
.XI suspend-emacs - "Suspend editor and place in background"
.SH NAME
suspend-emacs \- Suspend editor and place in background
.Me $a
.SH SYNOPSIS
.na
.B suspend-emacs
.ad
.SH PLATFORM
Supported   on  UNIX   platforms  -   \fIirix\fR,   \fIhpux\fR,   \fIsunos\fR,
\fIfreebsd\fR or \fIlinux\fR.
.SH DESCRIPTION
.B suspend-emacs
suspends the editing processor and puts it into the background. The "\fIfg\fR"
command restarts \*(mE.
.SH "SEE ALSO"
.na
.Ht shell 2 .
.ad
.FH
