.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd148.2,v 2.7 2009-08-29 17:13:25 jon Exp $
.Im MicroEmacs command|help
.so me.tni
.TH about 2
.XI about - "Information About MicroEmacs"
.SH NAME
about \- Information About \*(mE
.Me $a
.SH SYNOPSIS
.na
.B about
.ad
.SH DESCRIPTION
.B about
displays  information about the current \*(mE editing session and includes the
following information:-
.BS
Version number and date (YYYY/MM/DD) information for \*(mE.
.BU
Global status  information  including the number of active  buffers and global
mode status information.
.BU
Current buffer status information; buffer modes and buffer size information.
.BE 0
.SH EXAMPLE
The following is an example output from \fBabout\fR.
.CS
MicroEmacs 05 - Date 2005/01/01 - sunos

Global Status:
  # buffers : 42
  Modes on  : auto autosv backup exact magic quiet tab undo usr3
  Modes off : binary crlf crypt ctrlz del dir edit fence hide
              indent justify lock nact narrow over pipe rbin
              save time usr1 usr2 usr4 usr5 usr6 usr7 usr8
              view wrap

Current Buffer Status:
  Buffer    : todo.log
  File name : /home/jon/merep/me/todo.log
  Lines     : Total    685, Current    353
  Characters: Total  23282, Current  12582
  Modes on  : auto autosv backup exact indent justify magic
              quiet tab time undo usr3 wrap
  Modes off : binary crlf crypt ctrlz del dir edit fence hide
              lock nact narrow over pipe rbin save usr1 usr2 usr4
              usr5 usr6 usr7 usr8 view

Copyright (C) 1988-2005 JASSPA (www.jasspa.com)
.CE 0
.SH "SEE ALSO"
.na
.Ht describe-bindings 2 ,
.Ht list-buffers 2 .
.ad
.FH
