.\" -*- nroff -*-
.Id $Id: m2cmd044.2,v 2.0 2001-03-08 21:27:21 jon Exp $
.Im MicroEmacs command|buffer|macro
.so me.tni
.TH execute-buffer 2
.XI execute-buffer \- "Execute script lines from a buffer"
.XI execute-line - "Execute a typed in script line"
.SH NAME
.Me "|execute-buffer"
execute-buffer \- Execute script lines from a buffer
.br
.Me "|execute-line"
execute-line \- Execute a script line from the command line
.Me $a
.SH SYNOPSIS
.na
.B execute-buffer
"\fIbuffer-name\fR"
.br
.B execute-line
["\fIcommand-line\fR"]
.ad
.SH DESCRIPTION
.B execute-buffer
executes script lines in the named buffer  \fIbuffer-name\fR. If the buffer is
off screen and an error  occurs  during  execution,  the cursor is left on the
line causing the error.
.PP
.B execute-line
executes a in script line  entered from the command  line.  Typically  this is
used in macros.
.SH "SEE ALSO"
.na
.Ht execute-file 2 ,
.Ht execute-string 2 ,
.Ht execute-named-command 2 .
.ad
.FH
