.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd162.2,v 1.1 2002-10-16 22:30:10 jon Exp $
.Im MicroEmacs command|window|macrodevelop
.so me.tni
.TH delete-frame 2
.XI delete-frame - "Delete the current frame"
.SH NAME
delete-frame \- Delete the current frame
.Me $a
.SH SYNOPSIS
.na
.I n
.B delete-frame
.ad
.SH DESCRIPTION
\fBdelete-frame\fR  deletes the current frame.
.SH "SEE ALSO"
.na
.Ht create-frame 2 ,
.Ht next-frame 2 .
.ad
.FH
