.\" -*- nroff -*-
.Id $Id: m2cmd010.2,v 2.0 2001-03-08 21:26:57 jon Exp $
.Im MicroEmacs command|cursor|essential
.ds C0 "(\fB\*cf\fR)\ \&
.ds C1 "(\fB\*cb\fR)\ \&
.so me.tni
.TH forward-char 2
.XI forward-char - "\*(C0Move the cursor right"
.XI backward-char - "\*(C1Move the cursor left"
.SH NAME
.Me "|forward-char"
forward-char  \- Move the cursor right
.Me "|backward-char"
backward-char \- Move the cursor left
.Me $a
.SH SYNOPSIS 
.na
.I n
\fBforward-char\fR \*(C0
.br
.I n
\fBbackward-char\fR \*(C1
.ad
.SH DESCRIPTION
.B backward-char
moves  the  cursor  \fIn\fR  characters  to the  left.  Move to the end of the
previous line if the cursor was at the beginning of the current line.
.PP
.B forward-char
moves the cursor \fIn\fR characters to the right. Move to the beginning of the
next line if the cursor was already at the end of the current line.
.SH NOTES
.B backward-char
is also bound to \fBleft\fR.
.br
.B forward-char
is also bound to \fBright\fR.
.SH "SEE ALSO"
.na
.Ht forward-line 2 ,
.Ht backward-line 2 .
.ad
.rm C0
.rm C1
.FH
