.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd103.2,v 2.5 2002-01-11 21:58:42 jon Exp $
.Im MicroEmacs command|essential
.ds C0 "(\fB\*ez\fR)\ \&
.ds C1 "(\fB\*(cX\*cc\fR)\ \&
.so me.tni
.TH quick-exit 2
.XI quick-exit - "\*(C0Exit the editor writing changes"
.XI save-buffers-exit-emacs - "\*(C0Exit the editor prompt user to write changes"
.SH NAME
.Me "|quick-exit"
quick-exit \- Exit the editor writing changes
.br
.Me "|save-buffers-exit-emacs"
save-buffers-exit-emacs \- Exit the editor prompt user to write changes
.Me $a
.SH SYNOPSIS
.na
\fBquick-exit\fR \*(C0
.br
\fBsave-buffers-exit-emacs\fR \*(C1
.ad
.SH DESCRIPTION
.B quick-exit
writes  out all  changed  buffers to the files they were read from,  saves all
changed dictionaries, killing any running commands and exits the editor.
.PP
.B save-buffers-exit-emacs
operates a \fBquick-exit\fR only prompts the user before saving any files.
.SH NOTES
All buffers  with a name  starting  with a '\fB*\fR'  are assumed to be system
buffer (i.e. \fB*scratch*\fR) and are not saved.
.SH "SEE ALSO"
.na
.Ht exit-emacs 2 ,
.Ht save-buffer 2 .
.ad
.rm C0
.rm C1
.FH
