.\" -*- nroff -*-
.Id $Id: m2cmd050.2,v 2.1 2001-05-14 19:53:32 jon Exp $
.Im MicroEmacs command|buffer|file
.ds C0 "(\fB\*(cX\*cy\fR)\ \&
.so me.tni
.TH insert-file-name 2
.XI insert-file-name \- "\*(C0Insert filename into current buffer"
.SH NAME
insert-file-name \- Insert filename into current buffer
.Me $a
.SH SYNOPSIS
.na
\fBinsert-file-name\fR \*(C0
.ad
.SH DESCRIPTION
.B insert-file-name
inserts the current buffer's file name into the current buffer or, if entering
text on the  message  line then  enters  the file name into the  message  line
buffer.
.SH "SEE ALSO"
.na
.Ht insert-file 2 ,
.Ht yank 2 .
.ad
.rm C0
.FH
