.\" -*- nroff -*-
.Id $Id: m2cmd045.2,v 2.0 2001-03-08 21:27:21 jon Exp $
.Im MicroEmacs command|macro
.ds C0 "(\fB\*e/\fR)\ \&
.so me.tni
.TH execute-file 2
.XI execute-file \- "\*(C0Execute script lines from a file"
.SH NAME
execute-file \- Execute script lines from a file
.Me $a
.SH SYNOPSIS
.na
.I n
.B execute-file
"\fIfile\fR" \*(C0
.ad
.SH DESCRIPTION
.B execute-file
executes script lines from the given  \fIfile\fR  \fIn\fR times in succession,
this is the normal way to execute a \*(mE  script. The  command  prompts for a
file name, and will then search for  <\fIfile\fR>[.emf] in the search path. If
the file is found then the file is loaded and the buffer is  executed  \fIn\fR
times.
.SH "SEE ALSO"
.na
.Ht execute-buffer 2 ,
.Ht execute-line 2 ,
.Ht execute-named-command 2 ,
.Ht execute-string 2 .
.ad
.rm C0
.FH
