.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd061.2,v 2.5 2002-01-11 21:58:42 jon Exp $
.Im MicroEmacs command|cursor
.ds C0 "(\fB\*e\*cf\fR)\ \&
.so me.tni
.TH goto-matching-fence 2
.XI goto-matching-fence \- "\*(C0Move the cursor to matching fence"
.SH NAME
goto-matching-fence \- Move the cursor to specified line
.Me $a
.SH SYNOPSIS
.na
\fBgoto-matching-fence\fR \*(C0
.ad
.SH DESCRIPTION
.B goto-matching-fence
moves the cursor to the opposing  fence  character of the character  currently
under the cursor. The set of fence characters  include \fC[]\fR,  \fC{}\fR and
\fC()\fR.   i.e.  if  the  character   under  the  cursor  is  `\fC{\fR'  then
\fBgoto-matching-fence\fR moves the cursor to the opening fence `\fC}\fR', and
visa versa.
.PP
.B goto-matching-fence
can also be used to move the cursor to matching C/C++ \fC#if\fR,  \fC#elif\fR,
\fC#else\fR  and  \fC#endif\fR  constructs,  cycling through them in the given
order.
.PP
When the
.Ht fence 2m
buffer mode is enabled the matching open fence is automatically displayed when
the closing fence is typed. The length of time the matching fence is displayed
for can be controlled by the
.Ht $fmatchdelay 5
variable.  
.SH "SEE ALSO"
.na
.Ht fence 2m ,
.Ht $fmatchdelay 5 ,
.Ht goto-line 2 .
.ad
.rm C0
.FH
