.\"*-*- nroff -*-*************************************************************
.\"
.\"			Copyright 1998 Jon Green.
.\"			      All Rights Reserved
.\"
.\"
.\"  System        :
.\"  Module        :
.\"  Object Name   : m2cmd025.2
.\"  Created By    : Jon Green
.\"  Created       : Thu Jul 16 23:13:14 1998
.\"  Last Modified : <000719.1013>
.\"
.\"  Description
.\"
.\"  Notes
.\"
.\"  History
.\"
.\"***************************************************************************
.\"
.\"  Copyright (c) 1998 Jon Green.
.\"
.\"  All Rights Reserved.
.\"
.\"  This  document  may not, in  whole  or in part, be  copied,  photocopied,
.\"  reproduced,  translated, or reduced to any  electronic  medium or machine
.\"  readable form without prior written consent from Jon Green.
.\"
.\"***************************************************************************
.\"
.Id $Id: m2cmd025.2,v 1.1.1.1 2000-07-25 22:03:54 jon Exp $
.Im MicroEmacs command|registry
.so me.tni
.TH list-registry 2
.XI list-registry - "Display the registry in a buffer"
.SH NAME
list-registry \- Display the registry in a buffer
.Me $a
.SH SYNOPSIS
.na
.B list-registry
.ad
.SH DESCRIPTION
.B list-registry
lists the contents of the registry in the a buffer in a hierarchical format.
The key name and any associated string is shown as a hierarchical tree.
.PP
The registry listing is generated in the buffer "\fC*registry*\fR".
.SH "SEE ALSO"
.na
.Ht read-registry 2 ,
.Ht erf 8 .
.ad
.FH
