.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m2cmd063.2,v 2.7 2009-08-29 17:13:09 jon Exp $
.Im MicroEmacs command|window
.so me.tni
.TH change-window-depth 2
.XI change-window-depth \- "Change the depth of the current window"
.XI grow-window-vertically \- "Enlarge the current window (relative change)"
.XI shrink-window-vertically \- "Shrink the current window (relative change)"
.XI resize-window-vertically \- "Resize the current window (absolute change)"
.SH NAME
.Me "|change-window-depth"
change-window-depth \- Change the depth of the current window
.br
.Me "|grow-window-vertically"
grow-window-vertically \- Enlarge the current window (relative change)
.br
.Me "|shrink-window-vertically"
shrink-window-vertically \- Shrink the current window (relative change)
.br
.Me "|resize-window-vertically"
resize-window-vertically \- Resize the current window (absolute change)
.Me $a
.SH SYNOPSIS
.na
\fIn\fR \fBchange-window-depth\fR [ "\fIdepth\fR" ]
.sp
\fIn\fR \fBgrow-window-vertically\fR
.br
\fIn\fR \fBshrink-window-vertically\fR
.br
\fIn\fR \fBresize-window-vertically\fR
.ad
.SH DESCRIPTION
\fBchange-window-depth\fR  changes  the depth of the  current  window,  if the
numeric  argument \fIn\fR is given then the window depth is changed by \fIn\fR
lines.  If  \fIn\fR  is not  specified  the  user  is  prompted  for  the  new
\fIdepth\fR  and the window  depth will be changed to this value. The  command
aborts if the requested  size cannot be achieved (the window becomes too small
or a neighbouring one does).
.SH NOTES
Commands   \fBgrow-window-vertically\fR,   \fBshrink-window-vertically\fR  and
\fBresize-window-vertically\fR      were      replaced      by     the     new
\fBchange-window-depth\fR   command  in  April  2002.   Following   are  macro
implementations of the old commands:
.Me $emf-scheme
.CS
define-macro grow-window-vertically
    @# change-window-depth
!emacro

define-macro shrink-window-vertically
    &neg @# change-window-depth
!emacro

define-macro resize-window-vertically
    !if &not @?
        !abort
    !endif
    change-window-depth @#
!emacro
.CE 0
.Me $ehf-scheme
.SH "SEE ALSO"
.na
.Ht change-window-width 2 ,
.Ht resize-all-windows 2 ,
.Ht split-window-vertically 2 .
.ad
.FH

