.\" -*- nroff -*-
.Id $Id: m2mod010.2,v 1.1.1.1 2000-07-25 22:03:58 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH over 2m
.XI over - "Over-strike Mode"
.SH NAME
over \- Over-strike Mode
.SH SYNOPSIS
.B "over Mode"
.sp
\fBO\fR \- mode line letter.
.SH DESCRIPTION
.B over
mode, when  enabled,  over  writes  existing  text in a buffer as  opposed  to
inserting  text.  \s-1over\s0  maintains  the  position of text  aligned  with
\fCtab\fR characters.
.SH "SEE ALSO"
.na
.Ht buffer-mode 2 ,
.Ht global-mode 2 .
.ad
.FH
