.\" -*- nroff -*-
.Id $Id: m2mod004.2,v 1.1.1.1 2000-07-25 22:03:57 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH exact 2m
.XI exact - "Searching and sorting case sensitivity"
.SH NAME
exact \- Searching and sorting case sensitivity
.SH SYNOPSIS
.B "exact Mode"
.sp
\fBE\fR \- mode line letter.
.SH DESCRIPTION
.B exact
mode sets the  searching  and line  sorting  commands to case  sensitive  when
enabled (case insensitive when disabled).
See
.Ht search-forward 2
and
.Ht sort-lines 2 .
.SH "SEE ALSO"
.na
.Ht buffer-mode 2 ,
.Ht global-mode 2 ,
.Ht search-forward 2 ,
.Ht sort-lines 2 .
.ad
.FH
