.\" -*- nroff -*-
.Id $Id: m2mod006.2,v 2.2 2001-07-14 10:10:54 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH justify 2m
.XI justify - "Justification Mode"
.SH NAME
justify \- Justification Mode
.SH SYNOPSIS
.B "justify Mode"
.sp
\fBJ\fR \- mode line letter.
.SH DESCRIPTION
.B justify
mode, when enabled, performs paragraph justification as designated by
.Ht $fill-mode 5
\- capable of  \fIleft\fR,  \fIright\fR,  \fIboth\fR  or
\fIcenter\fR  justification  of text. Justify  removes all white spaces at the
end of the line, if there  are no  non-white  characters  on the line then the
line is always  left empty. If the  justification  method is  \fIcenter\fR  or
\fIright\fR  then all white  spaces are removed at the  beginning of the line.
If the line is longer than the
.Ht $fill-col 5
or the  method  is  \fIleft\fR  then  nothing  more is done,  else the line is
appropriately justified. The method used is set by the variable
.Ht $fill-mode 5 .
Justify is usually used in conjunction with
.Ht wrap 2m
and
.Ht indent 2m .
.SH "SEE ALSO"
.na
.Ht buffer-mode 2 ,
.Ht global-mode 2 ,
.Ht wrap 2m
.Ht indent 2m ,
.Ht $fill-col 5 ,
.Ht $fill-mode 5 .
.ad
.FH
