.\" -*- nroff -*-
.Id $Id: m2mod015.2,v 2.0 2001-03-08 21:28:43 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH usr 2m
.XI usr - "User buffer modes"
.Me "!32musr1..usr8"
.SH NAME
usr1 \- usr8 \- User buffer modes
.SH SYNOPSIS
.B "usr1-usr8 Mode"
.sp
\fB1\fR\-\fB8\fR \- mode line letters.
.SH DESCRIPTION
.B usr1
through 
.B usr8
modes have no  predefined  purpose,  they are present to provide the user with
the ability to store some buffer state. All of these modes are off by default.
For  example,  the user may wish to have two  commands  bound to the same key,
with another command to toggle which one is currently active.
.SH "SEE ALSO"
.na
.Ht buffer-mode 2 ,
.Ht global-mode 2 .
.ad
.FH
