.\" -*- nroff -*-
.Id $Id: m2mod025.2,v 2.0 2001-03-08 21:28:49 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH narrow 2m
.XI narrow - "Buffer contains a narrow"
.SH NAME
narrow \- Buffer contains a narrow
.SH SYNOPSIS
.B "narrow Mode"
.sp
\fBN\fR \- mode line letter.
.SH DESCRIPTION
This  mode  can  not  be set  and is  used  to  indicate  whether  the  buffer
contains a narrow, created by the
.Ht narrow-buffer 2
command.
.SH "SEE ALSO"
.na
.Ht narrow-buffer 2 .
.ad
.FH
