.\" -*- nroff -*-
.Id $Id: m2mod007.2,v 2.1 2001-05-14 19:54:00 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH letter 2m
.XI letter - "Letter kill policy"
.SH NAME
letter \- Letter kill policy
.SH SYNOPSIS
.B "letter Mode"
.sp
\fBl\fR \- mode line letter.
.SH DESCRIPTION
By default  individually  deleted  characters are not added to the kill buffer
unless an  argument is given to the  command.  This allows the user to delete
characters  while preserving the kill buffer, at the expense of not being able
to 
.Ht yank 2
the  character  back out. Enabling  \fBletter\fR mode ensures that all deleted
characters are added to the kill buffer.
.SH NOTES
This mode is implemented for backwards compatability only and the use of it is
strongly discouraged as this may alter the behaviour of many on the supporting
macros. If this  feature is required it would be  preferable  to use a numeric
argument with the delete or backspace key binding as follows:
.Me $emf-scheme
.CS
1 global-bind-key backward-delete-char "backspace"
.CE
.Me $ehf-scheme
The use of the numeric argument of 1 has the same effect. 
.SH "SEE ALSO"
.na
.Ht buffer-mode 2 ,
.Ht global-mode 2 ,
.Ht yank 2 ,
.Ht line 2m .
.ad
.FH
