.\" -*- nroff -*-
.Id $Id: m2mod003.2,v 2.1 2001-05-14 19:53:59 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH crypt 2m
.XI crypt - "Encrypted file mode"
.SH NAME
crypt \- Encrypted file mode
.SH SYNOPSIS
.B "crypt Mode"
.sp
\fBY\fR \- mode line letter.
.SH DESCRIPTION
.B crypt
mode  enables  encrypted  files to be loaded and saved for security  purposes.
The key can be set at any time using the command
.Ht set-encryption-key 2 .
Warning, take care if setting this as a global mode, it can have side-effects.
.PP
The  encryption  algorithm  is a Beaufort  Cipher with a variant  key. This is
reasonably  difficult to decrypt. When you write out text, if \fCcrypt\fR mode
is active and there is no encryption key, \*(mE will ask:
.IP
.C "Encryption String:"
.LP
Type in a word or  phrase of at least  five and up to 128  characters  for the
encryption  to use. If you look at the file which is then written out, all the
printable characters have been scrambled. To read such a file later, use
.Ht find-cfile 2
to load  \fIciphertext\fR  files, you will be asked the  encryption key before
the file is read.
.SH "SEE ALSO"
.na
.Ht buffer-mode 2 ,
.Ht find-cfile 2 ,
.Ht global-mode 2 ,
.Ht set-encryption-key 2 .
.ad
.FH
