.\" -*- nroff -*-
.Id $Id: m2mod023.2,v 2.4 2001-12-18 16:52:53 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH nact 2m
.XI nact - "Buffer not active"
.SH NAME
nact \- Buffer not active
.SH SYNOPSIS
.B "nact Mode"
.sp
\fBn\fR \- mode line letter.
.SH DESCRIPTION
This  mode  can not be set and is used to  indicate  that the  buffer  has not
been  activated,  i.e. the buffer has not been  displayed  in a window. If the
buffer is linked to a file but has not been  displayed,  so is not active, the
file will not have been loaded into the buffer.
.PP
The
.Ht list-buffers 2
command  output  denotes  active buffers with a '@' character in the left hand
column, inactive buffers have a ' '.
.PP
This mode can not be tested using the more usual
.Ht &bmode 4
macro  command as it only  operates  on the current  buffer as which point the
mode cannot be set. Instead the
.Ht &nbmode 4
macro command must be used.
.SH "SEE ALSO"
.na
.Ht list-buffers 2 ,
.Ht &nbmode 4 ,
.Ht &bmode 4 .
.ad
.FH
