.\" -*- nroff -*-
.Id $Id: m2mod032.2,v 1.1 2001-12-06 00:05:23 jon Exp $
.Im MicroEmacs modes
.so me.tni
.TH fence 2m
.XI fence - "Auto fence matching mode"
.SH NAME
fence \- Auto fence matching mode
.SH SYNOPSIS
.B "fence Mode"
.sp
\fBf\fR \- mode line letter.
.SH DESCRIPTION
.B fence
mode can be used to enable or disable  the  automatic  displaying  of and open
fence when the corresponding  closing fence is typed. When the mode is enabled
and the closing fence is typed the cursor is temporarily  move to the position
of the opening fence. The duration of the move can be controlled by the
.Ht $fmatchdelay 5
variable; any user input interrupts the display.
.PP
If
.Ht cmode 2m
is also enabled the search algorithm used is '\fIC\fR' aware and if a matching fence
is not found then the bell is rung as a warning. If  \fBcmode\fR is not enable
any closing fence which cannot be matched is ignored. 
.SH NOTES
The following characters are considered closing fences:
.CS
}  )  ]
.CE
These are match with the following opening fences respectively:
.CS
{  (  [
.CE 0
.SH "SEE ALSO"
.na
.Ht $fmatchdelay 5 ,
.Ht cmode 2m ,
.Ht goto-matching-fence 2 .
.ad
.FH
