.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Mon Nov 29 17:39:42 1999
.\"
.Id $Id: m3mac048.3,v 2.6 2002-10-16 22:28:04 jon Exp $
.Im MicroEmacs command|spell|scuts
.so me.tni
.TH expand-word 3
.XI expand-word - "Complete a word by invocation of the speller"
.SH NAME
expand-word \- Complete a word by invocation of the speller
.Me $a
.SH SYNOPSIS
.na
.B expand-word
.ad
.SH DESCRIPTION
\fBexpand-word\fR  attempts  to  complete  the  word at the  current  position
through the use of the current language dictionary. The user is presented with
a list of endings for the given word portion.  These may be selected  with the
cursor or mouse.
.PP
.B expand-word
is automatically invoked from the
.Ht expand-abbrev-handle 3
macro in  response  to an  expansion  command,  it is only  invoked if enabled
in the 
.Ht user-setup 3
=> General => Abbrev Expansion => Dict'n setting is enabled.
.SH NOTES
.B expand-word
is a macro implemented in \fCabbrev.emf\fR.
.PP
The   \fBuser-setup\fR   configuration   simply   sets  the   macro   variable
\fC.expand-word.on\fR to TRUE, i.e.:
.Me emf-scheme
.CS
set-variable .expand-word.on 1
.CE
.Me ehf-scheme
It may be subsequently disabled by setting the variable back to 0.
.SH "SEE ALSO"
.na
.Ht expand-abbrev-handle 3 ,
.Ht spell-buffer 3 ,
.Ht find-word 3 .
.ad
.FH
