.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m3mac053.3,v 2.6 2006-09-21 18:39:02 bill Exp $
.Im MicroEmacs command|file
.so me.tni
.TH reread-file 3
.XI reread-file - "Reload the current buffer's file"
.SH NAME
reread-file \- Reload the current buffer's file
.Me $a
.SH SYNOPSIS
.na
.I n
.B reread-file
.ad
.SH DESCRIPTION
.B reread-file
reloads from disk the file associated with the current buffer, this command is
particularly  useful  when  the file is  continually  updated  by an  external
program.  If the  buffer  has been  edited  and its name does not start with a
\&'\fC*\fR'  then the user is  prompted  as to whether  the changes  should be
discarded.  Also  if the  buffer  has an  active  process  running  in it then
confirmation is sort from the user before the process is killed.
.PP
The  argument  \fIn\fR  can  be  used  to  change  the  default  behavior  of
reread-file described above, \fIn\fR is a bit based flag where:-
.IP \fB0x01\fR
Enables loss of work checks  (default), if this flag is not supplied  then the
buffer is reread without any user prompts (useful in macros).
.SH NOTES
\fBreread-file\fR is a macro implemented in \fCtool.emf\fR.
.SH "SEE ALSO"
.na
.Ht find-file 2 ,
.Ht read-file 2 ,
.Ht view-file 2 .
.ad
.FH
