.\" -*- nroff -*-
.Id $Id: m3mac011.3,v 2.2 2001-07-14 10:11:09 jon Exp $
.Im MicroEmacs command
.so me.tni
.TH alarm 3
.XI alarm - "Set an alarm"
.SH NAME
alarm \- Set an alarm
.Me $a
.SH SYNOPSIS
.na
\fBalarm\fR
"\fImessage\fR" "\fIhours\fR" "\fIminutes\fR"
.ad
.SH DESCRIPTION
.B alarm
creates  an alarm for the user which will print the given  "\fImessage\fR"  in
the given number of "\fIhours\fR" and "\fIminutes\fR"  time from the moment of
creation.
.PP
The message is printed on the screen using
.Ht osd 2 .
.SH NOTES
.B alarm
is a macro defined in \fCmisc.emf\fR.
.SH "SEE ALSO"
.na
.Ht osd 2 .
.ad
.FH
