.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m3mac001.3,v 2.9 2009-08-31 17:55:57 jon Exp $
.Im MicroEmacs command|shell
.so me.tni
.TH xgrep 3
.XI xgrep - "Execute grep command"
.XI rgrep - "Execute recursive grep command"
.SH NAME
xgrep \- Execute grep command
.br
rgrep \- Execute recursive grep command
.Me $a
.SH SYNOPSIS
.na
.Me "|xgrep"
.B xgrep
"\fIexpression files...\fR"
.Me "|rgrep"
.B rgrep
"\fIexpression\fR" "\fIbase-path\fR" "\fIfile-mask\fR"
.ad
.SH DESCRIPTION
.B xgrep
executes the
.Hr grep 1
command with the  command line set by the
.Ht %xgrep-com 5
variable and the user supplied  \fIexpression\fR and file list \fIfiles...\fR.
The output of the command is piped into the \fB*grep*\fR buffer ready for the
.Ht get-next-line 2
command to step through all matched lines. The syntax from
the   grep   output   must  be   setup   using   
.Ht add-next-line 2 .
.PP
If an argument is given then a
.Ht pipe-shell-command 2
is used instead of
.Ht ipipe-shell-command 2 ,
this is useful when used in macros as it ensures that  \fBgrep\fR has finished
before the command returns.
.PP
.B rgrep
is similar to \fBgrep\fR in that it uses
.Hr grep 1
to search for all occurrences of \fIexpression\fR, but \fBrgrep\fR also uses
.Hr find 1
to search for  \fIexpression\fR  in all files matching the  \fIfile-mask\fR in
all directories from \fIbase-path\fR down.
.SH NOTES
\fBxgrep\fR is a macro defined in \fCxfind.emf\fR.
.PP
.Hr grep 1 
must be executable on the system before grep or rgrep can function,
.Hr find 1 
must also be available for rgrep to work. 
The 
.Hr find 1 
command is defined by variable
.Ht %xfind-com 5 ,
the default when not defined is \fCfind\fR.
.SH EXAMPLE
The \fBxgrep\fR command is generally set up in the startup files as follows:-
.Me $emf-scheme
.CS
;
; setup the next-error stuff including grep and compiling
;
set-variable $line-template "[0-9]+"
set-variable $file-template "[a-zA-Z:]*[0-9a-zA-Z\\_.]+"
;
; Definitions for GNU grep utility.
;
set-variable %xgrep-com "grep -n "
0 add-next-line "*grep*"
add-next-line "*grep*" "%f:%l:"
.CE 0
.Me $ehf-scheme
.SH "SEE ALSO"
.na
.Ht %xfind-com 5 , 
.Ht %xgrep-com 5 ,
.Ht add-next-line 2 ,
.Ht compile 3 .
.Hr find 1 ,
.Ht xfind 3 ,
.Ht get-next-line 2 ,
.Hr grep 1 .
.ad
.FH
