.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2006 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m3osd003.3,v 2.7 2006-08-12 19:08:47 jon Exp $
.Im MicroEmacs command|osd
.so me.tni
.TH insert-symbol 3
.XI insert-symbol - "Insert an ASCII character"
.SH NAME
insert-symbol \- Insert an ASCII character
.Me $a
.SH SYNOPSIS
.na
.B insert-symbol
.ad
.SH DESCRIPTION
\fBinsert-symbol\fR  draws the ASCII character table to the screen, displaying
decimal, hexadecimal and character notations in a tabular form. A character is
selected using the mouse or cursor characters inserting the selected character
into the current buffer at the current position.
.SH NOTES
\fBinsert-symbol\fR is a macro defined in \fCosdmisc.emf\fR.
.PP
The dialog is created using
.Ht osd 2 .
.SH "SEE ALSO"
.na
.Ht insert-string 2 ,
.Ht &atoi 4 ,
.Ht osd 2 .
.ad
.FH
