.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Tue Feb 2 21:10:34 1999
.\"
.Id $Id: m3osd004.3,v 2.5 2002-01-11 21:58:42 jon Exp $
.Im MicroEmacs command|search|hilight|osd
.ds C0 "(\fB\*e$\fR)\ \&
.so me.tni
.TH line-scheme-search 3
.XI line-scheme-search 3 "Search and annotate the current buffer"
.SH NAME
line-scheme-search \- Search and annotate the current buffer
.Me $a
.SH SYNOPSIS
.na
\fBline-scheme-search\fR
.ad
.SH DESCRIPTION
.B line-scheme-search
provides a method of searching for text patterns within the current buffer and
annotating any matches  through  colored line  hilighting. A selection of line
colors are provided to allow  different  search  patterns to be assigned their
own color.
.PP
.B line-scheme-search
is generally  used for annotating log files and alike, where  indevidual  lines
are of  interest  in addition to the context  about that line. The  hilighting
draws  attention to the line, by providing a visual cue, allowing the contents
of the file to be breifly scanned.
.PP
On invocation of \fBline-scheme-search\fR a
.Ht osd 2 
dialog  is  presented  to the  user,  search  patterns  and  their  associated
hilighting  assignment are selected through this interface. The dialog entries
are defined as follows:-
.IP "\fBSearch for\fR"
The text dialog entry box allows the search pattern to be entered. This may be
a regular expression or plain text.
.IP \fBColor\fR
The \fBColor\fR  allows the line hilighting color scheme to be selected from a
pop-up menu. The color  \fBRemove\fR is special and allows previously  applied
line hilighting to be removed.
.IP "\fBCase Sensitive\fR"
A check box that allows the search to be case sensitive or  insensitive.  This
modifies the
.Ht exact 2m 
mode.
.IP "\fBMagic Mode\fR"
A check box that  enables/disables  regular  expression pattern matching. This
modifies the
.Ht magic 2m 
mode.
.IP "\fBBelow\fR"
Searches  and  hilights  lines  matching  the search  pattern from the current
cursor position to the end of the buffer.
.IP "\fBAbove\fR"
Searches  and  hilights  lines  matching  the search  pattern from the current
cursor position to the top of the buffer.
.IP "\fBAll\fR"
Searches and hilights lines matching the search pattern for the whole buffer.
.IP "\fBClear All\fR"
Removes all line hilighting from the current buffer.
.IP "\fBFirst\fR"
Moves to the top of the buffer and  hilights  the first line that  matches the
search pattern.
.IP "\fBNext\fR"
Hilights the next line that matches the search pattern.
.IP "\fBReverse\fR"
Hilights the previous line that matches the search pattern.
.IP "\fBExit\fR"
Exits the hilighting search dialog.
.SH "NOTES"
.B line-scheme-search
is a macro implemented in \fChiline.emf\fR.
.SH "SEE ALSO"
.na
.Ht osd 2 ,
.Ht $line-scheme 5 .
.ad
.rm C0
.FH
