.Id $Id: m3osd003.3,v 2.3 2001-12-06 00:04:32 jon Exp $
.Im MicroEmacs command|osd
.so me.tni
.TH symbol 3
.XI symbol - "Insert an ASCII character"
.SH NAME
symbol \- Insert an ASCII character
.Me $a
.SH SYNOPSIS
.na
.B symbol
.ad
.SH DESCRIPTION
\fBsymbol\fR  draws  the  ASCII  character  table  to the  screen,  displaying
decimal, hexadecimal and character notations in a tabular form. A character is
selected using the mouse or cursor characters inserting the selected character
into the current buffer at the current position.
.SH NOTES
\fBsymbol\fR is a macro defined in \fCmisc.emf\fR.
.PP
The dialog is created using
.Ht osd 2 .
.SH "SEE ALSO"
.na
.Ht insert-string 2 ,
.Ht &atoi 4 ,
.Ht osd 2 .
.ad
.FH
