.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m4fil010.4,v 2.6 2009-08-29 17:14:03 jon Exp $
.Im MicroEmacs macro;directive|miscellaneousOperators
.so me.tni
.TH !return 4
.XI !return - "Exit macro with a TRUE status"
.XI !abort  - "Exit macro with a FALSE status"
.SH NAME
!return, !abort \- Exit macro
.SH SYNOPSIS
.na
.nf
\fB!return\fR [\fIn\fR]
\fB!abort\fR [\fIn\fR]
.fi
.ad
.SH DESCRIPTION
The \fB!return\fR directive causes the current macro to exit with a \fCTRUE\fR
status, either returning to the caller (if any) or to interactive  mode. If an
argument  \fIn\fR is specified  then the return  status is  determined  by the
value of \fIn\fR.
.PP
\fB!abort\fR  has the same  effect as  \fB!return\fR  only always  returning a
\fCFALSE\fR  status to halt the execution of any calling macro. If an argument
\fIn\fR is given to  \fB!abort\fR  the bell is also rung, the valid  values of
\fCn\fR are the same as for the
.Ht !bell 4
directive.
.SH EXAMPLE
The  following  example  checks the current  language  and warns if it has not
be set, i.e. \fCDefault\fR.
.Me $emf-scheme
.CS
;	Check the current language

!if &not &seq %language "Default"
    !return
!endif
ml-write "Warning - you have not setup the Language - use user-setup"
.CE
.Me $ehf-scheme
The following example is shows the logic of the \fB!return\fR directive:-
.CS
.Me $emf-scheme
; !return example
define-macro i-will-return
    ml-write "you will see me"
    !return
    ml-write "you wont see me"
!emacro

define-macro test-return
    ml-write "you will see me"
    i-will-return
    ml-write "you will see me"
!emacro
.CE
.Me $ehf-scheme
Similarly, for the \fB!abort\fR directive
.Me $emf-scheme
.CS
; !abort example
define-macro i-will-abort
    ml-write "you will see me"
    !abort
    ml-write "you wont see me"
!emacro

define-macro test-abort
    ml-write "you will see me"
    i-will-abort
    ml-write "you wont see me"
!emacro
.CE
.Me $ehf-scheme
For the last two examples above, all the  "\fBwill\fR"s are displayed and none
of the "\fBwont\fR"s are.
.SH "SEE ALSO"
.na
.Ht define-macro 2 ,
.Ht !bell 4 ,
.Ht !if 4 ,
.Ht !goto 4 .
.ad
.FH
