.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m5var023.5,v 2.6 2005-01-01 15:02:12 bill Exp $
.Im MicroEmacs variable|cursor
.so me.tni
.TH $pause-time 5
.XI $pause-time - "Length of time to pause for user"
.XI $fmatchdelay - "Fence matching delay time"
.SH NAME
$pause-time \- Length of time to pause for user
.Me $a
.SH SYNOPSIS
\fB$pause-time\fR \fImilliseconds\fR; Default is \fC2000\fR
.sp
0 <= \fImilliseconds\fR <= \fIt\fR
.SH DESCRIPTION
Defines the number of  milliseconds  to pause,  allowing  the user to see some
information.  The  pause  time  is  used  predominantly  by  the  fence  match
operation, determining the time  that the
opening fence is displayed, see
.Ht fence 2m
mode.
.PP
The  \fB$pause-time\fR is also used during the printing of some error messages
on the message-line. These errors are typically important ones that should not
be  ignored  so the system  pauses to ensure the user has enough  time to read
them.
.SH NOTES
The variable name was changed from \fB$fmatchdelay\fR in December 2004. 
.SH "SEE ALSO"
.na
.Ht fence 2m .
.ad
.FH
