.\" -*- nroff -*-
.Id $Id: m5var015.5,v 2.0 2001-03-08 21:30:14 jon Exp $
.Im MicroEmacs variable|scuts
.so me.tni
.TH $c-contcomm 5
.XI $c-contcomm - "C-mode; comment continuation string"
.SH NAME
$c-case \- C-mode; comment continuation string
.Me $a
.SH SYNOPSIS
\fB$c-contcomm\fR "\fIstring\fR"
.SH DESCRIPTION
.B $c-contcomm
is part of the
.Ht cmode 2m
environment for C programmers.
.PP
This defines the string which is inserted  when a new line is started while in
a comment. The string is only inserted if the cursor is at the end of the line
when the
.Ht newline 2 
command is given. For  example, for the default  settings, if a  \fBnewline\fR
was  entered at the end of the first  line, the second  line would  initialize
to:-
.CS
                /* xxxxxxxxxx
                   @
.CE
where '\fC@\fR' is the current cursor position. With a setting of "\fC * \fR",
then:-
.CS
                /* xxxxxxxxxx
                 * @
.CE 0
.SH "SEE ALSO"
.na
.Ht cmode 2m .
.ad
.FH

