.\" -*- nroff -*-
.Id $Id: m5var018.5,v 1.1.1.1 2000-07-25 22:04:04 jon Exp $
.Im MicroEmacs variable|scuts
.so me.tni
.TH $c-continue 5
.XI $c-continue - "C-mode; line continuation indent"
.XI $c-contmax - "C-mode; line continuation maximum indent"
.SH NAME
.Me "|$c-continue"
$c-continue \- C-mode; line continuation indent
.br
.Me "|$c-contmax"
$c-contmax \- C-mode; line continuation maximum indent
.Me $a
.SH SYNOPSIS
\fB$c-continue\fR \fIinteger\fR; Default is \fC10\fR
.br
\-n <= \fIinteger\fR <= \fIn\fR
.sp
\fB$c-contmax\fR \fIinteger\fR; Default is \fC16\fR
.br
\-n <= \fIinteger\fR <= \fIn\fR
.SH DESCRIPTION
.B $c-continue
and
.B $c-contmax
are part of the
.Ht cmode 2m
environment for C programmers.
.PP
.B $c-continue
sets the  indent  to be added to a split  line,  i.e. for an  indent  of 20, a
continued statement would be indented to 30. A continued statement is a single
c  statement  which is spread over 2 or more lines, the 2nd and any  following
lines would be indented to 30. For example
.CS
        thisIsAVeryLongVariableWhichMeansAssignmentsAreSplit =
                  ThisIsTheFirstContinuedStatementLine +
                  ThisIsTheSecondContinuedStatementLine + etc ;
.CE
The indent is  changed if there  is an open  bracket, continued statements are
indented to the depth of the open bracket plus one, e.g.
.CS
        func(firstFuncArg,
             secondFuncArg,
             anotherBracketForFun(firstAnotherBracketForFunArg,
                                  secondAnotherBracketForFunArg),
             thirdFuncArg) ;
.CE
.B $c-contmax
sets an upper limit of the  indentation  where an open bracket is encountered,
in the case where the leading  indent of the  function  name and open  bracket
exceeds \fB$c-contmax\fR, then the continuation is reduced to the continuation
indent.
.PP
The effect of \fB$c-contmax\fR is described as follows; if \fB$c-contmax\fR
is set to a large value then the default open brace offset appearence is:-
.CS
longVariable = LongFunctionNameWhichMeans(isSoFar,
                                          OverAndYouRunOutOfRoom) ;
.CE
Setting \fB$c-contmax\fR to 16 gives:
.CS
longVariable = LongFunctionNameWhichMeans(isSoFar,
                overAndYouRunOutOfRoom) ;
.CE
Where by the second argument indent has been  artificially  reduced because of
it's length.
.SH "SEE ALSO"
.na
.Ht cmode 2m .
.ad
.FH
