.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1998-2004 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.Id $Id: m8fil006.8,v 2.6 2004-02-01 23:36:27 jon Exp $
.Im MicroEmacs
.so me.tni
.TH me32.ini 8
.XI me32.ini - "Microsoft Window's Initialization (ini) File"
.SH NAME
me32.ini \- Microsoft Window's Initialization (ini) File
.SH SYNOPSIS
.na
.nf
.sp
.B "[Location]"
\fBexe\fR=\|\fI<executablePathname>\fR
.sp
.B "[Defaults]"
\fBmepath=\fR\|\fI<directoryPath>\fR
\fBmeinstallpath=\fR\|\fI<directoryPath>\fR
\fBgeometry=\fR\|\fI<width>\fR\|\fBx\fR\|\fI<depth>\fR+\|\fI<xoffset>\fR+\|\fI<yoffset>\fR
\fBfontfile=\fR\|\fI<fontFileName>\fR
.sp
\fB[\fR\|\fI<userName>\fR\|\fB]\fR
\fBmename\fR\|\fB=\fR\|\fI<value>\fR
\fBmeuserpath\fR\|\fB=\fR\|\fI<value>\fR
.sp
\fB[\fR\|\fI<userName>\fR\|\fB]\fR
\fBmename\fR\|\fB=\fR\|\fI<value>\fR
\fBmeuserpath\fR\|\fB=\fR\|\fI<value>\fR
.sp
\fB;\fR \fIComments commence with a semi-colon\fR
.fi
.ad
.SH PLATFORM
.B "Microsoft Windows environments only"
.SH DESCRIPTION
.B me32.ini
is the Microsoft Windows  configuration file, located in the windows directory
(typically
\fBC:\\Windows\fR\|),
the
.B me32.ini
file is  primarily  used to  counteract  the  deficiencies  of  Windows  shell
environment (as compared with \s-1UNIX\s0) with respect to the  initialization
of environment variables.
.PP
The  configuration  file may be  considered  to be split into two  sections, a
\fBDefaults\fR section, which defines system settings and a \fBUser\fR section
which allows environment variables to be defined.
.SS "User Section"
The \fBUser  Section\fR is executed prior to the  \fBDefaults  Section\fR. The
\fBUser Section\fR uses the 
.Ht $user-name 5
which is defined as follows:-
.BS
The  environment  variable
.Ht $MENAME 5 
.BU
The \fIlogin\  name\fR under Windows '95 or NT. If the \fIlogin\  name\fR is
defined then the variable
.Ht $user-name 5
is set to this value.
.BU
The  environment  variable
.Ht $LOGNAME 5
if the \fIlogin\ name\fR cannot be located.
.BE
A section  \fB[\fR\|\fIuserName\fR\|\fB]\fR  is looked up, and if located each
of the entries is used to set up the editor.
.IP "\fBmename\fR"
The \*(mS 
.Ht $user-name 5
to use rather than the login name.
.IP \fBmeuserpath\fR
The value of 
.Ht $user-path 5 .
.SS "Defaults Section"
The defaults section, labeled \fB[Defaults]\fR includes the following keys:-
.IP "\fBmepath\fR"
Sets the environment variable
.Ht $MEPATH 5 
to the  specified  value. This is the  directory  (or folder)  location of the
\*(mE default configuration files.
.IP "\fBmeinstallpath\fR"
Equivalent of setting the environment variable
.Ht $MEINSTALLPATH 5 
to define the directory (or folder)  location of the macros  directory.
.IP "\fBgeometry\fR"
The  geometry of the window the width and height are  specified in  character,
the position of the window is specified as an offset.
.IP \fBfontfile\fR
A default font file to use to render the font. This is not really required.
.SS "Location Section"
The location  section,  labeled  \fB[Location]\fR,  identifies the location of
\*(mE,  and  is  typically  used  by  other  components  to  find  and  launch
MicroEmacs. The section includes the following keys:-
.IP \fBexe\fR
The absolute pathname to the \*(mE executable image.
.ne 20
.SH EXAMPLE
The following is an example of the \fBme32.ini\fR file:-
.CS
; External locater for the executable 
[Location]
exe=c:\\Program Files\\JASSPA\\MicroEmacs\\me32.exe
;
[Defaults]
; mepath
; The location of the MicroEmacs common files.
;
meinstallpath=d:/jasspa
;
; userpath - The location of the users MicroEmacs directory.
;
meuserpath=d:/jasspa/user
.CE
Note that  multiple  users share the same  \fBme32.ini\fR  file, each user may
include their own  configuration  settings  which may be  interrogated  in the
configuration files.
.SH NOTES
As of \*(mS 2004 then the \fBme32.ini\fR  file is depreciated and not normally
used.
.SH "SEE ALSO"
.na
.Ht user-setup 3 ,
.Ht $MEINSTALL_PATH 5 
.Ht $MENAME 5 ,
.Ht $MEPATH 5 ,
.Ht $MEUSERPATH 5 ,
.Ht $user-name 5 ,
.Ht $user-path 5 ,
.Ht emf 8 .
.ad
.FH
