.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2002 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ016.9,v 2.5 2002-01-11 21:58:43 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH fvwm 9
.XI fvwm - "FVWM configuration file"
.XI fvwmrc - "FVWM configuration file"
.SH SYNOPSIS
fvwm, fvwmrc \- FVWM Window manager configuration files
.SH FILES
.na
.B hkfvwm.emf
\- FVWM configuration file hook definition
.ad
.SH EXTENSIONS
.na
\fB.fvwm\fR, \fB.fvwmrc\fR \- FVWM configuration file
.ad
.SH "MAGIC STRINGS"
.TP 
\fB-!- fvwm -!-\fR
.\"
The embedded  fvwm string may be used with later  versions of fvwm which use a
different file extension to force the hilighting of the file.
.SH DESCRIPTION
The  \fBfvwm\fR  file type  template  provides  simple  hilighting of the FVWM 
files, the template provides minimal hilighting.
.SH BUGS
None  reported. 
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
