.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2005 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ045.9,v 1.1 2005-01-24 23:36:10 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH asp 9
.XI asp - "Active Server Pages" 
.SH SYNOPSIS
asp \- Active Server Pages.
.SH FILES
.na
.B hkasp.emf
\- Active Server Pages file hook definition
.ad
.SH DESCRIPTION
The \fBasp\fR file type template  provides simple  hilighting of Active Server
Pages embedded within 
.Ht html 9 
files.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
