.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Thu Jun 24 22:19:53 1999
.\"
.Id $Id: m9typ035.9,v 2.6 2009-08-29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH MetaFont 9
.XI MetaFont - "MetaFont/MetaPost File"
.XI mp - "MetaPost File"
.XI mf - "MetaFont File"
.SH SYNOPSIS
MetaFont/MetaPost \- Meta Font and Post File.
.SH FILES
.na
.B hkmeta.emf
\- MetaFont/MetaPost file hook definition
.ad
.SH EXTENSIONS
.na
\fB.mf\fR \- MetaFont file
.br
\fB.mp\fR \- MetaPost file
.ad
.SH DESCRIPTION
The \fBMeta\fR file type template provides simple hilighting of \fBMetaFont\fR
(\fC.mf\fR)  and  \fBMetaPost\fR  (\fC.mp\fR)  files,  the  template  provides
minimal  hilighting.  The same  hilighting  definition  is used for both  file
types.
.PP
File recognition is performed using the standard file extensions.
.SH NOTES
\s-1JASSPA\s0 have no idea as to the state of this file hook definition.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
