.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"
.Id $Id: m9typ046.9,v 2.2 2009-08-29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH cfml 9
.XI cfml - "Adobe Macromedia ColdFusion Markup Language" 
.XI cfm - "ColdFusion Markup Language" filetype
.XI cfc - "ColdFusion Markup Language" filetype
.SH SYNOPSIS
cfm \- ColdFusion Markup Language.
.SH FILES
.na
.B hkcfm.emf
\- ColdFusion file hook definition.
.br
.B hkcfms.emf
\- ColdFusion script file hook definition.
.ad
.SH DESCRIPTION
The \fBcmf\fR file type template provides simple hilighting and indentation of
Adobe Macromedia ColdFusion pages embedded within 
.Ht html 9 
files. The keywords from \fBColdFusion MX 7\fR are supported.
.PP
The template supports  highlighting and indention of the tags \fC<cfxxx>\fR in
addition to \fC<cfscript>\fR blocks and \fC<cfquery>\fR SQL blocks.
.SH "SEE ALSO"
.na
.Ht html 9 ,
.Hl "Supported File Types" FileTypes -
.ad
.FH
