.\"*-*- nroff -*-*************************************************************
.\"
.\"			Copyright 1999 JASSPA.
.\"			      All Rights Reserved
.\"
.\"
.\"  System        :
.\"  Module        :
.\"  Object Name   : m9typ010.9
.\"  Created By    : Jon Green
.\"  Created       : Sat Feb 6 14:22:09 1999
.\"  Last Modified : <000719.1013>
.\"
.\"  Description
.\"
.\"  Notes
.\"
.\"  History
.\"
.\"***************************************************************************
.\"
.\"  Copyright (c) 1999 JASSPA.
.\"
.\"  All Rights Reserved.
.\"
.\"  This  document  may not, in  whole  or in part, be  copied,  photocopied,
.\"  reproduced,  translated, or reduced to any  electronic  medium or machine
.\"  readable form without prior written consent from JASSPA.
.\"
.\"***************************************************************************
.\"
.Id $Id: m9typ010.9,v 2.2 2001-07-14 10:12:05 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH p 9
.XI p - "Pascal File"
.XI pas - "Pascal File"
.SH SYNOPSIS
p, pas \- Pascal files
.SH FILES
.na
.B hkpascal.emf
\- Pascal hook definition
.br
.B pascal.etf
\- Pascal template file.
.ad
.SH EXTENSIONS
.na
\fB.p\fR, \fB.pas\fR \- Pascal file
.ad
.SH DESCRIPTION
The  \fBpascal\fR  file type  template  provides  simple  hilighting of Pascal
files, the template provides minimal hilighting.
.SH BUGS
None reported.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
