.\" -*- nroff -*-
.\" This is part of the JASSPA MicroEmacs documentation files.
.\" Copyright (c) 1999-2009 JASSPA (www.jasspa.com)
.\" See the file "me.nrs" for copying and conditions.
.\"
.\"  Created By    : Jon Green
.\"  Created       : Thu Jun 10 23:48:24 1999
.\"
.Id $Id: m9typ031.9,v 2.6 2009-08-29 17:14:33 jon Exp $
.Im MicroEmacs filetype
.so me.tni
.TH vb 9
.XI vb - "Visual Basic"
.XI bas - "Visual Basic"
.XI cls - "Visual Basic"
.SH SYNOPSIS
bas, cls \- Visual Basic file
.SH FILES
.na
.B hkvb.emf
\- Visual Basic macro file.
.ad
.SH EXTENSIONS
.na
\fB.bas\fR, \fB.cls\fR
.ad
.SH "MAGIC STRINGS"
.na
\fB-!- msvb -!-\fR
.ad
.SH DESCRIPTION
The \fBVisual Basic\fR template performs the hilighting of Visual Basic files.
The file type is recognised by the standard  extension, or by the inclusion of
the magic string.
.IP \fBHilighting\fR
The  hilighting  features allows components of  the  language  to  be
differentiated and rendered in different colors.
.IP "\fBAuto Layout\fR"
The
.Hl "indentation mechanism" indent 2
is enabled which performs automatic layout of the text.
.Ht restyle-region 3
and
.Ht restyle-buffer 3
are available to reformat  (re-layout) selected sections of the buffer, or the
whole buffer, respectively. The default indentation setting is 2.
.SH "SEE ALSO"
.na
.Hl "Supported File Types" FileTypes -
.ad
.FH
