#____________________________________________________________________________
#
# Last Edited <040207.1618>
#
# Utilties makefile.
#____________________________________________________________________________
#
TOPDIR	= ..
include $(TOPDIR)/etc/makeinc
# Dependencies
all:
install:
release:
clean:
spotless: clean
	$(RM) *~
	$(RM) tags
