#!/bin/sh
echo "Here  0"
sleep 1
echo "Here  1"
sleep 1
echo "Here  2"
sleep 1
echo "Here  3"
sleep 1
echo "Here  4"
sleep 1
echo "Here  5"
sleep 1
echo "Here  6"
sleep 1
echo "Here  7"
sleep 1
echo "Here  8"
sleep 1
echo "Here  9"
sleep 1
echo "Here 10"
sleep 1
echo "Here 11"
sleep 1
echo "Here 12"
sleep 1
echo "Here 13"
sleep 1
echo "Here 14"
sleep 1
echo "Here END"
