name: Binaries Win32 (VC)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v3

    - name: Info1 Visual Studio
      shell: pwsh
      run: |
        echo ls        
        ls
        echo Get-VSSetupInstance
        Get-VSSetupInstance
        
    - name: Find Visual Studio
      shell: pwsh
      run: |
        $installationPath = Get-VSSetupInstance `
          | Select-VSSetupInstance -Require Microsoft.VisualStudio.Workload.NativeDesktop -Latest `
          | Select-Object -ExpandProperty InstallationPath
        Write-Output "VSDEVCMD=${installationPath}\Common7\Tools\VsDevCmd.bat" `
          | Out-File -FilePath "${Env:GITHUB_ENV}" -Append
        cat "${Env:GITHUB_ENV}"
        
    - name: compile mew
      shell: cmd
      run: |
        echo ::set
        set
        echo ::"%VSDEVCMD%" -arch=x86
        "%VSDEVCMD%" -arch=x86
        echo ::set
        set
        echo ::cd microemacs\src
        cd microemacs\src
        echo ::.\build.bat -t w
        .\build.bat -t w
    
    - name: compile mecw
      shell: cmd
      run: |
        "%VSDEVCMD%" -arch=x86
        set
        cd microemacs\src
        .\build.bat -t cw
        

        
        
    
