name: Binaries Win32 (VS)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - name: Find VS
      shell: pwsh
      run: |
        $installationPath = Get-VSSetupInstance `
          | Select-VSSetupInstance -Require Microsoft.VisualStudio.Workload.NativeDesktop -Latest `
          | Select-Object -ExpandProperty InstallationPath
        Write-Output "VSDEVCMD=${installationPath}\Common7\Tools\VsDevCmd.bat" `
          | Out-File -FilePath "${Env:GITHUB_ENV}" -Append
        cat "${Env:GITHUB_ENV}"
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile mec
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=x86 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        nmake -f win32vc16.mak BTYP=c
      working-directory: ./microemacs/src

    - name: Compile mew
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=x86 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        nmake -f win32vc16.mak BTYP=w
      working-directory: ./microemacs/src

    - name: Compile Static mew
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=x86 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        nmake -f win32vc16.mak BTYP=w LSTT=1
      working-directory: ./microemacs/src

    - name: Create packages
      shell: pwsh
      run: |
        md binaries-win32
        cd .\microemacs\src
        cp .\.win32vc16-release-mec\mec.exe ..\..\binaries-win32\
        cp .\.win32vc16-release-mew\mew.exe ..\..\binaries-win32\        
        cd ..\..\binaries-win32\
        Compress-Archive -Path *.exe -DestinationPath win32-bin.zip
        rm *.exe

    - name: Create mes
      shell: pwsh
      run: |
        ..\src\.win32vc16-release-mec\mec.exe -p "@mesgen" -f -p ..\src\.win32vc16s-release-mew\mew.exe -t ..\3rdparty\tfs\.win32vc16-release\tfs.exe -o ../../binaries-win32/mes-win32.exe
      working-directory: ./microemacs/mesingle

    - name: Upload Packages
      uses: actions/upload-artifact@v3
      with: 
        name: binaries-win32
        path: binaries-win32
