name: Binaries Ubuntu-20 (Linux5 intel-64)

on:
  workflow_dispatch:
    branches: [ master ]
env:
    VERSION: "202407"
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v4
     
    - name: make me binary
      run: |
        sudo apt install build-essential mingw-w64 gcc-mingw-w64-i686 
        sudo apt install libz-mingw-w64 libz-mingw-w64-dev
        sudo apt install desktop-file-utils
        make -f microemacs/actions.mk PLATFORM=linux VERSION=${VERSION}
        
    - name: Upload Artifact MicroEmacs Ubuntu 20 mec
      uses: actions/upload-artifact@v4
      with: 
         name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mec
         path: MicroEmacs_${{ env.VERSION }}_linux_mec

    - name: Upload Artifact MicroEmacs Ubuntu 20 mew
      uses: actions/upload-artifact@v4
      with: 
         name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mew
         path: MicroEmacs_${{ env.VERSION }}_linux_mew
    - name: Upload Artifact MicroEmacs Ubuntu 20 mecs
      uses: actions/upload-artifact@v4
      with: 
         name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mecs
         path: MicroEmacs_${{ env.VERSION }}_linux_mecs

    - name: Upload Artifact MicroEmacs Ubuntu 20 mews
      uses: actions/upload-artifact@v4
      with: 
         name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mews
         path: MicroEmacs_${{ env.VERSION }}_linux_mews

    - name: Upload Artifact MicroEmacs Ubuntu 20 mecws
      uses: actions/upload-artifact@v4
      with: 
         name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mecws
         path: MicroEmacs_${{ env.VERSION }}_linux_mecws

    - name: Upload Artifact tfs Ubuntu 20
      uses: actions/upload-artifact@v4
      with: 
        name: tfs_${{ env.VERSION }}_ubuntu20
        path: tfs_${{ env.VERSION }}_linux
    
