name: Binaries Linux32 (Ubuntu)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
     
    - name: Compile nroff tools
      run: |
        make
      working-directory: ./nroff

    - name: Compile mec
      run: |
        ./build.sh -t c
      working-directory: ./microemacs/src

    - name: Compile mew
      run: |
        ./build.sh -t w
      working-directory: ./microemacs/src

    - name: Generate docs
      run: |
        export PATH=`pwd`/microemacs/bin/linux5-intel64-gcc9:`pwd`/nroff/bin/linux:$PATH
        export MEPATH=`pwd`/microemacs/macros
        cd ./microemacs/doc
        make me.ehf

    - name: Create packages
      run: |
        cd ./microemacs
        zip -r linux5-bin bin
        cd doc
        mkdir macros
        mv me.ehf macros
        zip -r ../meehf macros
        
    - name: Create linux5 mesc
      run: |
        mkdir -p bin/linux5-intel64-gcc9
        ../bin/linux5-intel64-gcc9/mec -p "@mesgen" -f -p ../bin/linux5-intel64-gcc9/mec -t ../bin/linux5-intel64-gcc9/tfs -o bin/linux5-intel64-gcc9/mecs
        zip -r ../linux5-mecs bin
        rm bin/linux5-intel64-gcc9/mecs
      working-directory: ./microemacs/mesingle

    - name: Create linux5 mesw
      run: |
        mkdir -p bin/linux5-intel64-gcc9
        ../bin/linux5-intel64-gcc9/mec -p "@mesgen" -f -p ../bin/linux5-intel64-gcc9/mew -t ../bin/linux5-intel64-gcc9/tfs -o bin/linux5-intel64-gcc9/mews
        zip -r ../linux5-mews bin
        rm bin/linux5-intel64-gcc9/mews
      working-directory: ./microemacs/mesingle

    - name: Upload linux5 bin
      uses: actions/upload-artifact@v3
      with: 
        name: linux5-bin.zip
        path: microemacs/linux5-bin.zip
    
    - name: Upload linux5 mecs
      uses: actions/upload-artifact@v3
      with: 
        name: linux5-mecs.zip
        path: microemacs/linux5-mecs.zip

    - name: Upload linux5 mews
      uses: actions/upload-artifact@v3
      with: 
        name: linux5-mews.zip
        path: microemacs/linux5-mews.zip

    - name: Upload MicroEmacs help
      uses: actions/upload-artifact@v3
      with: 
        name: meehf.zip
        path: microemacs/meehf.zip
