name: Binaries Win32 (VC)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - name: Info1 Visual Studio
      shell: pwsh
      run: |
        echo ls        
        ls
        echo Get-VSSetupInstance
        Get-VSSetupInstance
        
    - name: Find Visual Studio
      shell: pwsh
      run: |
        $installationPath = Get-VSSetupInstance `
          | Select-VSSetupInstance -Require Microsoft.VisualStudio.Workload.NativeDesktop -Latest `
          | Select-Object -ExpandProperty InstallationPath
        Write-Output "VSDEVCMD=${installationPath}\Common7\Tools\VsDevCmd.bat" `
          | Out-File -FilePath "${Env:GITHUB_ENV}" -Append
        cat "${Env:GITHUB_ENV}"
        
    - name: Compile mew
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=x86 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        echo evn
        dir env:
        echo which nmake
        get-command nmake
        echo test nmake
        nmake /?
        echo cat VsDevCmd
        cat "${Env:VSDEVCMD}"

        
        
    
