name: Binaries Linux32 (Ubuntu)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
     
    - name: Compile nroff tools
      run: |
        cd ./nroff
        make

    - name: Compile mec
      run: |
        cd ./microemacs/src
        ./build.sh -t c
    - name: Compile mew
      run: |
        cd ./microemacs/src
        ./build.sh -t w
    - name: Upload linux5 bin
      uses: actions/upload-artifact@v4
      with: 
        name: linux5-bin
        path: microemacs/bin

    - name: Generate docs
      run: |
        export PATH=`pwd`/microemacs/bin/linux5-intel64-gcc9:`pwd`/nroff/bin/linux:$PATH
        export MEPATH=`pwd`/microemacs/macros
        cd ./microemacs/doc
        make me.ehf
        rm -rf macros
        mkdir macros
        mv me.ehf macros
    - name: Upload docs
      uses: actions/upload-artifact@v4
      with: 
        name: meehf
        path: macros
        
    - name: Create linux5 mecs
      run: |
        cd ./microemacs/mesingle
        rm -rf bin
        mkdir -p bin/linux5-intel64-gcc9
        ../bin/linux5-intel64-gcc9/mec -p "@mesgen" -f -p ../bin/linux5-intel64-gcc9/mec -t ../bin/linux5-intel64-gcc9/tfs -o bin/linux5-intel64-gcc9/mecs
    - name: Upload linux5 mecs
      uses: actions/upload-artifact@v4
      with: 
        name: linux5-mecs
        path: microemacs/mesingle/bin

    - name: Create linux5 mews
      run: |
        cd ./microemacs/mesingle
        rm -rf bin
        mkdir -p bin/linux5-intel64-gcc9
        ../bin/linux5-intel64-gcc9/mec -p "@mesgen" -f -p ../bin/linux5-intel64-gcc9/mew -t ../bin/linux5-intel64-gcc9/tfs -o bin/linux5-intel64-gcc9/mews
    - name: Upload linux5 mews
      uses: actions/upload-artifact@v4
      with: 
        name: linux5-mews
        path: microemacs/mesingle/bin/linux5-intel64-gcc9/mews

    
