name: Binaries Windows Server (not working)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
     
    - name: download winlibs
      shell: cmd
      run: |
        curl -OL https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-16.0.0-10.0.0-ucrt-r5/winlibs-i686-posix-dwarf-gcc-12.2.0-llvm-16.0.0-mingw-w64ucrt-10.0.0-r5.zip
        unzip -q winlibs-i686-posix-dwarf-gcc-12.2.0-llvm-16.0.0-mingw-w64ucrt-10.0.0-r5.zip
        PATH=%CD%\mingw32\bin;%PATH%
        gcc --version
    - name: compile zlib
      shell: cmd
      run: |
        cd microemacs/3rdparty/zlib 
        mingw32-make -f win32mingw.mak
        ls 
        cd ../../..
    - name: compile tfs
      shell:  cmd
      run: |
        cd microemacs/3rdparty/tfs
        mingw32-make -f win32mingw.mak
        ls
        cd ../../..
    - name: compile mew
      shell: cmd
      run: |
        PATH=%CD%\mingw32\bin;%PATH%
        gcc -v
        cd microemacs/src
        mingw32-make -f win32mingw.mak
        ls 
    - name: Upload Artifact zlib
      uses: actions/upload-artifact@v3
      with: 
        name: build-zlib
        path: microemacs/3rdparty/zlib/.win32mingw-release
    - name: Upload Artifact tfs
      uses: actions/upload-artifact@v3
      with: 
        name: build-tfs
        path: microemacs/3rdparty/tfs/.win32mingw-release
        

        
        
    
