name: Binaries MacOS-13

on:
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read
env:
    VERSION: "202407"
jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies on MacOS and compile and produce mecw, mec and standalone ME application 
        run: |
           brew install xquartz
           brew install make
           export PATH=/usr/local/opt/make/libexec/gnubin/:$PATH
           cd microemacs/3rdparty/zlib
           make -f macoscc.mak
           cd ../../../
           make -f microemacs/actions.mk PLATFORM=macos VERSION=${VERSION}
      - name: Upload Artifact MicroEmacs macOS 13 mec
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos13_mec
           path: MicroEmacs_${{ env.VERSION }}_macos_mec

      - name: Upload Artifact MicroEmacs macOS 13 mew
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos13_mew
           path: MicroEmacs_${{ env.VERSION }}_macos_mew
      - name: Upload Artifact MicroEmacs macOS 13 mecs
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos13_mecs
           path: MicroEmacs_${{ env.VERSION }}_macos_mecs

      - name: Upload Artifact MicroEmacs macOS 13 mews
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos13_mews
           path: MicroEmacs_${{ env.VERSION }}_macos_mews

      - name: Upload Artifact MicroEmacs macOS 13 mecws
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos13_mecws
           path: MicroEmacs_${{ env.VERSION }}_macos_mecws

      - name: Upload Artifact tfs macOS 13
        uses: actions/upload-artifact@v4
        with: 
          name: tfs_${{ env.VERSION }}_macos13
          path: tfs_${{ env.VERSION }}_macos
           
