name: Binaries MacOS-12

on:
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies on MacOS and compile and produce mecw, mec and standalone ME application 
        run: |
           brew install xquartz
           brew install make
           export PATH=/usr/local/opt/make/libexec/gnubin/:$PATH
           make -f microemacs/actions.mk PLATFORM=macos12 VERSION=${VERSION}
      - name: Upload Artifact MicroEmacs macS 12 mec
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos12_mec
           path: MicroEmacs_${{ env.VERSION }}_macos12_mec

      - name: Upload Artifact MicroEmacs macOS 12 mew
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos12_mew
           path: MicroEmacs_${{ env.VERSION }}_macos12_mew
      - name: Upload Artifact MicroEmacs macOS 12 mecs
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos12_mecs
           path: MicroEmacs_${{ env.VERSION }}_macos12_mecs

      - name: Upload Artifact MicroEmacs macOS 12 mews
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos12_mews
           path: MicroEmacs_${{ env.VERSION }}_macos12_mews

      - name: Upload Artifact MicroEmacs macOS 12 mecws
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos12_mecws
           path: MicroEmacs_${{ env.VERSION }}_macos12_mecws

      - name: Upload Artifact tfs macOS 12
        uses: actions/upload-artifact@v4
        with: 
          name: tfs_${{ env.VERSION }}_macos12
          path: tfs_${{ env.VERSION }}_macos12
           
