name: Build macOS (macos-latest)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - name: Install dependencies
      run: |
         brew install xquartz
         echo Macos VER 1
         sw_vers
         echo Macos VER 2
         sw_vers -productVersion 
         sw_vers -productVersion | cut -f 1 -d .
         echo Macos OpenSSL 1
         ls /opt/homebrew/opt/openssl@3/
         echo Macos OpenSSL 2
         ls /opt/homebrew/opt/openssl@3/lib
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile macos apple mec
      run: |
        mkdir downloads
        mkdir packages
        cd ./microemacs/src
        ./build.sh -t c -a apple
    - name: Compile macos apple mew
      run: |
        cd ./microemacs/src
        ./build.sh -t w -a apple
    - name: Create macos apple binaries download
      run: |
        cd ./microemacs/bin
        mv macos14-apple64-* macos14-apple64
        rm ./.gitignore
        cd ..
        export MEVER=`./bin/macos14-apple64/mec -p @contribs/ver.emf`
        zip -r ../downloads/Jasspa_MicroEmacs_${MEVER}_macos_apple_binaries bin license.txt readme.txt

    - name: Compile macos intel mec
      run: |
        cd ./microemacs/src
        ./build.sh -t c -a intel
    - name: Compile macos intel mew
      run: |
        cd ./microemacs/src
        ./build.sh -t w -a intel
    - name: Create macos intel binaries download
      run: |
        cd ./microemacs/bin
        mv macos14-intel64-* macos14-intel64
        cd ..
        export MEVER=`./bin/macos14-apple64/mec -p @contribs/ver.emf`
        zip -r ../downloads/Jasspa_MicroEmacs_${MEVER}_macos_intel_binaries bin/macos14-intel64 license.txt readme.txt

    - name: Create macos apple mecs
      run: |
        export MEVER=`./microemacs/bin/macos14-apple64/mec -p @microemacs/contribs/ver.emf`
        cd ./microemacs/mesingle
        rm -rf bin
        mkdir -p bin/macos14-apple64
        ../bin/macos14-apple64/mec -p "@mesgen" -f -p ../bin/macos14-apple64/mec -t ../bin/macos14-apple64/tfs -o bin/macos14-apple64/mecs
        cp ../license.txt ./
        cp ../readme.txt ./
        zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_macos_apple_mecs bin license.txt readme.txt

    - name: Create macos apple mews
      run: |
        export MEVER=`./microemacs/bin/macos14-apple64/mec -p @microemacs/contribs/ver.emf`
        cd ./microemacs/mesingle
        rm -rf bin
        mkdir -p bin/macos14-apple64
        ../bin/macos14-apple64/mec -p "@mesgen" -f -p ../bin/macos14-apple64/mew -t ../bin/macos14-apple64/tfs -o bin/macos14-apple64/mews
        zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_macos_apple_mews bin license.txt readme.txt

    - name: Create macos apple OpenSSL download
      run: |
        cd ./microemacs/
        export MEVER=`./bin/macos14-apple64/mec -p @contribs/ver.emf`
        rm -rf tfs
        mkdir -p tfs/bin/macos14-apple64
        cd tfs
        cp /opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib bin/macos14-apple64
        cp /opt/homebrew/opt/openssl@3/lib/libssl.3.dylib bin/macos14-apple64
        cp /opt/homebrew/opt/openssl@3/LICENSE.txt bin/macos14-apple64
        cp /opt/homebrew/opt/openssl@3/README.md bin/macos14-apple64
        zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_macos_apple_openssl bin
        cd ..
        ./bin/macos14-apple64/tfs -o ../packages/Jasspa_MicroEmacs_${MEVER}_macos_apple64_openssl.tfs -a ./mesingle/tfs_hd tfs


    - name: Create macos intel mecs
      run: |
        export MEVER=`./microemacs/bin/macos14-apple64/mec -p @microemacs/contribs/ver.emf`
        cd ./microemacs/mesingle
        rm -rf bin
        mkdir -p bin/macos14-intel64
        ../bin/macos14-apple64/mec -p "@mesgen" -f -p ../bin/macos14-intel64/mec -t ../bin/macos14-apple64/tfs -o bin/macos14-intel64/mecs
        zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_macos_intel_mecs bin
    - name: Create macos intel mews
      run: |
        export MEVER=`./microemacs/bin/macos14-apple64/mec -p @microemacs/contribs/ver.emf`
        cd ./microemacs/mesingle
        rm -rf bin
        mkdir -p bin/macos14-intel64
        ../bin/macos14-apple64/mec -p "@mesgen" -f -p ../bin/macos14-intel64/mew -t ../bin/macos14-apple64/tfs -o bin/macos14-intel64/mews
        zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_macos_intel_mews bin

    - name: Upload macos downloads
      uses: actions/upload-artifact@v4
      with: 
        name: macos-downloads
        path: downloads
        
    - name: Upload macos packages
      uses: actions/upload-artifact@v4
      with: 
        name: macos-packages
        path: packages
