name: Linux5 build (Ubuntu-20)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
     
    - name: Compile nroff tools
      run: |
        mkdir downloads
        mkdir packages
        cd ./nroff
        make

    - name: Compile linux5 mec
      run: |
        cd ./microemacs/src
        ./build.sh -t c
    - name: Compile linux5 mew
      run: |
        cd ./microemacs/src
        ./build.sh -t w
    - name: Create linux5 bin download
      run: |
        cd ./microemacs/bin
        mv linux5-intel64-gcc9 linux5-intel64
        cd ..
        export MEVER=`./bin/linux5-intel64/mec -p @contribs/ver.emf`
        zip -r ../downloads/Jasspa_MicroEmacs_${MEVER}_linux5_bin bin

    - name: Create linux5 mecs
      run: |
        export MEVER=`./microemacs/bin/linux5-intel64/mec -p @microemacs/contribs/ver.emf`
        cd ./microemacs/mesingle
        rm -rf bin
        mkdir -p bin/linux5-intel64
        ../bin/linux5-intel64/mec -p "@mesgen" -f -p ../bin/linux5-intel64/mec -t ../bin/linux5-intel64/tfs -o bin/linux5-intel64/mecs
        zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_linux5_mecs bin
        
    - name: Create linux5 mews
      run: |
        export MEVER=`./microemacs/bin/linux5-intel64/mec -p @microemacs/contribs/ver.emf`
        cd ./microemacs/mesingle
        rm -rf bin
        mkdir -p bin/linux5-intel64
        ../bin/linux5-intel64/mec -p "@mesgen" -f -p ../bin/linux5-intel64/mew -t ../bin/linux5-intel64/tfs -o bin/linux5-intel64/mews
        zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_linux5_mews bin

    - name: Generate docs
      run: |
        export PATH=`pwd`/microemacs/bin/linux5-intel64:`pwd`/nroff/bin/linux:$PATH
        export MEPATH=`pwd`/microemacs/macros
        export MEVER=`mec -p @microemacs/contribs/ver.emf`
        cd ./microemacs/doc
        make me.ehf
        rm -rf tfs
        mkdir -p tfs/macros
        mv me.ehf tfs/macros
        cd tfs
        zip -r ../../../downloads/Jasspa_MicroEmacs_${MEVER}_hlpehf macros
        cd ..
        ../bin/linux5-intel64/tfs -o ../../packages/Jasspa_MicroEmacs_${MEVER}_hlpehf.tfs -a ../mesingle/tfs_hd tfs

    - name: Upload linux5 downloads
      uses: actions/upload-artifact@v4
      with: 
        name: linux5-downloads
        path: downloads
        
    - name: Upload linux5 packages
      uses: actions/upload-artifact@v4
      with: 
        name: linux5-packages
        path: packages
    
