name: Build macOS (macos-latest)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - name: Install dependencies
      run: |
         which cc
         cc --version
         which make
         make --version
         /usr/bin/xcrun --sdk macosx -show-sdk-version
         which cc
         cc --version
         brew install xquartz
         which cc
         cc --version
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile macos mec
      run: |
        cd ./microemacs/src
        ./build.sh -t c
    - name: Compile macos mew
      run: |
        export PATH=/usr/local/opt/make/libexec/gnubin/:$PATH
        cd ./microemacs/src
        ./build.sh -t w
           
