name: Build Homebrew formulas (Ubuntu-20)

on:
  workflow_dispatch:
    branches: [ master ]
env:
   VERSION: "20240902"

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Create Brew Recipes
        run: |
          cd microemacs/brew
          mkdir recipes
          make tpl2rb version=${VERSION}
          cp *.rb recipes 


      - name: Upload linux downloads
        uses: actions/upload-artifact@v4
        with: 
          name: Jasspa_MicroEmacs_${{ env.VERSION }}-formula-downloads
          path: microemacs/brew/recipes
