name: Build macOS (macos-latest)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - name: Install dependencies
      run: |
         which cc
         cc --version
         which make
         make --version
         brew install xquartz
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile macos apple mec
      run: |
        cd ./microemacs/src
        ./build.sh -t c -a apple
    - name: Compile macos apple mew
      run: |
        cd ./microemacs/src
        ./build.sh -t w -a apple
    - name: Compile macos intel mec
      run: |
        cd ./microemacs/src
        ./build.sh -t c -a intel
    - name: Compile macos intel mew
      run: |
        cd ./microemacs/src
        ./build.sh -t w -a intel
           
