name: Build linux5 intel 64 (ubuntu-20)

on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: 'Branch, tag or commit SHA1 to build'
        default: ''
        required: false
        type: string

      refToHelpAsset:
        description: 'Run-ID of build with help-ehf asset (not used)'
        default: ''
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-20-01
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
      - name: Install dependencies
        run: |
           echo INFO: uname -a
           uname -a
           
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.refToBuild }}
       
      - name: Compile linux5-intel mec
        run: |
          cd ./microemacs/src
          ./build.sh -t c

      - name: Compile linux5-intel mew
        run: |
          cd ./microemacs/src
          ./build.sh -t w

      - name: Create linux5-intel binaries download
        run: |
          cd ./microemacs/bin
          mv linux5-intel64-gcc9 linux5-intel64
          rm ./.gitignore
          cd ..
          mv release_readme.txt readme.txt
          export MEVER=`./bin/linux5-intel64/mec -p @contribs/ver.emf`
          zip -r ../downloads/Jasspa_MicroEmacs_${MEVER}_bin_linux5_intel_binaries bin LICENSE readme.txt

      - name: Create linux5-intel mesc
        run: |
          export MEVER=`./microemacs/bin/linux5-intel64/mec -p @microemacs/contribs/ver.emf`
          cd ./microemacs/mesingle
          rm -rf bin/linux5-intel64
          mkdir -p bin/linux5-intel64
          ../bin/linux5-intel64/mec -p "@./mesgen" -f -p ../bin/linux5-intel64/mec -t ../bin/linux5-intel64/tfs -o bin/linux5-intel64/mesc
          cp ../LICENSE ./
          cp ../readme.txt ./
          zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_abin_linux5_intel_mesc bin LICENSE readme.txt
          
      - name: Create linux5-intel mesw
        run: |
          export MEVER=`./microemacs/bin/linux5-intel64/mec -p @microemacs/contribs/ver.emf`
          cd ./microemacs/mesingle
          rm -rf bin/linux5-intel64
          mkdir -p bin/linux5-intel64
          ../bin/linux5-intel64/mec -p "@./mesgen" -f -p ../bin/linux5-intel64/mew -t ../bin/linux5-intel64/tfs -o bin/linux5-intel64/mesw
          zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_abin_linux5_intel_mesw bin LICENSE readme.txt

      - name: Create linux5-intel OpenSSL download
        run: |
          cd ./microemacs/
          export MEVER=`./bin/linux5-intel64/mec -p @contribs/ver.emf`
          rm -rf tfs
          mkdir -p tfs/bin/linux5-intel64
          cd tfs/bin/linux5-intel64
          cp /usr/lib/x86_64-linux-gnu/ibcrypto.so .
          cp /usr/lib/x86_64-linux-gnu/libssl.so .
          cd ../..
          zip -r ../../downloads/Jasspa_MicroEmacs_${MEVER}_bin_linux5_intel_openssl bin
          cd ..
          ./bin/linux5-intel64/tfs ../packages/Jasspa_MicroEmacs_${MEVER}_openssl_linux5_intel64.tfs tfs

      - name: Upload linux5-intel downloads
        uses: actions/upload-artifact@v4
        with: 
          name: linux5-intel-downloads
          path: downloads
          
      - name: Upload linux5-intel packages
        uses: actions/upload-artifact@v4
        with: 
          name: linux5-intel-packages
          path: packages

