name: Build nroff tools and documentation

on:
  workflow_dispatch:
    branches: [ master ]
env:
    VERSION: "202406"
jobs:
  build-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
     
    - name: make nroff
      run: |
        cd nroff
        make
        cd ..
    - name: make me-binaries
      run: |
        sudo apt install libxt-dev
        make -f microemacs/actions.mk PLATFORM=ubuntu22 VERSION=${VERSION}
    - name: make me doc
      run: |  
        export PATH=`pwd`/nroff/bin$PATH
        cd ../microemacs/doc 
        make
    - name: Upload Artifact nroff tools
      uses: actions/upload-artifact@v4
      with: 
        name: nroff_bin_${{ env.VERSION }}
        path: nroff/bin/linux


