name: Release Ubuntu Linux 20, 22, 24, MacOS 11 (INTEL), MacOS 14 (ARM)

on:
  workflow_dispatch:
    branches: [ master ]
env:
    VERSION: "202406"
jobs:
  build-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
     
    - name: make me-binaries
      run: |
        make -f microemacs/actions.mk PLATFORM=ubuntu20 VERSION=${VERSION}
    - name: Upload Artifact MicroEmacs Ubuntu 20 mec
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mec
        path: MicroEmacs_${{ env.VERSION }}_ubuntu20_mec
    - name: Upload Artifact MicroEmacs Ubuntu 20 mew
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mew
        path: MicroEmacs_${{ env.VERSION }}_ubuntu20_mew
    - name: Upload Artifact MicroEmacs_ Ubuntu 20 mecs
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mecs
        path: MicroEmacs_${{ env.VERSION }}_ubuntu20_mecs
    - name: Upload Artifact MicroEmacs Ubuntu 20 mew
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mews
        path: MicroEmacs_${{ env.VERSION }}_ubuntu20_mews

    - name: Upload Artifact MicroEmacs Ubuntu 20 mecws
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu20_mecws
        path: MicroEmacs_${{ env.VERSION }}_ubuntu20_mecws

    - name: Upload Artifact tfs Ubuntu 20
      uses: actions/upload-artifact@v4
      with: 
        name: tfs_${{ env.VERSION }}_ubuntu20
        path: tfs_${{ env.VERSION }}_ubuntu20

    - name: Upload Artifact macros
      uses: actions/upload-artifact@v4
      with: 
        name: macros_${{ env.VERSION }}
        path: macros_${{ env.VERSION }}


  build-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
     
    - name: make me-binaries
      run: |
        make -f microemacs/actions.mk PLATFORM=ubuntu22 VERSION=${VERSION}
    - name: Upload Artifact MicroEmacs Ubuntu 22 mec
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu22_mec
        path: MicroEmacs_${{ env.VERSION }}_ubuntu22_mec
    
    - name: Upload Artifact MicroEmacs Ubuntu 22 mew
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu22_mew
        path: MicroEmacs_${{ env.VERSION }}_ubuntu22_mew
    
    - name: Upload Artifact MicroEmacs Ubuntu 22 mecs
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu22_mecs
        path: MicroEmacs_${{ env.VERSION }}_ubuntu22_mecs

    - name: Upload Artifact MicroEmacs Ubuntu 22 mews
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu22_mews
        path: MicroEmacs_${{ env.VERSION }}_ubuntu22_mews

    - name: Upload Artifact MicroEmacs Ubuntu 22 mecws
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu22_mecws
        path: MicroEmacs_${{ env.VERSION }}_ubuntu22_mecws

    - name: Upload Artifact tfs Ubuntu 22
      uses: actions/upload-artifact@v4
      with: 
        name: tfs_${{ env.VERSION }}_ubuntu22
        path: tfs_${{ env.VERSION }}_ubuntu22

  build-ubuntu-24:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
     
    - name: make me-binaries
      run: |
        sudo apt install libxt-dev
        make -f microemacs/actions.mk PLATFORM=ubuntu24 VERSION=${VERSION}
    - name: Upload Artifact MicroEmacs Ubuntu 24 mec
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu24_mec
        path: MicroEmacs_${{ env.VERSION }}_ubuntu24_mec
    
    - name: Upload Artifact MicroEmacs Ubuntu 24 mew
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu24_mew
        path: MicroEmacs_${{ env.VERSION }}_ubuntu24_mew
    
    - name: Upload Artifact MicroEmacs Ubuntu 24 mecs
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu24_mecs
        path: MicroEmacs_${{ env.VERSION }}_ubuntu24_mecs

    - name: Upload Artifact MicroEmacs Ubuntu 24 mews
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu24_mews
        path: MicroEmacs_${{ env.VERSION }}_ubuntu24_mews

    - name: Upload Artifact MicroEmacs Ubuntu 24 mecws
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs_${{ env.VERSION }}_ubuntu24_mecws
        path: MicroEmacs_${{ env.VERSION }}_ubuntu24_mecws

    - name: Upload Artifact tfs Ubuntu 24
      uses: actions/upload-artifact@v4
      with: 
        name: tfs_${{ env.VERSION }}_ubuntu24
        path: tfs_${{ env.VERSION }}_ubuntu24

  build-macos-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies on MacOS and compile and produce mecw, mec and standalone ME application 
        run: |
           brew install xquartz
           brew install make
           export PATH=/usr/local/opt/make/libexec/gnubin/:$PATH
           make -f microemacs/actions.mk PLATFORM=macos11 VERSION=${VERSION}
      - name: Upload Artifact MicroEmacs macS 11 mec
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos11_mec
           path: MicroEmacs_${{ env.VERSION }}_macos11_mec

      - name: Upload Artifact MicroEmacs macOS 11 mew
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos11_mew
           path: MicroEmacs_${{ env.VERSION }}_macos11_mew
      - name: Upload Artifact MicroEmacs macOS 11 mecs
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos11_mecs
           path: MicroEmacs_${{ env.VERSION }}_macos11_mecs

      - name: Upload Artifact MicroEmacs macOS 11 mews
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos11_mews
           path: MicroEmacs_${{ env.VERSION }}_macos11_mews

      - name: Upload Artifact MicroEmacs macOS 11 mecws
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos11_mecws
           path: MicroEmacs_${{ env.VERSION }}_macos11_mecws

      - name: Upload Artifact tfs macOS 11
        uses: actions/upload-artifact@v4
        with: 
          name: tfs_${{ env.VERSION }}_macos11
          path: tfs_${{ env.VERSION }}_macos11


  build-macos-14:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies on MacOS and compile and produce mecw, mec and standalone ME application 
        run: |
           brew install xquartz
           brew install make
           export PATH=/usr/local/opt/make/libexec/gnubin/:$PATH
           make -f microemacs/actions.mk PLATFORM=macos14 VERSION=${VERSION}
      - name: Upload Artifact MicroEmacs macOS 14 mec
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos14_mec
           path: MicroEmacs_${{ env.VERSION }}_macos14_mec

      - name: Upload Artifact MicroEmacs macOS 14 mew
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos14_mew
           path: MicroEmacs_${{ env.VERSION }}_macos14_mew
      - name: Upload Artifact MicroEmacs macOS 14 mecs
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos14_mecs
           path: MicroEmacs_${{ env.VERSION }}_macos14_mecs

      - name: Upload Artifact MicroEmacs macOS 14 mews
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos14_mews
           path: MicroEmacs_${{ env.VERSION }}_macos14_mews

      - name: Upload Artifact MicroEmacs macOS 14 mecws
        uses: actions/upload-artifact@v4
        with: 
           name: MicroEmacs_${{ env.VERSION }}_macos14_mecws
           path: MicroEmacs_${{ env.VERSION }}_macos14_mecws

      - name: Upload Artifact tfs macOS 14
        uses: actions/upload-artifact@v4
        with: 
          name: tfs_${{ env.VERSION }}_macos14
          path: tfs_${{ env.VERSION }}_macos14

