name: Test Homebrew formulas (Ubuntu-20,22,24, MacOS 12,13,14)

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build1:
    runs-on: ubuntu-20.04
    name: Build on Ubuntu 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Install MicroEmacs mec
        run: |
          uname -a
          export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
          brew tap mittelmark/mittelmark
          brew install microemacs-mec
          ls /home/linuxbrew/.linuxbrew/bin
          find /home/linuxbrew/.linuxbrew -name "*mec*"
          ls -l /home/linuxbrew/.linuxbrew/opt/microemacs-mec
          ##mec -V - is not in bin
  build2:
    runs-on: ubuntu-22.04
    name: Build on Ubuntu 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Install MicroEmacs mec
        run: |
          uname -a
          export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
          brew tap mittelmark/mittelmark
          brew install microemacs-mec
          ls /home/linuxbrew/.linuxbrew/bin
          find /home/linuxbrew/.linuxbrew -name "*mec*"
          ls -l /home/linuxbrew/.linuxbrew/opt/microemacs-mec
          mec -V

  build3:
    runs-on: ubuntu-24.04
    name: Build on Ubuntu 24

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Install MicroEmacs mec
        run: |
          uname -a
          export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
          brew tap mittelmark/mittelmark
          brew install microemacs-mec
          ls /home/linuxbrew/.linuxbrew/bin
          find /home/linuxbrew/.linuxbrew -name "*mec*"
          ls -l /home/linuxbrew/.linuxbrew/opt/microemacs-mec
          mec -V

  build3:
    runs-on: macos-12
    name: Build on MacOS 12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Install MicroEmacs mec
        run: |
          uname -a
          #export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
          which brew
          brew tap mittelmark/mittelmark
          brew install microemacs-mec
          #ls /home/linuxbrew/.linuxbrew/bin
          #find /usr -name "*mec*"
          #ls -l /home/linuxbrew/.linuxbrew/opt/microemacs-mec
          mec -V

  build5:
    runs-on: macos-13
    name: Build on MacOS 13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Install MicroEmacs mec
        run: |
          uname -a
          #export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
          which brew
          brew tap mittelmark/mittelmark
          brew install microemacs-mec
          #ls /home/linuxbrew/.linuxbrew/bin
          #find /usr -name "*mec*"
          #ls -l /home/linuxbrew/.linuxbrew/opt/microemacs-mec
          mec -V

  build6:
    runs-on: macos-14
    name: Build on MacOS 14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Install MicroEmacs mec
        run: |
          uname -a
          #export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
          which brew
          brew tap mittelmark/mittelmark
          brew install microemacs-mec
          #ls /home/linuxbrew/.linuxbrew/bin
          #find /usr -name "*mec*"
          #ls -l /home/linuxbrew/.linuxbrew/opt/microemacs-mec
          mec -V

